#!/bin/bash
# Driver: runs the UNMODIFIED data/verification/speed-2026-09-08/bench_two_engines.js once per
# release, one process per release. Passes alternate forward/reverse so time-of-day contention is
# not confounded with release order. Nothing here measures; it only schedules.
#
# --protocol-events is read by engine/game_differential.js, which the benchmark requires only for
# buildPair/freshBodies. The live data/protocol-events.json was regenerated by an ENGINE agent at
# 2026-09-08T05:36Z mid-pass-1 and its load guard then refused every release with a different
# TRACE_EVENTS claim. See make_proto_pins.js: the pinned file is inert for a run that compares no
# protocol, and the pass-1 vs pass-3 control in the report is what proves it.
cd "C:/Users/willj/Projects/Pokemon/ABRA"
export SHOWDOWN_PATH='C:\Users\willj\Projects\Pokemon\pokemon-showdown'
OUT=data/verification/speed-bisect-2026-09-08
OUTW='data\verification\speed-bisect-2026-09-08'
PASS=$1
IDS=$(cat $OUT/candidates.txt)
if [ "$2" = "rev" ]; then IDS=$(echo "$IDS" | tac); fi
for id in $IDS; do
  if [ -f "$OUT/r-$id-p$PASS.json" ]; then continue; fi
  echo "=== pass $PASS $id $(date -u +%H:%M:%S)"
  cmd.exe //c "tools\lownode.cmd data\verification\speed-2026-09-08\bench_two_engines.js --release $id --team-store data\team-pool-frozen --protocol-events data/verification/speed-bisect-2026-09-08/proto/$id.json --pairs 20 --per-pair 5 --reps 2 --caps 60 --out $OUTW\r-$id-p$PASS.json > $OUTW\r-$id-p$PASS.log 2>&1"
  echo "    exit=$?"
done
echo "PASS $PASS DONE $(date -u)"
