/* generated_audit.js — EVERY generated file in this repository, and whether it can PROVE it still
 * matches the source it was built from.
 *
 *   node engine/generated_audit.js              the report, and a non-zero exit if anything DRIFTED
 *   node engine/generated_audit.js --no-rebuild membership + declarations only; spawn no builder
 *   node engine/generated_audit.js --list       one line per file, machine-readable
 *   node engine/generated_audit.js --break      self-test: prove this check can go RED (see below)
 *
 * ══ WHY THIS EXISTS ═════════════════════════════════════════════════════════════════════════════
 *
 * `data/abra-tags.js` is `data/tags.json` wrapped as a browser global, and it is frozen into every
 * engine release. It has drifted from its source FOUR times; the fourth was 38 minutes after the
 * third was fixed. Both files carry an IDENTICAL `generated` stamp — the copy inherits the source's
 * timestamp verbatim — so no staleness heuristic can ever see the drift. Care does not close this.
 *
 * Two checks already existed and neither could see it as a CLASS:
 *   - engine/artifact_audit.js check G watches `data/*.js` that declare a `GENERATED by` header.
 *     One directory, one extension, one kind of declaration.
 *   - engine/provenance.js derives a WRITER for every artifact under data/, which is the right
 *     enumeration, and then judges STALENESS rather than AGREEMENT.
 *
 * This file is the join: provenance's enumeration, artifact_audit's question, over the whole tree.
 *
 * ══ WHAT SHAPE THIS MATCHES ═════════════════════════════════════════════════════════════════════
 *
 * A file is GENERATED here if either door says so, and the two doors are independent on purpose —
 * a file that stops declaring itself is still caught by the writer scan, and a file no writer scan
 * can reach is still caught by its own header:
 *
 *   DOOR 1  SELF-DECLARED. The file's own first bytes say `GENERATED ... by <script>`, or (JSON) it
 *           carries `by` / `generated_by` / `written_by` / `generator` / `provenance.*`.
 *   DOOR 2  SOURCE-DERIVED. engine/provenance.js scanned engine/, build/ and tests/ for a write call
 *           naming the file, and recorded the result in data/provenance-stamp.json `graph_files`.
 *           That list is READ here, never re-derived — two implementations of one fact is this
 *           repository's most expensive recurring failure.
 *
 * Membership is the UNION. Nothing is typed. A generated file added tomorrow by a script nobody has
 * written yet joins this audit by existing, which is the whole point: `tests/test-mc-key.js` was a
 * list of known-bad spellings and the third instance of the species-key bug used a spelling that was
 * not on the list.
 *
 * ══ WHAT WOULD WALK PAST IT — READ THIS BEFORE TRUSTING A GREEN RUN ═════════════════════════════
 *
 * This section is the difference between coverage and the appearance of it. Five things get through:
 *
 *  1. THE TRIPLE-BLIND FILE. Generated, declares no header, no script in engine/ build/ tests/ names
 *     it beside a write, and it is untracked by git. All three doors shut. Nothing here sees it.
 *  2. A BUILDER WITH NO `--check`. Membership is known and drift is NOT DETECTABLE. Those files are
 *     printed under UNPROVABLE with their builder named. They are counted, not proved — and a count
 *     of unprovable files is the honest output, not a pass.
 *  3. A `--check` THAT ASKS THE WRONG QUESTION. The comparison is the builder's own, deliberately
 *     (see below), so a builder that compares the wrong thing gives the wrong answer with this
 *     file's blessing. `build/build_browser_data.js --check` compares the PAYLOAD and not the bytes,
 *     so a header or date-stamp difference passes it by design.
 *  4. A FILE GENERATED OUTSIDE THIS REPOSITORY and pasted in. It has no builder here to re-run.
 *  5. A STALE `provenance-stamp.json`. Door 2 is only as wide as the last provenance run. This file
 *     prints the stamp's age and says so rather than quietly covering less than it looks like.
 *
 * ══ THE COMPARISON IS THE BUILDER'S OWN `--check`, NEVER A RE-IMPLEMENTATION ════════════════════
 *
 * tests/test-guru-derived.js established that pattern in 2026-08-04 and artifact_audit check G
 * reused it in 2026-08-25. A second implementation of the wrapper stops being right the moment the
 * wrapper changes shape, and then reports a drift that is really its own staleness.
 *
 * ══ A `--check` COMPARES BYTES, AND THE BYTES ON DISK ARE NOT ALWAYS THE BYTES IN THE REPO ══════
 *
 * `core.autocrlf` is true on this machine. A file that git last WROTE (checkout, stash, restore)
 * carries CRLF on disk; a file a GENERATOR last wrote carries LF. Both hash to the same blob, so
 * `git status` is clean and `git diff` is empty — and a byte comparison against what the builder
 * would write is RED for a reason that is not drift. Measured 2026-08-26: `data/abra-tags.js` holds
 * 41,252 CR bytes and `data/engine-data.js` holds 13, and every other generated bundle holds none.
 *
 * That is a real defect and it is NOT the same defect as drift, so it gets its own verdict —
 * CHECKOUT-EOL — with its own count and its own fix. Folding it into DRIFTED would make the drift
 * count a number nobody believes; folding it into `ok` would leave check G permanently red for a
 * cause nobody had named, which is how a gate becomes "one of the known failures".
 *
 * ══ THE SELF-TEST — A CHECK THAT CANNOT GO RED IS NOT A CHECK ═══════════════════════════════════
 *
 *   node engine/generated_audit.js --break
 *
 * Copies TWO pairs built by TWO DIFFERENT builders into a scratch tree with its own git index, runs
 * this file against it clean and then damaged, and requires opposite answers with BOTH files named.
 * The control leg is not decoration: a fixture that is red both ways proves nothing. Nothing in the
 * real tree is written — which matters, because `data/abra-tags.js` is frozen into every engine
 * release and a rebuild of it under a live measurement voids the measurement.
 *
 * Measured 2026-08-26: control exit 0 / DRIFTED 0, break exit 1 / DRIFTED 2, both named. That is the
 * answer to "does it catch the class or the instance", and it was measured rather than claimed.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const cp = require('child_process');

/* THE ROOT IS OVERRIDABLE SO THIS FILE CAN BE SHOWN RED WITHOUT BREAKING THE REPOSITORY. `--break`
 * builds a two-file fixture in a scratch tree, points this variable at it and re-runs. Nothing in
 * the real tree is written, which matters because `data/abra-tags.js` is frozen into every engine
 * release and a rebuild under a live measurement voids it. */
const ROOT = process.env.ABRA_AUDIT_ROOT ? path.resolve(process.env.ABRA_AUDIT_ROOT) : path.join(__dirname, '..');
const D = (...p) => path.join(ROOT, ...p);
const ARGV = process.argv.slice(2);
const NO_REBUILD = ARGV.includes('--no-rebuild');
const LIST = ARGV.includes('--list');
const BREAK = ARGV.includes('--break');

/* WHAT IS DELIBERATELY OUT OF SCOPE, WITH THE REASON ON THE LINE.
 *
 * data/releases/** is a FROZEN COPY of files this audit already judges. A release is supposed to
 * disagree with the live tree — that is what freezing means — so judging the copies would produce
 * 411 rows of designed-in "drift" and drown the two rows that matter. CLAUDE.md: a stranded or
 * frozen artifact is a figure to WITHHOLD, never one to re-sync. */
const OUT_OF_SCOPE = [
  [/^data\/releases\//, 'a frozen release snapshot — designed to disagree with the live tree'],
  [/^node_modules\//, 'vendored'],
];
const outOfScope = rel => OUT_OF_SCOPE.find(([re]) => re.test(rel)) || null;

/* UNREADABLE IS NOT ABSENT. Every read here can fail, and a failure that returns "" would turn a
 * corrupt or locked file into "this file declares nothing" — a manufactured answer handed to the
 * report that exists to say whether a file can be believed. provenance.js carries this same note. */
const UNREADABLE = [];
function readOr(rel, what, bytes) {
  try {
    if (!bytes) return fs.readFileSync(D(rel), 'utf8');
    const fd = fs.openSync(D(rel), 'r');
    try {
      const b = Buffer.alloc(bytes);
      const n = fs.readSync(fd, b, 0, bytes, 0);
      return b.slice(0, n).toString('utf8');
    } finally { fs.closeSync(fd); }
  } catch (e) {
    if (!e || e.code !== 'ENOENT') UNREADABLE.push(`${rel} (${what}) — ${String(e.message).slice(0, 90)}`);
    return null;
  }
}

/* ── THE WALK ─────────────────────────────────────────────────────────────────────────────────────
 * `git ls-files`, not readdir. It is derived, it costs one process, and it excludes node_modules and
 * every agent's scratch tree without a pattern anybody has to maintain. The cost is stated in the
 * walk-past list above: an UNTRACKED generated file is invisible here. */
function tracked() {
  const out = cp.execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 28 });
  return out.split('\0').filter(Boolean);
}

/* ── DOOR 1: THE FILE DECLARES ITS OWN BUILDER ────────────────────────────────────────────────────
 *
 * `[\s\S]{0,200}?` and not `[^*]*?` — two headers in this repo put "GENERATED FILE" and "Generated
 * by <builder>" on separate comment lines, and a pattern that cannot cross a ` * ` prefix silently
 * skipped data/move-effects.js and data/mega-formes.js when check G was first written. */
const HDR = /GENERATED\b[\s\S]{0,240}?\bby\s+(?:ABRA[\/\\])?((?:build|engine|tests|tools|web|scripts)[\/\\][A-Za-z0-9_.-]+\.(?:js|cjs|mjs|py))(?:[\s\S]{0,240}?\bfrom\s+((?:data|CHOMP|docs|web|engine)[\/\\][A-Za-z0-9_.\/\\-]+\.(?:json|jsonl|js|py|md)))?/i;
const HDR_BYTES = 1400;

/* A BUILDER IS NOT ITS OWN OUTPUT, AND SAYING SO IS NOT A LIST.
 *
 * build/build_tags_js.js's header contains the sentence "GENERATED (S13): the content is
 * data/tags.json verbatim", which is a claim about the file it WRITES. Two derived facts separate a
 * script from an artifact and neither names anybody: a script reads `process.argv`, and a script is
 * never the builder it names. Both are properties of the bytes, so a new builder is handled with no
 * edit here. */
const looksLikeAScript = head => /process\.argv|require\(['"]child_process|^#!/m.test(head || '');

function door1(rel) {
  const head = readOr(rel, 'the GENERATED header', HDR_BYTES);
  if (head == null) return null;
  const m = head.match(HDR);
  if (!m) return null;
  const builder = m[1].replace(/\\/g, '/');
  if (builder === rel) return null;                 // a script describing its own output
  if (looksLikeAScript(head)) return null;
  return { builder, source: m[2] ? m[2].replace(/\\/g, '/') : null, via: 'header' };
}

/* A JSON ARTIFACT DECLARES ITSELF IN A FIELD RATHER THAN A COMMENT. Same key set provenance.js
 * reads, imported in spirit and kept in one order so the two agree about what a declaration is. */
const DECL_KEYS = ['by', 'generated_by', 'written_by', 'generator', 'source'];
const JSON_READ_CAP = 24 * 1024 * 1024;   /* above this the file is NOT JUDGED and is named as such */

function door1json(rel, size) {
  if (!/\.json$/i.test(rel)) return { j: null, skipped: null };
  if (size > JSON_READ_CAP) return { j: null, skipped: 'larger than ' + (JSON_READ_CAP >> 20) + 'MB' };
  const raw = readOr(rel, 'the declaration fields');
  if (raw == null) return { j: null, skipped: 'unreadable' };
  let j = null;
  try { j = JSON.parse(raw); } catch (e) { return { j: null, skipped: 'not JSON — ' + String(e.message).slice(0, 60) }; }
  if (!j || typeof j !== 'object' || Array.isArray(j)) return { j: null, skipped: null };
  return { j, skipped: null };
}

/* The declared writer, resolved to a script that EXISTS. A declaration pointing at nothing is a
 * claim that has quietly become false and is reported rather than believed. */
function declaredBuilder(j) {
  const p = j && typeof j.provenance === 'object' && j.provenance ? j.provenance : {};
  for (const v of DECL_KEYS.map(k => j[k]).concat(DECL_KEYS.map(k => p[k]))) {
    if (typeof v !== 'string' || !v.trim()) continue;
    for (const tok of v.split(/\s+/)) {
      const t = tok.replace(/^\.\//, '').replace(/\\/g, '/');
      if (!/^(?:[A-Za-z0-9_.-]+\/)?[A-Za-z0-9_.-]+\.(js|py)$/.test(t)) continue;
      const cands = t.includes('/') ? [t] : ['engine', 'build', 'tests', 'tools', 'scripts', 'web'].map(d => d + '/' + t);
      for (const c of cands) if (fs.existsSync(D(c))) return { builder: c, source: null, via: 'declared field' };
      return { builder: null, claim: v.slice(0, 70), via: 'declared field naming no script that exists' };
    }
  }
  return null;
}

/* ── DOOR 2: PROVENANCE'S DERIVED WRITER GRAPH ────────────────────────────────────────────────────
 * READ, not re-derived. engine/provenance.js scans engine/, build/ and tests/ for a write call that
 * names the file — through helpers, through one level of variable indirection, and through computed
 * path templates — and records the resulting membership in data/provenance-stamp.json. Re-deriving
 * that here would be a second implementation of the single fact "which script writes this file",
 * and the two would disagree eventually and invisibly. LESSONS.md §8. */
function door2() {
  const raw = readOr('data/provenance-stamp.json', 'the derived artifact graph');
  if (raw == null) return { files: [], stampAge: null, why: 'data/provenance-stamp.json is absent — run node engine/provenance.js' };
  let j = null;
  try { j = JSON.parse(raw); }
  catch (e) { return { files: [], stampAge: null, why: 'data/provenance-stamp.json is unreadable — ' + e.message }; }
  const files = (j.graph_files || []).map(f => 'data/' + f);
  let age = null;
  if (j.generated) age = (Date.now() - Date.parse(j.generated)) / 36e5;
  return { files, stampAge: age, generated: j.generated || null, why: null };
}

/* ── THE THREE QUESTIONS ──────────────────────────────────────────────────────────────────────────
 * Q1 does it declare its BUILDER?
 * Q2 does it declare the DIGEST OF THE SOURCE it was built from?  (a NAME is not a digest)
 * Q3 does it carry a digest of ITS OWN CONTENT?
 * Q2 and Q3 are what make a file provable WITHOUT re-running its builder, which is the only proof
 * available to an artifact that took forty minutes of rollouts to produce and cannot be rebuilt. */
const NOTE_KEY = (() => { try { return require('./run_stamp.js').STAMP_NOTE_KEY; } catch (e) {
  console.error('generated_audit: cannot import run_stamp STAMP_NOTE_KEY — ' + e.message); return 'note'; } })();

/* ABSENT AND UNREADABLE ARE DIFFERENT ANSWERS AND ONLY ONE OF THEM IS BENIGN. A source that has
 * been deleted since the artifact was written is a fact about the run; a source this process cannot
 * open is a fact about this process, and reporting the second as the first hands a manufactured
 * verdict to the report that exists to say whether a file can be believed. */
function sha12abs(abs) {
  try { return crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex').slice(0, 12); }
  catch (e) {
    if (e && e.code === 'ENOENT') return null;
    UNREADABLE.push(`${abs} (hashing a declared source) — ${String(e.message).slice(0, 80)}`);
    return 'UNREADABLE';
  }
}
function sourceDigestBlock(rel, j) {
  const direct = j && j.source_digests && typeof j.source_digests === 'object' ? j.source_digests : null;
  if (direct) return { block: direct, where: 'in the artifact' };
  /* THE SIDECAR IS THE OTHER HALF OF THE SAME CONVENTION. engine/run_stamp.js derives the sidecar's
   * path from the artifact's, so this must too rather than accepting one passed alongside. */
  const side = rel.replace(/\.[^.\/]+$/, '') + '.meta.json';
  const raw = fs.existsSync(D(side)) ? readOr(side, 'the run stamp sidecar') : null;
  if (raw == null) return null;
  try {
    const s = JSON.parse(raw);
    if (s && s.source_digests) return { block: s.source_digests, where: side };
  } catch (e) { UNREADABLE.push(`${side} (a run stamp sidecar) — ${String(e.message).slice(0, 60)}`); }
  return null;
}
const OWN_DIGEST_KEYS = ['content_digest', 'self_digest', 'artifact_digest', 'payload_sha256', 'digest_of_self'];
function ownDigest(j) {
  if (!j) return null;
  for (const k of OWN_DIGEST_KEYS) if (typeof j[k] === 'string' && j[k].trim()) return k;
  return null;
}

/* ── EOL: THE BYTES ON DISK VS THE BYTES IN THE REPO ──────────────────────────────────────────────
 * Exact and cheap, and it re-implements nothing: git itself is asked. If the FILTERED hash equals
 * the committed blob but the RAW hash does not, then the on-disk bytes differ from the committed
 * bytes only by the eol filter — a checkout artifact, not a content change. */
function eolState(rel) {
  /* `git rev-parse HEAD:<f>` FAILING BECAUSE THE FILE IS UNTRACKED IS AN ANSWER; git failing because
   * the index was locked by another agent is not, and this repository runs several agents at once.
   * The first is quiet, the second is recorded — otherwise a locked index silently downgrades a
   * CHECKOUT-EOL verdict to DRIFTED and somebody rebuilds a file that was never wrong. */
  const q = (a, quiet) => {
    try { return cp.execFileSync('git', a, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim(); }
    catch (e) {
      if (!quiet) UNREADABLE.push(`git ${a[0]} on ${rel} — ${String(e.message).split('\n')[0].slice(0, 80)}`);
      return null;
    }
  };
  const head = q(['rev-parse', 'HEAD:' + rel], true);   // untracked is expected and silent
  if (!head) return null;
  const filtered = q(['hash-object', '--', rel]);
  const raw = q(['hash-object', '--no-filters', '--', rel]);
  if (!filtered || !raw) return null;
  if (filtered !== head) return 'differs from HEAD';        // a real, committed-vs-worktree change
  if (raw !== head) return 'eol-only';                       // same content, different newlines on disk
  return 'identical';
}

/* ── THE PROOF ────────────────────────────────────────────────────────────────────────────────────
 * One ladder, strongest first. The verdicts are disjoint by construction so the counts add up. */
const checkCache = new Map();
const stripComments = s => s
  .replace(/\/\*[\s\S]*?\*\//g, m => m.replace(/[^\n]/g, ' '))
  .replace(/(^|[^:])\/\/[^\n]*/g, '$1')
  .replace(/(^|\n)([ \t]*)#[^\n]*/g, '$1$2');

/* A COMMENT IS NOT A MODE. Nine builders here contain the STRING `--check`; five of them read it
 * off argv and four only talk about it — including engine/quarantine.js, whose `--check` is a
 * QUARANTINE-LEAK gate that runs a 20,000-comparison differential and writes to data/. Spawning it
 * because a comment mentioned a flag would be this audit doing damage while measuring, which is the
 * failure CLAUDE.md spends a page on. So the source is stripped of comments first, and the flag must
 * reach an argv read. */
const READS_CHECK = /(process\.argv|sys\.argv|\bargv\b|\bhas\s*\()[^\n]{0,140}--check|--check[^\n]{0,140}(process\.argv|sys\.argv|\bargv\b)/;

/* ── A `--check` IS ONLY RE-RUN WHEN THE BUILDER IS A PURE TRANSFORM ──────────────────────────────
 *
 * `build/build_tags_js.js --check` reads two files and compares them: milliseconds, no writes. A
 * builder that PLAYS A GAME to produce its artifact cannot be re-run as a comparison — it costs
 * minutes, it pins every core, it writes, and CLAUDE.md forbids a measuring agent from running
 * beside a writing one. The distinction is DERIVED, not declared: the builder's own require graph
 * inside this repository is walked, and any builder that reaches the simulator is refused.
 *
 * The refusal is the SAFE direction and it is reported, never silently dropped: such a file lands in
 * UNPROVABLE with "reaches the play layer" on the line. engine/em_validation.js deliberately puts
 * its --check ahead of the heavy requires and is refused anyway; that costs a row of coverage and
 * cannot cost a live measurement. */
/* WHAT "THE PLAY LAYER" IS, DERIVED FROM THE ONE PLACE THAT DEFINES IT.
 *
 * `engine/engine_release.js` freezes the engine, and its `SOURCES` array IS the definition of what
 * the engine is — CLAUDE.md says in as many words to read the count from there and never from a
 * sentence, because the set has grown three times and the prose went stale three times. So the set
 * is parsed out of that array rather than named here. `engine_release.js` itself is added because a
 * caller that opens a release is reaching the simulator through the loader instead of through a
 * require, which is exactly how tests/test-engine-diff.js and tests/roster.js play games without
 * ever naming medicham2-browser.js.
 *
 * Only the .js entries matter: this is a REQUIRE walk, and `data/tags.json` is read with
 * readFileSync by the very builders this needs to be allowed to spawn. */
const PLAY_LAYER = (() => {
  const src = readOr('engine/engine_release.js', 'deriving what the play layer is');
  const set = new Set(['engine/engine_release.js']);
  const m = src && src.match(/const SOURCES\s*=\s*\[([\s\S]*?)\n\]/);
  if (!m) {
    console.error('generated_audit: could NOT parse SOURCES out of engine/engine_release.js. The play-layer');
    console.error('  guard is falling back to the simulator alone, so this run may spawn a builder that plays');
    console.error('  games. Fix the parse before trusting it.');
    set.add('engine/medicham2-browser.js');
    return set;
  }
  for (const q of m[1].matchAll(/'(engine\/[A-Za-z0-9_.-]+\.js)'/g)) set.add(q[1]);
  return set;
})();
const reachCache = new Map();
function reachesPlayLayer(rel, seen) {
  if (PLAY_LAYER.has(rel)) return rel;
  if (reachCache.has(rel)) return reachCache.get(rel);
  seen = seen || new Set();
  if (seen.has(rel)) return null;
  seen.add(rel);
  const src = readOr(rel, 'walking its require graph');
  if (src == null) { reachCache.set(rel, null); return null; }
  let hit = null;
  const code = stripComments(src);
  /* THREE SPELLINGS OF ONE REQUIRE, because this repository uses all three and a walk that knows
   * only the first is a walk that says tests/test-engine-diff.js does not touch the simulator:
   *   require('./medicham2-browser.js')            relative literal
   *   require(D('engine', 'medicham2-browser.js')) the dominant idiom here — no literal path at all
   *   REL.require('engine/medicham2-browser.js')   through a frozen release, which is still the engine
   * provenance.js records the same lesson about its own scans: the name is usually inside a helper. */
  const deps = [];
  for (const m of code.matchAll(/require\s*\(\s*['"](\.[^'"]+)['"]\s*\)/g))
    deps.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), m[1].replace(/\\/g, '/'))));
  for (const m of code.matchAll(/require\s*\(\s*[A-Za-z_$][\w$]*\s*\(\s*['"]([\w.-]+)['"]\s*,\s*['"]([\w.-]+)['"]\s*\)/g))
    deps.push(m[1] + '/' + m[2]);
  for (const m of code.matchAll(/\.require\s*\(\s*['"]((?:engine|data)\/[\w.-]+)['"]\s*\)/g))
    deps.push(m[1]);
  for (let dep of deps) {
    if (!/\.[a-z]+$/.test(dep)) dep += '.js';
    if (dep.startsWith('..')) continue;
    if (!fs.existsSync(D(dep))) continue;
    const r = reachesPlayLayer(dep, seen);
    if (r) { hit = dep === r ? dep : dep + ' -> ' + r; break; }
  }
  reachCache.set(rel, hit);
  return hit;
}

/* A REQUIRE WALK CANNOT SEE A SPAWN, AND THIS REPOSITORY SPAWNS.
 *
 *   engine/rollout_r4.js:64   spawnSync(process.execPath, [D('engine', script), ...args])
 *
 * `script` is a runtime string. No static analysis reaches the simulator through that, so a builder
 * that spawns anything is treated as COST UNKNOWN and never re-run. Refusing costs a row of
 * coverage; not refusing costs somebody else's forty-minute measurement. */
const SPAWNS = /child_process|spawnSync|spawn\s*\(|execFileSync|execSync/;
function builderCheckState(builder) {
  if (!builder) return { ok: false, why: 'no builder' };
  const src = readOr(builder, 'looking for a --check mode');
  if (src == null) return { ok: false, why: 'its builder could not be read' };
  const code = stripComments(src);
  if (!READS_CHECK.test(code)) return { ok: false, why: `${builder} offers no --check mode` };
  const play = reachesPlayLayer(builder);
  if (play) return { ok: false, why: `${builder} has a --check but reaches the play layer (${play}) — NOT re-run` };
  if (SPAWNS.test(code)) return { ok: false, why: `${builder} has a --check but spawns a child process, so its cost is unknown — NOT re-run` };
  return { ok: true, why: null };
}

/* THE SHORTLIST TEST, AND WHAT IT IS NOT. `cheapLooking` says only that no REQUIRE path from this
 * builder reaches the frozen engine and that it spawns nothing. It is a triage aid, not a proof:
 *   - a Python builder's imports are not walked at all, so it is excluded rather than cleared;
 *   - a builder that assembles a script name at runtime is invisible to any static walk. */
function cheapLooking(builder) {
  if (!builder || /\.py$/.test(builder)) return false;
  if (reachesPlayLayer(builder)) return false;
  const src = readOr(builder, 'judging whether a --check would be cheap');
  return src != null && !SPAWNS.test(stripComments(src));
}
function runBuilderCheck(builder, env) {
  const key = builder + '|' + (env ? env.__BREAK || '' : '');
  if (checkCache.has(key)) return checkCache.get(key);
  const r = cp.spawnSync(process.execPath, [D(builder), '--check'], {
    cwd: ROOT, encoding: 'utf8', timeout: 300000,
    env: Object.assign({}, process.env, env || {}),
  });
  const out = ((r.stdout || '') + (r.stderr || '')).trimEnd();
  const v = { status: r.status, out, error: r.error ? r.error.message : null };
  checkCache.set(key, v);
  return v;
}

const UNREAD_DIGEST_KEYS = new Map();

function main() {
  const files = tracked();
  const g2 = door2();
  const members = new Map();

  /* Door 1 over the whole tree. */
  const notJudged = [];
  for (const rel of files) {
    if (outOfScope(rel)) continue;
    /* A TRACKED FILE THIS RUN CANNOT STAT IS A HOLE IN THE AUDIT, NOT A FILE THAT PASSED. */
    let size = 0;
    try { size = fs.statSync(D(rel)).size; }
    catch (e) { if (!e || e.code !== 'ENOENT') UNREADABLE.push(`${rel} (stat, door 1) — ${String(e.message).slice(0, 70)}`); continue; }
    if (size === 0) continue;
    const h = door1(rel);
    let ev = h;
    const { j, skipped } = door1json(rel, size);
    if (skipped) notJudged.push(`${rel} — ${skipped}`);
    if (!ev && j) ev = declaredBuilder(j);
    if (ev) members.set(rel, Object.assign({ rel, j, size }, ev));
    else if (j && (j.source_digests || ownDigest(j))) members.set(rel, { rel, j, size, builder: null, source: null, via: 'carries digests but names no builder' });
  }
  /* Door 2 — provenance's derived writers. A file already in via door 1 keeps its richer row. */
  let door2Only = 0;
  for (const rel of g2.files) {
    if (outOfScope(rel)) continue;
    if (members.has(rel)) { members.get(rel).alsoDerived = true; continue; }
    if (!fs.existsSync(D(rel))) continue;
    /* Same rule as door 1: an unreadable member of provenance's graph is reported, never skipped. */
    let size = 0;
    try { size = fs.statSync(D(rel)).size; }
    catch (e) { if (!e || e.code !== 'ENOENT') UNREADABLE.push(`${rel} (stat, door 2) — ${String(e.message).slice(0, 70)}`); continue; }
    const { j } = door1json(rel, size);
    members.set(rel, { rel, j, size, builder: null, source: null, via: 'a script in engine/ build/ tests/ writes it (provenance)' });
    door2Only++;
  }

  /* ── judge ───────────────────────────────────────────────────────────────────────────────────── */
  const rows = [];
  for (const m of [...members.values()].sort((a, b) => a.rel.localeCompare(b.rel))) {
    const q1 = !!m.builder;
    const sd = sourceDigestBlock(m.rel, m.j);
    const q2 = !!sd;
    const q3 = ownDigest(m.j);
    let verdict = 'UNPROVABLE', detail = '', out = '';
    const cs = builderCheckState(m.builder);

    if (cs.ok && !NO_REBUILD) {
      const r = runBuilderCheck(m.builder, null);
      if (r.error) { verdict = 'UNPROVABLE'; detail = `${m.builder} --check could not run — ${r.error}`; }
      else if (r.status === 0) { verdict = 'PROVED'; detail = `${m.builder} --check agrees`; }
      else {
        const eol = eolState(m.rel);
        if (eol === 'eol-only') { verdict = 'CHECKOUT-EOL'; detail = `${m.builder} --check disagrees, and the on-disk bytes differ from the committed bytes ONLY by the eol filter`; }
        else { verdict = 'DRIFTED'; detail = `${m.builder} --check disagrees`; }
        out = r.out;
      }
    } else if (q2) {
      /* A `source_digests` BLOCK IS NOT ALL DIGESTS. run_stamp.js reserves one key for prose, and
       * several hand-rolled blocks carry `taken`, `algorithm` and other notes beside the paths. A
       * key that does not name a file in this tree is not a digest that failed — treating it as one
       * manufactures a mismatch, which is the exact failure mode this whole file is about.
       * AND THE DIGESTS ARE NOT ALL THE SAME LENGTH: run_stamp writes 12 hex characters and at
       * least one artifact recorded the full 64, so they are compared on the shorter prefix. */
      const bad = [];
      let compared = 0;
      for (const [src, want] of Object.entries(sd.block)) {
        if (src === NOTE_KEY) continue;
        if (typeof want !== 'string' || !/^[0-9a-f]{8,64}$/.test(want)) continue;   // prose, not a digest
        if (!/[\/\\]/.test(src) && !/\.[A-Za-z0-9]+$/.test(src)) continue;          // not a path
        const got = sha12abs(D(src));
        compared++;
        if (got === 'UNREADABLE') { bad.push(`${src} (could not be read — see UNREADABLE)`); continue; }
        if (got == null) { bad.push(`${src} (absent now)`); continue; }
        const n = Math.min(got.length, want.length);
        if (got.slice(0, n) !== want.slice(0, n)) bad.push(`${src} ${want.slice(0, 12)} -> ${got}`);
      }
      if (!compared) { verdict = 'UNPROVABLE'; detail = `carries a source_digests block ${sd.where} with no comparable digest in it`; }
      else if (!bad.length) { verdict = 'DIGESTED'; detail = `all ${compared} source digest(s) recorded ${sd.where} still match`; }
      else {
        /* NOT A FAILURE OF THIS CHECK, AND SAYING SO IS THE POINT. An artifact whose sources have
         * moved since it was written is STALE, which is a fact about the measurement and the
         * standing verdict of engine/provenance.js. It is not a derived file disagreeing with a
         * source that is sitting right beside it, which is the class this file exists to catch.
         * Failing on it here would duplicate provenance's gate and turn this one red at ~60 rows on
         * the day it landed — and a gate that fires at sixty is a gate people learn to waive. */
        verdict = 'SOURCE-MOVED'; detail = `${bad.length} of ${compared} source digest(s) recorded ${sd.where} have moved since: ${bad.slice(0, 3).join('; ')}`;
      }
    } else if (q1) {
      verdict = 'UNPROVABLE'; detail = NO_REBUILD ? `${m.builder} — not re-run (--no-rebuild)` : cs.why;
    } else {
      verdict = 'UNPROVABLE'; detail = 'no builder can be named and no source digest is recorded';
    }
    rows.push({ rel: m.rel, verdict, detail, out, q1, q2, q3: !!q3, builder: m.builder || null, source: m.source || null, via: m.via });

    /* DIGEST-SHAPED FIELDS THIS RUN DOES NOT READ, counted rather than assumed away.
     *
     * Q2 reads exactly `source_digests` and the run_stamp sidecar. Several artifacts carry other
     * digest-shaped keys — `source_digests_before`, `harness_digests`, `census_digest` — and folding
     * them in would be wrong in both directions: `_before` is DELIBERATELY the old state and
     * comparing it to today manufactures a mismatch, while `harness_digests` describes a fixture and
     * not a source. So they are NAMED and left unread, because an unread field that nobody mentions
     * is indistinguishable from a field that does not exist. */
    if (m.j) for (const k of Object.keys(m.j)) {
      if (k === 'source_digests') continue;
      if (!/digest|sha256|checksum/i.test(k)) continue;
      UNREAD_DIGEST_KEYS.set(k, (UNREAD_DIGEST_KEYS.get(k) || 0) + 1);
    }
  }

  /* ── report ──────────────────────────────────────────────────────────────────────────────────── */
  if (LIST) {
    for (const r of rows) console.log([r.verdict, r.rel, r.builder || '-', r.q1 ? 'B' : '-', r.q2 ? 'S' : '-', r.q3 ? 'O' : '-'].join('\t'));
  }
  const by = v => rows.filter(r => r.verdict === v);
  console.log('GENERATED-FILE AUDIT — can each generated file prove it matches its source?\n');
  console.log(`  ${rows.length} generated file(s) found, over ${files.length} tracked files.`);
  console.log(`    door 1  self-declared (header or field) : ${rows.filter(r => r.via === 'header' || r.via === 'declared field').length}`);
  console.log(`    door 2  writer derived by provenance    : ${door2Only} more that declare nothing`);
  if (g2.why) console.log(`    DOOR 2 IS SHUT: ${g2.why} — this run covers LESS than it looks like it does.`);
  else console.log(`    provenance stamp read: ${g2.generated} (${g2.stampAge == null ? '?' : g2.stampAge.toFixed(1)}h old, ${g2.files.length} artifacts)`);
  console.log('');
  console.log('  THE THREE QUESTIONS');
  console.log(`    declares its BUILDER                    : ${rows.filter(r => r.q1).length} of ${rows.length}`);
  console.log(`    declares the DIGEST OF ITS SOURCE       : ${rows.filter(r => r.q2).length} of ${rows.length}`);
  console.log(`    carries a digest of ITS OWN CONTENT     : ${rows.filter(r => r.q3).length} of ${rows.length}`);
  console.log('');
  const CAP = { PROVED: 99, DIGESTED: 99, 'CHECKOUT-EOL': 99, DRIFTED: 99, 'SOURCE-MOVED': 6 };
  const WHY = {
    PROVED: 'the builder was re-run in --check mode and agrees',
    DIGESTED: 'not rebuildable, but every source it recorded still hashes the same',
    'CHECKOUT-EOL': 'byte-different from what the builder writes, and the difference is ENTIRELY line endings',
    'SOURCE-MOVED': 'STALE, not drifted — its sources moved after it was written. This is engine/provenance.js\'s verdict and its gate, not this one\'s',
    DRIFTED: 'the builder was re-run in --check mode and DISAGREES — the two files in this tree do not match',
  };
  for (const v of ['DRIFTED', 'CHECKOUT-EOL', 'PROVED', 'DIGESTED', 'SOURCE-MOVED']) {
    const set = by(v);
    if (!set.length) continue;
    console.log(`  ${v} — ${set.length}   (${WHY[v]})`);
    for (const r of set.slice(0, CAP[v])) {
      console.log(`     ${r.rel}${r.source ? '  <- ' + r.source : ''}`);
      console.log(`        ${r.detail}`);
      if (r.out) for (const l of r.out.split('\n').slice(0, 6)) console.log('        | ' + l);
    }
    if (set.length > CAP[v]) console.log(`     … and ${set.length - CAP[v]} more (--list for all)`);
    console.log('');
  }
  const un = by('UNPROVABLE');
  console.log(`  UNPROVABLE — ${un.length}. Drift in these is NOT DETECTABLE by anything in this repository.`);
  const noBuilder = un.filter(r => !r.builder);
  const play = un.filter(r => r.builder && /play layer/.test(r.detail));
  const noCheck = un.filter(r => r.builder && !/play layer/.test(r.detail));
  console.log(`     ${noCheck.length} name a builder that offers no --check mode — ONE EDIT EACH from covered,`);
  console.log(`         and this file picks each up with no change here the moment the mode exists.`);
  console.log(`     ${play.length} name a builder that has a --check and REACHES THE PLAY LAYER, so it is not re-run:`);
  console.log(`         re-running it would play games, cost minutes and write. Their only possible proof is a`);
  console.log(`         source_digests block, which is engine/run_stamp.js's job.`);
  console.log(`     ${noBuilder.length} name no builder at all — nothing in this repository can rebuild them to compare.`);
  const byBuilder = new Map();
  for (const r of noCheck) byBuilder.set(r.builder, (byBuilder.get(r.builder) || 0) + 1);
  console.log(`\n     the builders that would buy the most coverage, largest first:`);
  for (const [b, n] of [...byBuilder.entries()].sort((a, b2) => b2[1] - a[1]).slice(0, 10)) {
    console.log(`       ${String(n).padStart(4)} file(s)  ${b}`);
  }

  /* ── THE RECURRENCE SET ────────────────────────────────────────────────────────────────────────
   * Not every unprovable file is the same risk. A training checkpoint is a RUN's output: there is
   * nothing in this tree to compare it to, and its only possible proof is the source digests it
   * recorded when it ran. `data/abra-tags.js` is a different animal — a PURE COPY of another file
   * that is sitting right there, which means the two can silently disagree inside one commit, and
   * that is the shape that has now recurred four times.
   *
   * The cut is DERIVED, not judged, and it is a SHORTLIST rather than a verdict — see cheapLooking()
   * for the two things it cannot see. Every member is one `--check` away from PROVED, and this file
   * picks it up with no edit here. */
  const recurrence = noCheck.filter(r => cheapLooking(r.builder));
  console.log(`\n  SHORTLIST — ${recurrence.length} of the ${noCheck.length}. No require path from the builder reaches the frozen`);
  console.log('  engine and it spawns nothing, so a --check would probably cost milliseconds. A Python builder');
  console.log('  is EXCLUDED rather than cleared (imports are not walked) and so is a runtime-computed spawn.');
  for (const r of recurrence) console.log(`     ${r.rel.padEnd(34)} <- ${r.builder}${r.source ? '  from ' + r.source : ''}`);
  if (UNREAD_DIGEST_KEYS.size) {
    console.log(`\n  DIGEST-SHAPED FIELDS THIS RUN DOES NOT READ — ${UNREAD_DIGEST_KEYS.size} distinct key(s).`);
    console.log('  Named, not folded in: see the note at the collection site for why each is unsafe to compare.');
    console.log('     ' + [...UNREAD_DIGEST_KEYS.entries()].sort((a, b) => b[1] - a[1])
      .map(([k, n]) => `${k} x${n}`).join(', '));
  }
  if (notJudged.length) {
    console.log(`\n  NOT JUDGED — ${notJudged.length} file(s) this run could not read as a declaration:`);
    for (const s of notJudged.slice(0, 12)) console.log('       ' + s);
  }
  if (UNREADABLE.length) {
    console.log(`\n  UNREADABLE — ${UNREADABLE.length}. An unreadable file is a HOLE in this audit, not a pass:`);
    for (const s of UNREADABLE.slice(0, 12)) console.log('       ' + s);
  }

  const drifted = by('DRIFTED').length, eol = by('CHECKOUT-EOL').length;
  console.log('');
  if (drifted) {
    console.log(`  RED — ${drifted} generated file(s) DRIFTED from a source sitting beside them in this tree.`);
    console.log('  Rebuild each one with the builder named above, then re-run this.');
  } else if (eol) {
    console.log(`  RED — ${eol} file(s) are byte-different from what their builder writes, and the difference is`);
    console.log('  ENTIRELY line endings. The content agrees. This is a CHECKOUT defect, not drift: on a');
    console.log('  core.autocrlf=true clone, git rewrites a generated file the moment it checks it out, and');
    console.log('  every byte-comparing --check in this repo then reads RED for a cause that is not drift.');
  } else {
    console.log('  GREEN on the files that can be proved. Read the UNPROVABLE count above before believing it:');
    console.log('  a generated file nothing can compare is not a file that agrees with its source.');
  }
  process.exit(drifted || eol ? 1 : 0);
}

/* ── THE DELIBERATE BREAK ─────────────────────────────────────────────────────────────────────────
 *
 * A check that has never been shown red is a check nobody has tested, and this repository has
 * shipped more than one that could not fail — `tests/test-mc-key.js` matched a list of known-bad
 * spellings and the third instance of the bug used a spelling that was not on it.
 *
 * So: build the smallest real fixture — one builder, one source, one generated copy — in a scratch
 * tree with its own git index, run this file against it TWICE, and require opposite answers. The
 * control leg matters as much as the break: a fixture that is red both ways proves nothing, and
 * "the knob was cleared and the counter moved" is the standard this project already holds every
 * other instrument to.
 *
 * NOTHING IN THE REAL TREE IS WRITTEN. The pair is COPIED out, and the copy is what gets damaged.
 *
 * AND IT DAMAGES TWO PAIRS BUILT BY TWO DIFFERENT SCRIPTS, because "does it catch the CLASS or just
 * this instance" is the whole question and it deserves an answer that was MEASURED. If only the tags
 * pair went red, this would be `tests/test-mc-key.js` again — a check that matches one known case.
 */
const FIXTURES = [
  { art: 'data/abra-tags.js', builder: 'build/build_tags_js.js', src: 'data/tags.json' },
  { art: 'data/guru.js', builder: 'build/build_guru_js.js', src: 'data/guru-matchups.json' },
];
function selfTest() {
  const os = require('os');
  const SRC_ROOT = path.join(__dirname, '..');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'abra-generated-audit-'));
  fs.mkdirSync(path.join(dir, 'build')); fs.mkdirSync(path.join(dir, 'data'));
  for (const f of FIXTURES) for (const rel of [f.builder, f.src, f.art]) {
    /* Newlines are normalised on the way in ON PURPOSE. The fixture is testing DRIFT, and on a
     * core.autocrlf=true clone the live copy may already be CRLF — which is a different verdict
     * (CHECKOUT-EOL) and would confound the demonstration with the very thing it is not about. */
    const raw = fs.readFileSync(path.join(SRC_ROOT, rel), 'utf8').replace(/\r\n/g, '\n');
    fs.writeFileSync(path.join(dir, rel), raw);
  }
  const run = (label) => {
    cp.execFileSync('git', ['add', '-A'], { cwd: dir, stdio: 'ignore' });
    const r = cp.spawnSync(process.execPath, [__filename], {
      cwd: dir, encoding: 'utf8', env: Object.assign({}, process.env, { ABRA_AUDIT_ROOT: dir }),
    });
    const txt = (r.stdout || '') + (r.stderr || '');
    const verdict = /DRIFTED — (\d+)/.exec(txt);
    /* The DRIFTED block, read as lines rather than with a fixed-width regex window — a window wide
     * enough for two rows is a window that will silently miss the third. */
    const lines = txt.split('\n');
    const start = lines.findIndex(l => /^\s{2}DRIFTED — /.test(l));
    const block = start < 0 ? [] : lines.slice(start + 1, start + 1 + lines.slice(start + 1).findIndex(l => !l.trim()));
    const named = FIXTURES.filter(f => block.some(l => l.trim().startsWith(f.art))).map(f => f.art);
    console.log(`  ${label}: exit ${r.status}, DRIFTED=${verdict ? verdict[1] : 0}${named.length ? '  ' + named.join(', ') : ''}`);
    return { status: r.status, drifted: verdict ? Number(verdict[1]) : 0, named };
  };
  /* THE DAMAGE IS THE REAL DRIFT, NOT A WHITESPACE NUDGE. The four live instances of this bug all had
   * the same shape: the browser copy carried an OLDER VALUE for a parameter the node engine had
   * already moved — Bug Bite and Pluck stealing any item instead of only a berry. So the fixture
   * edits a value inside the payload, and falls back to a byte nudge only if the shape has changed
   * since this was written. The fallback is ANNOUNCED rather than silent: a self-test that quietly
   * weakens its own damage is the same failure as a check that quietly covers less than it claims. */
  const damage = (p) => {
    const before = fs.readFileSync(p, 'utf8');
    let after = before.replace(/("(?:tag|name|id)"\s*:\s*")([A-Za-z])/, (m, a, b) => a + (b === 'z' ? 'y' : 'z'));
    if (after === before) {
      console.log(`  (no tag/name/id field in ${path.basename(p)} — falling back to a one-byte nudge)`);
      const i = Math.floor(before.length / 2);
      after = before.slice(0, i) + ' ' + before.slice(i);
    }
    if (after === before) throw new Error('the fixture could not be damaged at all — do not trust this self-test');
    fs.writeFileSync(p, after);
  };
  try {
    cp.execFileSync('git', ['init', '-q'], { cwd: dir, stdio: 'ignore' });
    console.log('SELF-TEST — ' + FIXTURES.length + ' pairs, ' + FIXTURES.length + ' DIFFERENT builders, in ' + dir + '\n');
    for (const f of FIXTURES) console.log(`    ${f.art}  <- ${f.builder}  from ${f.src}`);
    console.log('\n  CONTROL: every copy is exactly what its builder would write.');
    const control = run('control');
    for (const f of FIXTURES) damage(path.join(dir, f.art));
    console.log(`\n  BREAK: one value changed inside the payload of EACH of the ${FIXTURES.length} copies.`);
    const broken = run('broken');
    console.log('');
    const pass = control.status === 0 && control.drifted === 0
              && broken.status !== 0 && broken.drifted === FIXTURES.length
              && broken.named.length === FIXTURES.length;
    console.log(pass
      ? `  SELF-TEST PASSED — green on the untouched pairs, RED on all ${FIXTURES.length}, each named.\n` +
        '  A second generated file, built by a DIFFERENT script, is caught. That is the class, measured.'
      : '  SELF-TEST FAILED — this check did not move on every broken pair. Do not trust a green run.');
    process.exit(pass ? 0 : 1);
  } finally {
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch (e) { console.error('  (scratch fixture left behind at ' + dir + ' — ' + e.message + ')'); }
  }
}

if (BREAK) selfTest(); else main();
