/* policy.js — the behaviour-clone. Mines what each species ACTUALLY clicks from
 * the stored per-turn stream (real ladder players), split by turn 1 vs later.
 * This is the move policy MEDICHAM samples from, so its rollouts click Tailwind,
 * Fake Out, Spore, Swords Dance, Protect — because strong players do — instead of
 * only ever picking max damage. Pure re-computation over stored data.
 *
 *   node engine/policy.js                      ->  data/move-priors.observed.json   (derive)
 *   node engine/policy.js --promote            ->  observed BECOMES data/move-priors.json
 *   node engine/policy.js --promote --dry-run  ->  print the delta, write nothing
 *   node engine/policy.js --promote --from A --to B     (explicit paths; used by the test)
 *
 * THE DERIVATION NO LONGER WRITES THE ENGINE. WHY THERE IS A PROMOTE STEP AT ALL.
 * (2026-08-22. Full account: docs/_reports/2026-08-22-ingest-invalidates-releases.md.)
 *
 * `data/move-priors.json` is one of the 26 files `engine/engine_release.js` freezes as an engine
 * SOURCE, and freezing it is CORRECT: `engine/set_priors.js` `movePriors()` -> `sampleMoves()` is
 * called from `engine/champions_sim.js:203` inside `packTeam()` and decides which moves an
 * unrevealed set is filled with — on the team the SHOWDOWN REFERENCE ENGINE plays. A different pool
 * is a different team is a different battle. `engine/board.js` reads it twice more
 * (`movePriorOdds`, `protectOdds`), and `engine/rollout_leaf.js` clicks out of it under
 * `foePolicy:'prior'`.
 *
 * The defect was never that it is frozen. It was that `.github/workflows/ingest.yml` — on a
 * six-hourly cron, read from that file — REWROTE it unattended, so a scheduled job was entitled to redefine the
 * engine every six hours — and the release pointer follows any byte of any source, so every artifact
 * measured before the ingest was withheld by `MEASURED AGAINST A DIFFERENT ENGINE`. The gate was
 * right every time it fired: both transitions on 2026-08-22 moved 259 of 345 species, 36
 * pool-membership entries and 4 modal moves. **It bit twice in four hours**, once withholding a
 * correct roster re-measurement and once walking a different sample under a same-seed differential
 * re-run (`skipped_multihit` 170 against 154).
 *
 * So the scheduler keeps COLLECTING and stops DECIDING. It writes the fresh derivation to
 * `data/move-priors.observed.json`; the engine's copy moves only when a person promotes it, and the
 * promotion PRINTS WHAT IT DOES TO THE ENGINE. That is the pattern `data/residual-order.json` and
 * `data/switchin-order.json` — the other two derived tables inside SOURCES — already use: derived,
 * regenerated by an explicit `--write`, never by a cron. `SOURCES` is untouched, no release changes
 * meaning, and no existing snapshot loses a file.
 *
 * THE COST, SAID OUT LOUD: the engine's behaviour priors are now as old as the last promotion. That
 * is the correct trade — a table stale by a recorded decision is a fact; a table that moves under a
 * running measurement is not — but it means promotion has to actually HAPPEN. `engine/provenance.js`
 * derives its graph from this source, so once new games land it will report `data/move-priors.json`
 * as older than its input, which is the debt printed rather than remembered.
 */
const fs=require('fs'), path=require('path');
const { classify } = require('./moves-meta.js');
const D=(...p)=>path.join(__dirname,'..',...p);
const key=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');

/* THE TWO PATHS, bound as literals so engine/provenance.js can still attribute BOTH artifacts to
 * this file. It ranks a generator by whether the artifact's name is bound to an identifier that is
 * later written; a computed path would take move-priors.json back to "no generator", which is the
 * condition that exempts an artifact from every corpus check in that file. */
const CANONICAL = path.join(__dirname, '../data/move-priors.json');
const OBSERVED  = path.join(__dirname, '../data/move-priors.observed.json');

const ARGV = process.argv.slice(2);
const flag = n => ARGV.includes('--' + n);
const opt  = (n, d) => { const i = ARGV.indexOf('--' + n);
                         return (i >= 0 && ARGV[i+1] && !/^--/.test(ARGV[i+1])) ? ARGV[i+1] : d; };
/* Positional args, with the VALUE of --from/--to excluded so `--promote --from x` cannot be read as
 * a store path. The two positionals stay exactly what they were: [store] [out]. */
const POS = ARGV.filter((a,i) => !/^--/.test(a) && !(i>0 && /^--(from|to)$/.test(ARGV[i-1])));

/* ------------------------------------------------------------------------------------------------
 * THE PROMOTE STEP. Runs before the derivation and exits, so a promotion never re-reads the store —
 * it lands the bytes that were ALREADY measured, which is the whole point of separating them.
 * ---------------------------------------------------------------------------------------------- */

/* WHICH MOVES BLOCK. Read from data/tags.json's `stalling` tag, which engine/tag_dex.js derives from
 * `m.stallingMove` — the same field engine/board.js's STALL set is built from (board.js:1871). One
 * fact, one derivation: a typed list of Protect-family moves here would be a second copy of a
 * Pokemon fact, which this repository has learned is how two files come to disagree invisibly.
 * Returns null rather than a guess when the tag artifact cannot be read, and the caller says so. */
function stallingMoves() {
  try {
    const t = JSON.parse(fs.readFileSync(D('data','tags.json'),'utf8'));
    const s = new Set();
    for (const [id,m] of Object.entries(t.moves||{})) if ((m.tags||[]).includes('stalling')) s.add(key(id));
    return s.size ? s : null;
  } catch(e) { return null; }
}

function profile(j, stall) {
  const out = {};
  for (const [sp,v] of Object.entries((j&&j.species)||{})) {
    const p = {};
    let prot = 0;
    for (const mv of (v.moves||[])) {
      if (!mv || !mv.mv) continue;
      p[key(mv.mv)] = +mv.p || 0;
      if (stall && stall.has(key(mv.mv))) prot += +mv.p || 0;
    }
    out[key(sp)] = { p, prot: +prot.toFixed(3), acts: +v.acts||0,
                     top: (v.moves&&v.moves[0]&&key(v.moves[0].mv))||null,
                     lead:(v.lead &&v.lead[0] &&key(v.lead[0].mv))||null };
  }
  return out;
}

/* WHAT WOULD CHANGE IF THIS LANDED, in the units the readers actually consume:
 *   the candidate POOL      set_priors.fillSet draws from it
 *   the MODAL move          sampleMoves' most likely draw, and rollout_leaf's pickByPrior
 *   protectOdds             multiplies MAG's kill probability in board.js
 *   the cell probabilities  movePriorOdds
 * A promote that printed "updated" and nothing else would be no better than the cron it replaces. */
function delta(oldJ, newJ) {
  const stall = stallingMoves();
  const A = profile(oldJ, stall), B = profile(newJ, stall);
  const all = new Set([...Object.keys(A), ...Object.keys(B)]);
  const r = { stallKnown: !!stall, added:[], removed:[], common:0, changed:0,
              cells:0, cellsChanged:0, pool:[], topFlip:[], leadFlip:[], prot:[],
              sumAbs:0, maxAbs:0, maxAbsWhat:null,
              actsOld:0, actsNew:0, spOld:Object.keys(A).length, spNew:Object.keys(B).length };
  for (const s of all) {
    const a = A[s], b = B[s];
    if (a) r.actsOld += a.acts;
    if (b) r.actsNew += b.acts;
    if (!a) { r.added.push(s); continue; }
    if (!b) { r.removed.push(s); continue; }
    r.common++;
    let moved = false;
    const mvs = new Set([...Object.keys(a.p), ...Object.keys(b.p)]);
    const gone = [], came = [];
    for (const m of mvs) {
      const inA = m in a.p, inB = m in b.p;
      r.cells++;
      /* A POOL CHANGE IS A FULL-SIZE DELTA, NOT A MISSING ONE. `movePriorOdds` returns 0 for a move
       * that is not in the row, so an entry appearing at p=0.12 moved that cell by 0.12. Counting it
       * as an unmeasured "membership" event and leaving it out of the magnitude would understate the
       * mean by exactly the changes that matter most — the ones that change what fillSet can draw. */
      if (inA !== inB) {
        (inA ? gone : came).push(m);
        const d = inA ? a.p[m] : b.p[m];
        moved = true; r.cellsChanged++; r.sumAbs += d;
        if (d > r.maxAbs) { r.maxAbs = d; r.maxAbsWhat = `${s} ${m} ${inA ? a.p[m]+' -> absent' : 'absent -> '+b.p[m]}`; }
        continue;
      }
      const d = Math.abs(a.p[m] - b.p[m]);
      if (d > 1e-9) {
        moved = true; r.cellsChanged++; r.sumAbs += d;
        if (d > r.maxAbs) { r.maxAbs = d; r.maxAbsWhat = `${s} ${m} ${a.p[m]} -> ${b.p[m]}`; }
      }
    }
    if (gone.length || came.length)
      r.pool.push({ sp:s, s: gone.map(m=>'-'+m).concat(came.map(m=>'+'+m)).join(' '),
                    n: gone.length + came.length });
    if (a.top !== b.top)   { r.topFlip.push(`${s}  ${a.top} -> ${b.top}`); moved = true; }
    if (a.lead !== b.lead) { r.leadFlip.push(`${s}  ${a.lead} -> ${b.lead}`); moved = true; }
    if (Math.abs(a.prot - b.prot) > 1e-9)
      r.prot.push({ sp:s, d:Math.abs(a.prot-b.prot), s:`${s} ${a.prot} -> ${b.prot}` });
    if (moved) r.changed++;
  }
  r.poolCells = r.pool.reduce((t,x)=>t+x.n,0);
  r.pool.sort((x,y)=>y.n-x.n || (x.sp<y.sp?-1:1));
  r.prot.sort((x,y)=>y.d-x.d);
  return r;
}

function printDelta(r, from, to) {
  const n = (x)=>String(x).padStart(6);
  console.log(`\nWHAT LANDS ON THE ENGINE   ${path.basename(from)} -> ${path.basename(to)}`);
  console.log(`  species                    ${n(r.spNew)} observed / ${r.spOld} in the engine now`);
  if (r.added.length)   console.log(`  species ADDED              ${n(r.added.length)}   ${r.added.slice(0,12).join(' ')}${r.added.length>12?' …':''}`);
  if (r.removed.length) console.log(`  species REMOVED            ${n(r.removed.length)}   ${r.removed.slice(0,12).join(' ')}${r.removed.length>12?' …':''}`);
  console.log(`  species changed            ${n(r.changed)} of ${r.common} in both`);
  console.log(`  move cells changed         ${n(r.cellsChanged)} of ${r.cells}`);
  console.log(`  POOL membership changed    ${n(r.poolCells)} cells over ${r.pool.length} species   <- set_priors.fillSet draws from this`);
  console.log(`  MODAL move flipped         ${n(r.topFlip.length)}                    <- sampleMoves / pickByPrior`);
  console.log(`  lead modal flipped         ${n(r.leadFlip.length)}`);
  if (r.stallKnown) {
    const top = r.prot[0] ? `   max ${r.prot[0].s}` : '';
    console.log(`  protectOdds moved          ${n(r.prot.length)} species${top}   <- board.js kill probability`);
  } else {
    console.log(`  protectOdds moved             n/a   data/tags.json unreadable, so the stalling family could not be DERIVED; not guessed`);
  }
  const mean = r.cellsChanged ? (r.sumAbs / r.cellsChanged) : 0;
  console.log(`  mean |delta| over changed  ${mean.toFixed(5)}   max ${r.maxAbs.toFixed(3)}${r.maxAbsWhat?'  ('+r.maxAbsWhat+')':''}`);
  console.log(`  clicks behind it           ${r.actsNew} observed / ${r.actsOld} in the engine now`);

  const CAP = 60;
  if (r.pool.length) {
    console.log(`\nPOOL MEMBERSHIP (${r.pool.length} species) — a move here can now be drawn, or can no longer be:`);
    for (const x of r.pool.slice(0,CAP)) console.log('  ' + x.sp.padEnd(22) + x.s);
    if (r.pool.length > CAP) console.log(`  … and ${r.pool.length-CAP} more`);
  }
  if (r.topFlip.length) {
    console.log(`\nMODAL MOVE FLIPS (${r.topFlip.length}) — the most likely click changes species:`);
    for (const s of r.topFlip.slice(0,CAP)) console.log('  ' + s);
    if (r.topFlip.length > CAP) console.log(`  … and ${r.topFlip.length-CAP} more`);
  }
  if (r.leadFlip.length) {
    console.log(`\nLEAD MODAL FLIPS (${r.leadFlip.length}) — the turn-1 distribution:`);
    for (const s of r.leadFlip.slice(0,CAP)) console.log('  ' + s);
    if (r.leadFlip.length > CAP) console.log(`  … and ${r.leadFlip.length-CAP} more`);
  }
  if (r.stallKnown && r.prot.length) {
    console.log(`\nprotectOdds — the ten biggest movers of ${r.prot.length}:`);
    for (const x of r.prot.slice(0,10)) console.log('  ' + x.s);
  }
}

/* THE REFUSALS. A promote that cannot fail is not a gate — it is the cron with a longer command
 * line. Every one of these is a way the observed file can be WELL-FORMED and still destroy the
 * engine's table, which is the failure mode this repository keeps meeting: nothing throws, nothing
 * reports, and the number is fiction afterwards.
 *
 * The shrink bound is the same instrument the ingest workflow already points at the stores ("A store
 * that shrank is a bug, never an update"). The behaviour clone is not strictly monotonic — a species
 * can fall under the 15-act floor — so it is a BAND rather than equality, and it is overridable by
 * --force with the override printed. 0.80 is a judgement: the largest observed day-over-day species
 * move on this artifact is 0 (345 -> 345 across both 2026-08-22 ingests), so 20% is ~infinitely
 * looser than anything real and still catches a half-written or half-filtered store. */
const SHRINK_FLOOR = 0.80;

function refuse(msg, code) {
  console.error('REFUSED: ' + msg);
  process.exit(code);
}

function promote() {
  const from = opt('from', OBSERVED), to = opt('to', CANONICAL);
  const dry = flag('dry-run'), force = flag('force');

  if (!fs.existsSync(from))
    refuse(`${path.relative(D('.'),from) || from} does not exist. Nothing has been derived to promote — `
         + `run the derivation first (node engine/policy.js), or let the ingest workflow do it.`, 2);

  const raw = fs.readFileSync(from, 'utf8');
  let obs = null;
  try { obs = JSON.parse(raw); } catch(e) { refuse(`${from} is not valid JSON: ${e.message}`, 2); }
  if (!obs || typeof obs !== 'object' || !obs.species || typeof obs.species !== 'object')
    refuse(`${from} has no \`species\` object. That is not a behaviour clone.`, 2);

  const spN = Object.keys(obs.species).length;
  let cellsN = 0;
  for (const v of Object.values(obs.species)) cellsN += ((v && v.moves) || []).length;
  if (!spN)    refuse(`${from} holds 0 species — promoting it would BLANK the engine's move priors. `
                    + `Every unrevealed set would be filled from nothing.`, 2);
  if (!cellsN) refuse(`${from} holds ${spN} species and 0 move cells — promoting it would blank the `
                    + `candidate pool set_priors.fillSet draws from.`, 2);

  const haveCanon = fs.existsSync(to);
  let cur = { species:{} };
  if (haveCanon) {
    try { cur = JSON.parse(fs.readFileSync(to,'utf8')); }
    catch(e) { console.error(`  note: ${to} is unparsable (${e.message}); promoting over it, delta unavailable`); }
  } else {
    console.log(`  note: ${to} does not exist — this is a first install, so no shrink comparison is possible.`);
  }

  const spO = Object.keys(cur.species||{}).length;
  let cellsO = 0;
  for (const v of Object.values(cur.species||{})) cellsO += ((v && v.moves) || []).length;

  if (spO && spN < spO * SHRINK_FLOOR) {
    const m = `${from} profiles ${spN} species against the engine's ${spO} — a ${(100*(1-spN/spO)).toFixed(1)}% `
            + `drop, past the ${Math.round(100*(1-SHRINK_FLOOR))}% bound. A behaviour clone does not lose a `
            + `fifth of the ladder in one derivation; a truncated store or a broken clean filter does. `
            + `Check the store, then --force if this is genuinely what the ladder looks like.`;
    if (!force) refuse(m, 3);
    console.error('  FORCED PAST A REFUSAL: ' + m);
  }
  if (cellsO && cellsN < cellsO * SHRINK_FLOOR) {
    const m = `${from} holds ${cellsN} move cells against the engine's ${cellsO} — past the `
            + `${Math.round(100*(1-SHRINK_FLOOR))}% bound. The candidate pool would shrink that far.`;
    if (!force) refuse(m, 3);
    console.error('  FORCED PAST A REFUSAL: ' + m);
  }

  if (haveCanon && fs.readFileSync(to,'utf8') === raw) {
    console.log(`\nNO CHANGE — ${path.basename(from)} is byte-identical to ${path.basename(to)}. `
              + `Nothing promoted, nothing touched (a rewrite would move the mtime for no reason).`);
    return;
  }

  console.log(`PROMOTE  ${from}\n     ->  ${to}`);
  console.log(`  observed derived ${obs.generated||'(undated)'} — ${spN} species, ${cellsN} move cells`);
  if (haveCanon) console.log(`  engine now       ${cur.generated||'(undated)'} — ${spO} species, ${cellsO} move cells`);

  if (spO) printDelta(delta(cur, obs), from, to);

  if (dry) { console.log(`\nDRY RUN — nothing written. Re-run without --dry-run to land it.`); return; }

  fs.writeFileSync(to, raw);
  console.log(`\nwrote ${to}`);
  console.log(`  This is an ENGINE SOURCE. The next engine_release.cut() mints a NEW release id, and`);
  console.log(`  every artifact stamped with the old one is correctly withheld. Do not promote while a`);
  console.log(`  measurement is running — that is the 2026-08-04 failure, and it is what this step exists`);
  console.log(`  to make a decision rather than an accident.`);
}

if (flag('promote')) { promote(); return module.exports={}; }

/* ------------------------------------------------------------------------------------------------
 * THE DERIVATION. Unchanged except for where it writes: the default OUT is the OBSERVED file, so
 * running this — by hand or by cron — can no longer redefine a frozen engine source.
 * ---------------------------------------------------------------------------------------------- */
const STORE=POS[0]||path.join(__dirname,'../data/games.ladder.jsonl');
/* THE PATH LITERAL IS REPEATED HERE DELIBERATELY, AND IT IS NOT A SLIP. engine/provenance.js
 * attributes an artifact to the generator that BINDS its name to an identifier which is then
 * written — the `const OUT = process.argv[3] || path.join(__dirname,'../data/move-priors.json')`
 * idiom, which that file documents as the arm it had to add for THIS script. Writing
 * `POS[1] || OBSERVED` hides the name from that scan, and the observed table landed in "no
 * generator" on the first run of this change: the bucket that is exempt from every corpus check in
 * provenance.js. Measured, not guessed. The two spellings are asserted equal on the next line
 * rather than trusted to stay in step. */
const OUT=POS[1]||path.join(__dirname,'../data/move-priors.observed.json');
if (!POS[1] && path.resolve(OUT) !== path.resolve(OBSERVED))
  throw new Error('the derivation default and the promote source have drifted apart: ' + OUT + ' vs ' + OBSERVED);

const sp={};                 // species -> {all:{move:count}, t1:{move:count}, acts}
const seen=new Set();
function bump(o,m){ o[m]=(o[m]||0)+1; }

/* CLEAN GAMES ONLY -- THIS IS THE BEHAVIOUR CLONE, SO IT IS THE WORST PLACE TO GET THIS WRONG.
 *
 * This read the WHOLE store. Of ~15,000 records only ~1,900 are clean; the rest are bot games,
 * forfeits, partial brings and stubs. So "what real ladder players actually click" -- the header
 * claim of this very file -- was in fact what BOTS click, by roughly seven to one. That distribution
 * is what MEW's pilot samples from and what MEDICHAM rolls out, so every downstream claim about
 * human behaviour inherited it.
 *
 * quality.js is the single definition of usable and every other consumer goes through it. */
const CLEAN=(()=>{ try{ return new Set(require('./quality.js').loadGames({path:STORE}).map(g=>g.id)); }
                   catch(e){ console.error('quality.js unavailable:',e.message); return null; } })();
if(!CLEAN||!CLEAN.size){ console.error('refusing to build the behaviour clone without the clean filter'); process.exit(1); }

for(const line of fs.readFileSync(STORE,'utf8').split('\n')){
  if(!line.trim())continue; let r; try{r=JSON.parse(line);}catch(e){continue;}
  if(!CLEAN.has(r.id))continue;
  if(seen.has(r.id))continue; seen.add(r.id);
  for(const t of (r.turns||[])){
    for(const e of t.ev){
      if(e.t!=='m'||!e.mon||!e.mv)continue;
      const s=e.mon, mv=key(e.mv);
      sp[s]=sp[s]||{all:{},t1:{},acts:0}; sp[s].acts++;
      bump(sp[s].all,mv); if(t.n===1) bump(sp[s].t1,mv);
    }
  }
}

// finalize -> probabilities + tags, keep species with enough signal
const out={ generated:new Date().toISOString().slice(0,10), species:{} };
let kept=0, statusMoves=0;
for(const s in sp){
  const d=sp[s]; if(d.acts<15) continue;          // need a real sample
  const total=Object.values(d.all).reduce((a,b)=>a+b,0);
  const moves=Object.entries(d.all).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([mv,c])=>{
    const cls=classify(mv); if(cls.kind!=='other'&&cls.kind!=='pivot') statusMoves++;
    return { mv, p:+(c/total).toFixed(3), kind:cls.kind, effect:cls.effect||null, boosts:cls.boosts||null };
  });
  const t1total=Object.values(d.t1).reduce((a,b)=>a+b,0)||1;
  const lead=Object.entries(d.t1).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([mv,c])=>({mv,p:+(c/t1total).toFixed(3),kind:classify(mv).kind}));
  out.species[s]={ acts:d.acts, moves, lead };
  kept++;
}
fs.writeFileSync(OUT, JSON.stringify(out));
process.stderr.write(`behaviour-clone: ${kept} species profiled from real clicks, ${statusMoves} non-damage move slots tagged -> ${OUT}\n`);
if (path.resolve(OUT) === path.resolve(OBSERVED))
  process.stderr.write(`  this is the OBSERVED table and nothing reads it. `
    + `node engine/policy.js --promote --dry-run  says what landing it would do to the engine.\n`);
/* human peek: a support mon's real move mix.
 *
 * `amoonguss` SAT IN THIS LIST AND IS NOT IN THIS REGULATION. Derived 2026-08-22 against
 * `Dex.forFormat('gen9championsvgc2026regmb')`: `isNonstandard: 'Past'`, `tier: 'Illegal'`, while
 * whimsicott / incineroar / torkoal all read `isNonstandard: null`. CLAUDE.md names this species
 * specifically as the thing never to print, and a diagnostic is not exempt — a peek line is
 * indistinguishable from a claim about the game we are playing.
 *
 * IT IS ALSO EVIDENCE, WHICH IS WHY THE NAME IS RECORDED HERE RATHER THAN JUST DELETED. The store
 * profiles it with real clicks, so those games are not Reg M-B. That is the corpus-contamination
 * question, it is OPS/ENGINE territory, and it is not fixed here. */
for(const s of ['whimsicott','incineroar','torkoal']){
  if(out.species[s]) process.stderr.write(`  ${s}: `+out.species[s].moves.map(m=>`${m.mv}${m.kind!=='other'?'['+m.kind+']':''} ${Math.round(m.p*100)}%`).join(', ')+'\n');
}
module.exports={};
