/* steering.js — THE SELECTION POLICY OF A DIFFERENTIAL RUN, DECLARED AND DIGESTED.
 *
 * ROADMAP #81 WIRE 5. This is a MEASUREMENT-INTEGRITY file, not a mechanic.
 *
 * ================= WHAT WENT WRONG ================================================================
 *
 * `game_differential.js` does not play random games. `covWant()` scores every legal action by the
 * LEAST-EXERCISED CENSUS MECHANIC it can reach, so `data/mechanics-census.json` decides which moves
 * the driver clicks and therefore WHICH GAMES THE RUN PLAYS. The census is regenerated by
 * `tests/test-mechanics.js` — which is what ENGINE runs after landing every single probe.
 *
 * So: LANDING A PROBE CHANGES THE SAMPLE THE DIFFERENTIAL MEASURES.
 *
 * THE RECEIPT (docs/ENGINE.md, WIRE 4). A before-arm read `-damage field 3` at 51 games / 50 distinct
 * causes; a second run of the IDENTICAL frozen release over a BYTE-IDENTICAL team store read 46 / 45.
 * A third run reproduced the second exactly. The instrument is deterministic and its INPUT was not.
 * Four WIREs have now been reported as before/after pairs, and every one of them landed probes into
 * the census in the same session.
 *
 * That is CLAUDE.md's photograph rule broken through a door the 23-file release did not cover:
 * *nothing in frame may move during a measurement, INCLUDING FILES THE MEASURING AGENT NEVER OPENS.*
 * The census is in frame because it decides the sample.
 *
 * ================= THREE SHAPES WERE AVAILABLE. THIS IS WHY THIS ONE ==============================
 *
 * (1) PUT THE CENSUS IN `engine_release.js`'s SOURCES. Rejected, and not on grounds of taste — it is
 *     WRONG FOR THE ONE USE CASE THAT MATTERS. A before-arm is run as `--release <old-id>`; if the
 *     census lived inside the release, the before-arm would read the OLD census and the after-arm the
 *     NEW one, so the two arms would steer DIFFERENTLY BY CONSTRUCTION. Freezing it makes each run
 *     individually reproducible and makes every before/after pair non-comparable, which is the exact
 *     failure being fixed. It is also unworkable in practice: the census carries a `generated`
 *     timestamp, so its bytes change on EVERY run of tests/test-mechanics.js even when no mechanic
 *     moved (measured 2026-08-07: content digest 28203348a7ff stable, file digest c6be796631be not).
 *     A release id would fork on every test run and `drift()` would be permanently non-zero.
 *
 * (2) A RUN-LOCAL SNAPSHOT TAKEN ONCE AT START. Rejected because it fixes nothing that is broken.
 *     The differential is single-process and already reads the census exactly once at module load,
 *     so there is no mid-run drift to prevent. The failure is BETWEEN ARMS, and a run-local snapshot
 *     says nothing about the other arm.
 *
 * (3) MAKE THE STEERING EXPLICIT, DECLARED, PINNABLE AND COMPARABLE. Taken. The run says out loud
 *     what selects its sample, records the exact bytes' digest in the artifact, can be PINNED to a
 *     named file so two arms are handed the same bytes, and `engine/arms_comparable.js` REFUSES a
 *     before/after pair whose steering digests differ. A future reader can tell whether two arms were
 *     comparable instead of having to trust that they were.
 *
 * ================= THE ONE RULE THIS FILE OBEYS ===================================================
 *
 * NO SILENT DEFAULT. An unreadable or unparsable steering input is a REFUSAL, never an empty target
 * list. An empty COV_TARGETS makes covWant return Infinity for everything, the driver falls back to
 * click order, and the run plays a perfectly plausible set of games under no steering at all while
 * reporting success. That is this project's signature failure mode, and it is one `catch {}` away.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { sha12 } = require('./engine_release.js');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const LIVE_CENSUS = path.join(ROOT, 'data', 'mechanics-census.json');

/* ---- THE CODE THAT REALISES THE POLICY, DIGESTED — 2026-09-05, MEASURE -------------------------
 *
 * ================= WHAT WENT WRONG, AGAIN, THROUGH THE DOOR THIS FILE LEFT OPEN ==================
 *
 * This file's header says a measurement is a photograph and *nothing in frame may move, INCLUDING
 * FILES THE MEASURING AGENT NEVER OPENS*. It then froze the census, the behaviour tables and the team
 * pool — every INPUT to the selection — and never froze the CODE that reads them.
 *
 * THE RECEIPT, 2026-09-05. Six whole-game runs were taken between 02:11 and 02:40 on one identical
 * set of pins: release 688e696f00c8, census pin 9446a684709d, team pool 0d103fb9fa87, 961 games,
 * turn cap 12, and byte-identical `driver_inputs` in all six. They read:
 *
 *     empirical  02:15   121 protocol / 34 board-material      prefer_narrowed = 20507
 *     empirical  02:29   121 protocol / 34 board-material      prefer_narrowed = 20507
 *     joint      02:26   138 protocol / 53 board-material      prefer_narrowed = 20353
 *     joint      02:32   167 protocol / 69 board-material      prefer_narrowed = 0
 *     joint      02:39   167 protocol / 69 board-material      prefer_narrowed = 0
 *     empirical  02:40   147 protocol / 55 board-material      prefer_narrowed = 0
 *
 * That was reported as the joint arm being NON-DETERMINISTIC. It is not. `engine/empirical_driver.js`
 * was rewritten at 02:27:26 — the Protect-amplification fix, which replaced a hard `prefer` narrowing
 * with `preferPool()` — and `engine/game_differential.js` at 02:28:45. Every run before those writes
 * played the narrowing policy and every run after played the sampled one; the arm reproduced EXACTLY
 * on both sides of the edit (167/167 bit-identical, 121/121 bit-identical, down to `credit_events`
 * and `shuffle_calls`). The variation was a code change, and it was invisible because no artifact
 * recorded a digest of the code.
 *
 * `engine/arms_comparable.js` was run on the 138 and one of the 167s and answered **COMPARABLE — a
 * difference between their numbers is the change under test**, and additionally called the pair a
 * REPEAT. Its own printed limits already named the hole: *"THE DRIVER ITSELF... no artifact records
 * its digest. WIRE 4 asserted it by hand."* A named limit is not a guard.
 *
 * ================= WHY IT IS DERIVED AND NOT A LIST ==============================================
 *
 * `engine_release.js`'s SOURCES list grew four times and every growth was found by a crash; the fix
 * there was `requireClosure()`, which DERIVES the reachable set from the entry file. The same
 * function serves here, so a driver file added tomorrow is digested the same day with nothing edited.
 * A typed list of instrument files is the hand-maintained ban list of four in a new costume.
 *
 * FROZEN FILES ARE EXCLUDED, AND THAT IS NOT TIDINESS. A run reads the release's SNAPSHOT bytes
 * through `REL.require`, never the live copy, so digesting the live copy of a frozen source would
 * report a difference that did not touch the run — a guard that cries wolf is one people route
 * around. Those files are stamped separately by `REL.stamp()` as `source_digests`.
 *
 * WHAT IT DOES NOT SEE, said out loud. Static local `require('./x.js')` only: a computed path or a
 * dynamic import is invisible, exactly as it is to the release closure. The Showdown checkout is
 * covered only by `showdown_commit`. `data/protocol-events.json` is still unstamped. */
function driverCode(opts) {
  opts = opts || {};
  const ER = require('./engine_release.js');
  const entryAbs = opts.entry || (require.main && require.main.filename) || null;
  if (!entryAbs) {
    throw new Error('steering.driverCode: no entry file. The instrument cannot digest itself, so a '
      + 'run taken now could not be shown to have used the same code as any other run.');
  }
  const entry = path.relative(ROOT, entryAbs).split(path.sep).join('/');
  const frozen = new Set(opts.frozen || []);
  const clo = ER.requireClosure([entry], ROOT);
  const files = {};
  for (const f of [entry, ...clo.escapes.keys()].sort()) {
    if (frozen.has(f)) continue;              // served from the snapshot, stamped as source_digests
    files[f] = sha12(path.join(ROOT, f));     // THROWS: an undigestable instrument file is a refusal
  }
  const roll = Object.entries(files).map(([f, d]) => f + '@' + d).join('\n');
  return {
    derived_from: 'engine/steering.js driverCode -> engine_release.requireClosure(' + entry + ')',
    entry,
    frozen_excluded: [...frozen].filter(f => clo.escapes.has(f) || f === entry).sort(),
    files,
    digest: crypto.createHash('sha256').update(roll).digest('hex').slice(0, 12),
    /* Unresolved edges are REPORTED, never swallowed. Two of the three seen on this tree are prose
     * inside a block comment in engine_release.js (`./x.js`, `./literal`); they are carried anyway,
     * because a reader deciding whether a closure was complete needs the list, not a summary. */
    unresolved: clo.unresolved,
    covers: 'the INSTRUMENT: every local .js reachable by static require from the entry point, minus '
          + 'the engine-release SOURCES which are served from the snapshot and stamped separately.',
    does_not_cover: 'a computed require path, a dynamic import, the Showdown checkout beyond '
          + '`showdown_commit`, and data/protocol-events.json (read as data, not required).',
  };
}

/* The version is part of the comparability check. If covWant's SCORING RULE ever changes, two arms
 * run either side of that change are not comparable even with identical census bytes — and the digest
 * alone could not say so, because the input did not move. Bump this when the rule moves. */
const POLICY = 'census-coverage-seeking/v1';
const POLICY_RULE =
  'at every decision the driver prefers the legal action reaching the least-exercised row of '
  + 'data/mechanics-census.json, ties broken toward the least-clicked entity (game_differential.js '
  + 'covWant/creditClick). The census therefore SELECTS THE SAMPLE this run measures.';

/* ---- THE SECOND ARM, 2026-08-29 -----------------------------------------------------------------
 *
 * A SECOND POLICY, NOT A REPLACEMENT, AND IT IS SELECTED BY ID.
 *
 * The coverage-seeker exercises mechanics rather than trying to win, so 944 of 961 games (98.2%) are
 * cut off by the turn cap and 17 end naturally — the differential has never compared a game's ENDING.
 * The empirical arm samples `data/move-priors.json` (P(move | species) over real ladder clicks)
 * instead, so the games are played the way people play them and can reach a result.
 *
 * IT DOES NOT REPLACE THE COVERAGE-SEEKER AND THAT IS MEASURED, NOT DEFERENCE. 48 legal moves are
 * clicked ZERO times in 21,726 real games and 187 fewer than 20 times, while the census and the
 * deliberate roster stage 500 moves / 202 abilities / 148 items regardless of usage. An empirical
 * driver cannot reach that tail by construction. Will, 2026-08-29: *"we play real games from showdown
 * tho"*, *"but we want to also test individual mechanics as well to make sure they work"*, *"thats
 * why we have both."*
 *
 * ASK FOR AN ARM BY ID. `--steering coverage|empirical`, defaulting to `coverage`, which is the arm
 * every published number was taken on. Asking by omission is what once produced 162 false
 * accusations in this repository.
 *
 * THE CENSUS IS STILL RESOLVED AND STILL DIGESTED UNDER THIS POLICY, and it is not decoration: the
 * credit rule keeps running, so coverage is still MEASURED. It simply no longer SELECTS. Both facts
 * are in the block below so a reader can tell which job the census was doing. */
const POLICY_EMPIRICAL = 'empirical-click/v1';
const POLICY_EMPIRICAL_RULE =
  'at every decision the driver draws the action from real recorded human play: P(move | species) '
  + 'from data/move-priors.json (its turn-1 `lead` table on turn one), with a voluntary switch drawn '
  + 'at the conditional rate measured in data/rollout-switch-census.json. Legality still comes from '
  + 'Showdown\'s own request and the configuration ban/prefer axes still narrow the pool first. The '
  + 'census is still CREDITED and no longer SELECTS; the behaviour tables select the sample.';

/* ---- THE THIRD ARM, 2026-09-05 ------------------------------------------------------------------
 *
 * A THIRD POLICY, AND `empirical-click/v1` KEEPS MEANING WHAT IT MEANT. The empirical arm declares
 * two gaps in its own header (engine/empirical_driver.js:56-64): it has NO TARGET MODEL — the caller
 * names the lowest live foe every time, which is 100% double-targeting against a measured human
 * 38.9% — and NO SWITCH MODEL beyond one pooled rate, against a measured 3.8%-18.5% span across
 * context. `joint-empirical-click/v1` closes both.
 *
 * IT IS A NEW ID RATHER THAN A WIDENING, and that is the whole reason it is here. Every whole-game
 * figure ever published carries `steering.policy`; silently changing what `empirical-click/v1` does
 * would make all of them ambiguous, and `comparable()` below would go on cheerfully pairing arms
 * taken either side of the change because their policy STRINGS still matched. It would also do it
 * silently, which is the failure this file exists to prevent.
 *
 * WHAT THIS MEANS FOR THE GATE, SAID BEFORE ANY RUN RATHER THAN AFTER. `engine/quarantine.js`'s
 * whole-game clause asks `PIN.guard({ ..., policy: POLICY_EMPIRICAL })` against
 * `data/game-differential.json`, and `vouches()` REFUSES any block declaring a different policy —
 * *"those are different populations, not a stronger and a weaker one."* So an artifact written under
 * this policy into the published slot would WITHHOLD the clause, not answer it. That is correct and
 * it is not a bug to route around: a joint-arm run belongs in `data/verification/` until somebody
 * decides, deliberately and in writing, which arm the gate is answerable by. */
const POLICY_JOINT = 'joint-empirical-click/v1';
const POLICY_JOINT_RULE =
  'everything `' + POLICY_EMPIRICAL + '` does, plus the two capabilities that policy declares it '
  + 'lacks. TARGET: the two active bodies no longer each name the lowest live foe — one anchor is '
  + 'drawn uniformly over the live foes and the partner joins it at the rate humans focus-fire '
  + '(data/joint-click-census.json, pooled.joint_target.pct_same_foe_clean), else takes the other. '
  + 'SWITCH: the voluntary-switch rate is read from a context cell (HP band x tenure on the field x '
  + 'bench size) rather than from one pooled constant, and WHICH body is sent prefers a body that has '
  + 'not yet been on the field at the measured rate. Legality still comes from Showdown\'s own '
  + 'request and the ban/prefer axes still narrow the pool first. The census is still CREDITED and '
  + 'still does not SELECT.';

/* Resolve the steering input for one run.
 *   opts.censusPath    an explicit file to pin to (the `--census` flag). Default: the live census.
 *   opts.mode          'coverage' (default) or 'empirical'.
 *   opts.driverInputs  REQUIRED under 'empirical'. An array of already-digested behaviour tables,
 *                      `[{ file, read_from, digest, generated, rows }]`. The CALLER computes these
 *                      because it is the one holding the engine-release handle, and "which copy of
 *                      the behaviour table did this run use" is a provenance question that belongs
 *                      where the bytes were read. An empty list under 'empirical' is a REFUSAL for
 *                      the same reason an unreadable census is: a run with no declared selector is a
 *                      run with no steering that looks like a run.
 * Returns a block that goes straight into the artifact and is what arms_comparable.js compares. */
/* THE ARM TABLE, IN ONE PLACE. `resolve`, `vouches` and `comparable` all used to ask
 * `=== 'empirical'` inline, so a third arm meant three edits and any one of them missed would leave a
 * policy that is table-driven being checked as though it were census-driven. */
const MODES = {
  coverage:  { policy: POLICY,           rule: POLICY_RULE,           tableDriven: false },
  empirical: { policy: POLICY_EMPIRICAL, rule: POLICY_EMPIRICAL_RULE, tableDriven: true },
  joint:     { policy: POLICY_JOINT,     rule: POLICY_JOINT_RULE,     tableDriven: true },
};
/* Which POLICY IDS select their sample from behaviour tables rather than from the census. Derived
 * from the table above so the two can never fall out of step. */
const TABLE_DRIVEN = new Set(Object.values(MODES).filter(m => m.tableDriven).map(m => m.policy));

function resolve(opts) {
  opts = opts || {};
  const mode = opts.mode || 'coverage';
  const M = MODES[mode];
  if (!M) {
    throw new Error('steering: unknown mode "' + mode + '". The arms are '
      + Object.entries(MODES).map(([k, v]) => '`' + k + '` (' + v.policy + ')').join(', ')
      + ', and one must be named by id.');
  }
  const driverInputs = opts.driverInputs || null;
  if (M.tableDriven && (!Array.isArray(driverInputs) || !driverInputs.length)) {
    throw new Error('steering: mode `' + mode + '` was asked for with no driverInputs. The behaviour '
      + 'tables ARE the selector under this policy; a block that does not name and digest them '
      + 'cannot be compared with any other run, and arms_comparable.js would have nothing to refuse.');
  }
  const pinned = !!opts.censusPath;
  const src = pinned ? path.resolve(opts.censusPath) : LIVE_CENSUS;

  let bytes;
  try { bytes = fs.readFileSync(src, 'utf8'); }
  catch (e) {
    /* REFUSE. See the header: an empty target set is a run with no steering that looks like a run. */
    throw new Error('steering: cannot read the selection input ' + src + ' — ' + e.message
      + '\n  This file DECIDES WHICH GAMES THE RUN PLAYS. Continuing without it would play an '
      + 'unsteered sample and report it as a steered one.');
  }
  let obj;
  try { obj = JSON.parse(bytes); }
  catch (e) {
    throw new Error('steering: ' + src + ' did not parse — ' + e.message
      + '\n  Refusing to run: an empty census makes every action score equally and the driver falls '
      + 'back to click order, silently.');
  }
  if (!obj || !Array.isArray(obj.results) || !obj.results.length) {
    throw new Error('steering: ' + src + ' carries no `results` rows. That is not a census, and a '
      + 'run steered by it would be steered by nothing.');
  }

  const digest = sha12(src);
  /* The LIVE digest is recorded even when the run is pinned, so a reader can see whether the pin was
   * already stale when the run was taken. `null` when the live file cannot be digested — UNKNOWN,
   * never a false match. */
  let live = null;
  try { live = sha12(LIVE_CENSUS); }
  catch (e) { console.error('  steering: could not digest the live census (' + e.message
    + ') — matches_live reads UNKNOWN, not false'); }

  return {
    policy: M.policy,
    rule: M.rule,
    /* WHAT JOB THE CENSUS IS DOING IN THIS RUN, said out loud rather than inferred from `policy`.
     * Under the empirical arm it is measured and not consulted; a reader who sees a census digest
     * beside a 1.8%-vs-64% completion claim should not have to work out which. */
    census_role: M.tableDriven ? 'CREDITED ONLY — it measures coverage and does not select'
                               : 'SELECTS THE SAMPLE — covWant reads it at every decision',
    driver_inputs: driverInputs || null,
    /* THE CODE THAT REALISES THE POLICY. See `driverCode` above for the receipt. The caller passes
     * the frozen set because it is the one holding the release handle — the same argument the
     * `driverInputs` note makes one field up. A caller that passes nothing gets the closure computed
     * here from `require.main`, which is right for every current caller and is recorded either way. */
    driver_code: opts.driverCode || driverCode({ frozen: opts.frozenFiles }),
    input: 'data/mechanics-census.json',
    input_read_from: pinned ? path.relative(ROOT, src).replace(/\\/g, '/') : 'data/mechanics-census.json',
    input_digest: digest,
    input_rows: obj.results.length,
    input_generated: obj.generated || null,
    input_live_digest: live,
    pinned,
    matches_live: live === null ? null : (live === digest),
    census: obj,
  };
}

/* ---- ONE BLOCK, ON ITS OWN: CAN IT VOUCH FOR ITS OWN POPULATION? — 2026-09-04 ------------------
 *
 * `comparable()` below answers a TWO-SIDED question and it was the only reader of these fields, so a
 * clause asking the ONE-SIDED question — *is this artifact's sample identified at all* — had nothing
 * to call and rolled its own. `wholeGameClause` rolled `steering.policy` and stopped there: it
 * refused the wrong DRIVER and waved through the wrong TEAM POOL, using a field this very file
 * already knew was load-bearing (`team_pool_digest`, whose absence `comparable()` has refused since
 * WIRE 5 — "the swarm reads the live game store, which OPS appends to").
 *
 * So the selector list lives in ONE function and both questions are asked through it. A selector
 * added here tomorrow is checked by every clause the same day, with no clause edited. That is the
 * whole point: the alternative is a per-clause list, and a per-clause list is the hand-maintained ban
 * list of four in a different costume.
 *
 * `opts.policy` — the arm the READER is answerable by. A block that declares a different policy is
 * not a weaker answer; it is an answer about other games (961 games, 17 of which end, is not a claim
 * about games).
 *
 * IT REFUSES ON ABSENCE, NOT ONLY ON MISMATCH. An artifact with no `steering` block is one whose
 * sample nobody recorded, and silence must never read as agreement. */
function vouches(s, opts) {
  const want = opts && opts.policy;
  const bad = [];
  if (!s || !s.policy) {
    bad.push('declares no steering policy at all — it predates engine/steering.js, so nothing '
      + 'recorded what selected its sample. NOT comparable.');
    return { ok: false, reasons: bad };
  }
  if (want && s.policy !== want) {
    bad.push('declares `' + s.policy + '` and the reader is answerable by `' + want + '`. Those are '
      + 'different populations, not a stronger and a weaker one.');
  }
  if (TABLE_DRIVEN.has(s.policy)) {
    const d = (s.driver_inputs || []).filter((x) => x && x.file && x.digest);
    if (!d.length) {
      bad.push('an `' + s.policy + '` arm records no `driver_inputs`, so the tables that '
        + 'SELECTED its sample cannot be shown equal. That block is what the census digest is under '
        + 'the coverage policy.');
    }
  } else if (!s.input_digest) {
    bad.push('records no `input_digest`, so the census bytes that SELECTED its sample are unknown. '
      + 'A census that gained rows changes WHICH scenarios play.');
  }
  if (s.team_pool_digest === undefined) {
    bad.push('does not record `team_pool_digest`, so the TEAMS it played cannot be identified. The '
      + 'swarm reads the live game store, which OPS appends to.');
  }
  return { ok: !bad.length, reasons: bad };
}

/* Two artifacts' steering blocks: may their numbers be compared?
 *
 * FAILS CLOSED ON AN ABSENT BLOCK. Every artifact written before this file existed has no `steering`,
 * and the honest answer for those is NOT that they were comparable — it is that nothing recorded
 * whether they were. Returning "ok" for a missing declaration would launder exactly the four
 * before/after pairs this wire exists to re-examine. */
function comparable(a, b) {
  const bad = [];
  /* THE ONE-SIDED QUESTION FIRST, THROUGH THE SHARED DOOR. An arm that cannot identify its own
   * population cannot be shown equal to anything, and asking that here rather than inline is what
   * keeps `vouches()` the single list of selectors. */
  for (const [name, s] of [['before', a], ['after', b]]) {
    const v = vouches(s);
    for (const r of v.reasons) bad.push(name + ' ' + r);
  }
  if (bad.length) return { ok: false, reasons: bad };
  if (a.policy !== b.policy) {
    bad.push('the selection POLICY differs: ' + a.policy + ' vs ' + b.policy
      + ' — the scoring rule itself moved, so identical inputs would still select different samples');
  }
  /* THE EMPIRICAL ARM'S OWN SELECTOR. Under `empirical-click/v1` the behaviour tables decide which
   * games get played, exactly as the census does under the coverage policy — so two arms handed
   * different `move-priors.json` or `rollout-switch-census.json` bytes are not a before/after, and
   * `data/move-priors.json` moves whenever somebody runs `node engine/policy.js --promote`.
   * Compared by DIGEST LIST so an added or removed table is a difference too. Reached only when both
   * arms already agree on `policy`, which the clause above enforces. */
  const digestsOf = s => (s.driver_inputs || []).map(x => (x && x.file) + '@' + (x && x.digest)).sort().join(', ');
  if (TABLE_DRIVEN.has(a.policy)) {
    const da = digestsOf(a), db = digestsOf(b);
    /* THE ABSENCE CASE IS REFUSED ONE LEVEL UP, by `vouches()`, and used to be spelled again here.
     * Two implementations of one refusal disagree eventually and both keep working — the message is
     * now written once, beside the selector list it belongs to. */
    if (da !== db) {
      bad.push('the BEHAVIOUR TABLES differ: ' + da + ' vs ' + db + '. Under empirical-click/v1 these '
        + 'select the sample, so the two arms played different games for a reason unrelated to the '
        + 'change under test.');
    }
  }
  /* THE INSTRUMENT ITSELF — 2026-09-05. Six runs on one identical set of pins read 121/138/147/167
   * because `engine/empirical_driver.js` was rewritten between them, and this function answered
   * COMPARABLE on a pair that spanned the edit. See `driverCode` above for the full receipt.
   *
   * EXACTLY-ONE-SIDE IS A REFUSAL, NOT A PASS. A new run against an artifact taken before this stamp
   * existed genuinely cannot be shown to have run the same instrument, and "nothing recorded it" has
   * to read as a refusal here or the stamp buys nothing on the first pair that matters — which is the
   * pair being taken tonight. It is the same rule `baselineGuard` already applies to a missing `pins`
   * block.
   *
   * BOTH-SIDES-MISSING KEEPS TODAY'S ANSWER, deliberately and with its reason: every artifact on disk
   * predates this field, refusing all of them retroactively would change no fact about them, and
   * `arms_comparable.js` has printed THE DRIVER ITSELF in its limits block the whole time. Those
   * pairs were never checked on this axis and still are not. */
  const ca = a.driver_code, cb = b.driver_code;
  if (ca && cb) {
    if (ca.digest !== cb.digest) {
      const moved = Object.keys(Object.assign({}, ca.files, cb.files))
        .filter(f => (ca.files || {})[f] !== (cb.files || {})[f]).sort();
      bad.push('the INSTRUMENT differs: driver code ' + ca.digest + ' vs ' + cb.digest + '. '
        + moved.length + ' file(s) moved between the arms — ' + moved.join(', ')
        + '. The code that reads the tables selects the sample just as much as the tables do; on '
        + '2026-09-05 one such edit moved a whole-game run from 138 to 167 divergences under pins '
        + 'that were otherwise byte-identical.');
    }
  } else if (ca || cb) {
    bad.push('only the ' + (ca ? 'before' : 'after') + '-arm records `driver_code`. The other predates '
      + 'the instrument stamp, so nothing recorded which bytes of engine/game_differential.js and '
      + 'engine/empirical_driver.js played its games. That is not "probably the same" — an edit to '
      + 'exactly those files is what produced 138 and 167 from identical pins.');
  }
  if (a.input_digest !== b.input_digest) {
    bad.push('the steering INPUT differs: ' + a.input + ' is ' + a.input_digest + ' in the before-arm and '
      + b.input_digest + ' in the after-arm (' + a.input_rows + ' vs ' + b.input_rows + ' rows, generated '
      + a.input_generated + ' vs ' + b.input_generated + '). The two arms played DIFFERENT GAMES for a '
      + 'reason unrelated to the change under test.');
  }
  /* THE SECOND STEERING INPUT, FOUND WHILE FIXING THE FIRST (WIRE 5). `diff_swarm.buildSwarm` reads
   * data/games.bo3.jsonl and data/games.ots.jsonl LIVE, dedupes to distinct teams and picks by a
   * STRIDE over the matching set — so one appended game shifts the stride and changes WHICH TEAMS get
   * played. OPS appends to that store continuously; it moved twice during this wire's own test runs.
   * WIRE 4 controlled it by asserting size and mtime by hand before, between and after both arms. This
   * is the same assertion made by the instrument, on the thing that actually matters: the digest of the
   * team KEYS actually picked, per configuration. `undefined` on either side is a REFUSAL, not a pass
   * — made by `vouches()` now, one level up, so the same refusal serves the one-sided readers too. */
  if (a.team_pool_digest !== b.team_pool_digest) {
    bad.push('the TEAM POOL differs: ' + a.team_pool_digest + ' vs ' + b.team_pool_digest + ' ('
      + a.team_pool_teams + ' vs ' + b.team_pool_teams + ' distinct teams in the corpus, '
      + a.team_pool_picked + ' vs ' + b.team_pool_picked + ' picked). The game store moved between the '
      + 'arms, so they played different teams — the other half of the sample.');
  }
  return { ok: !bad.length, reasons: bad };
}

module.exports = { resolve, comparable, vouches, driverCode, POLICY, POLICY_RULE,
                   POLICY_EMPIRICAL, POLICY_EMPIRICAL_RULE,
                   POLICY_JOINT, POLICY_JOINT_RULE, MODES, TABLE_DRIVEN, LIVE_CENSUS };
