/* steering.js — THE SELECTION POLICY OF A DIFFERENTIAL RUN, DECLARED AND DIGESTED.
 *
 * ROADMAP #81 WIRE 5. This is a MEASUREMENT-INTEGRITY file, not a mechanic.
 *
 * ================= WHAT WENT WRONG ================================================================
 *
 * `game_differential.js` does not play random games. `covWant()` scores every legal action by the
 * LEAST-EXERCISED CENSUS MECHANIC it can reach, so `data/mechanics-census.json` decides which moves
 * the driver clicks and therefore WHICH GAMES THE RUN PLAYS. The census is regenerated by
 * `tests/test-mechanics.js` — which is what ENGINE runs after landing every single probe.
 *
 * So: LANDING A PROBE CHANGES THE SAMPLE THE DIFFERENTIAL MEASURES.
 *
 * THE RECEIPT (docs/ENGINE.md, WIRE 4). A before-arm read `-damage field 3` at 51 games / 50 distinct
 * causes; a second run of the IDENTICAL frozen release over a BYTE-IDENTICAL team store read 46 / 45.
 * A third run reproduced the second exactly. The instrument is deterministic and its INPUT was not.
 * Four WIREs have now been reported as before/after pairs, and every one of them landed probes into
 * the census in the same session.
 *
 * That is CLAUDE.md's photograph rule broken through a door the 23-file release did not cover:
 * *nothing in frame may move during a measurement, INCLUDING FILES THE MEASURING AGENT NEVER OPENS.*
 * The census is in frame because it decides the sample.
 *
 * ================= THREE SHAPES WERE AVAILABLE. THIS IS WHY THIS ONE ==============================
 *
 * (1) PUT THE CENSUS IN `engine_release.js`'s SOURCES. Rejected, and not on grounds of taste — it is
 *     WRONG FOR THE ONE USE CASE THAT MATTERS. A before-arm is run as `--release <old-id>`; if the
 *     census lived inside the release, the before-arm would read the OLD census and the after-arm the
 *     NEW one, so the two arms would steer DIFFERENTLY BY CONSTRUCTION. Freezing it makes each run
 *     individually reproducible and makes every before/after pair non-comparable, which is the exact
 *     failure being fixed. It is also unworkable in practice: the census carries a `generated`
 *     timestamp, so its bytes change on EVERY run of tests/test-mechanics.js even when no mechanic
 *     moved (measured 2026-08-07: content digest 28203348a7ff stable, file digest c6be796631be not).
 *     A release id would fork on every test run and `drift()` would be permanently non-zero.
 *
 * (2) A RUN-LOCAL SNAPSHOT TAKEN ONCE AT START. Rejected because it fixes nothing that is broken.
 *     The differential is single-process and already reads the census exactly once at module load,
 *     so there is no mid-run drift to prevent. The failure is BETWEEN ARMS, and a run-local snapshot
 *     says nothing about the other arm.
 *
 * (3) MAKE THE STEERING EXPLICIT, DECLARED, PINNABLE AND COMPARABLE. Taken. The run says out loud
 *     what selects its sample, records the exact bytes' digest in the artifact, can be PINNED to a
 *     named file so two arms are handed the same bytes, and `engine/arms_comparable.js` REFUSES a
 *     before/after pair whose steering digests differ. A future reader can tell whether two arms were
 *     comparable instead of having to trust that they were.
 *
 * ================= THE ONE RULE THIS FILE OBEYS ===================================================
 *
 * NO SILENT DEFAULT. An unreadable or unparsable steering input is a REFUSAL, never an empty target
 * list. An empty COV_TARGETS makes covWant return Infinity for everything, the driver falls back to
 * click order, and the run plays a perfectly plausible set of games under no steering at all while
 * reporting success. That is this project's signature failure mode, and it is one `catch {}` away.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { sha12 } = require('./engine_release.js');

const ROOT = path.join(__dirname, '..');
const LIVE_CENSUS = path.join(ROOT, 'data', 'mechanics-census.json');

/* The version is part of the comparability check. If covWant's SCORING RULE ever changes, two arms
 * run either side of that change are not comparable even with identical census bytes — and the digest
 * alone could not say so, because the input did not move. Bump this when the rule moves. */
const POLICY = 'census-coverage-seeking/v1';
const POLICY_RULE =
  'at every decision the driver prefers the legal action reaching the least-exercised row of '
  + 'data/mechanics-census.json, ties broken toward the least-clicked entity (game_differential.js '
  + 'covWant/creditClick). The census therefore SELECTS THE SAMPLE this run measures.';

/* Resolve the steering input for one run.
 *   opts.censusPath  an explicit file to pin to (the `--census` flag). Default: the live census.
 * Returns a block that goes straight into the artifact and is what arms_comparable.js compares. */
function resolve(opts) {
  opts = opts || {};
  const pinned = !!opts.censusPath;
  const src = pinned ? path.resolve(opts.censusPath) : LIVE_CENSUS;

  let bytes;
  try { bytes = fs.readFileSync(src, 'utf8'); }
  catch (e) {
    /* REFUSE. See the header: an empty target set is a run with no steering that looks like a run. */
    throw new Error('steering: cannot read the selection input ' + src + ' — ' + e.message
      + '\n  This file DECIDES WHICH GAMES THE RUN PLAYS. Continuing without it would play an '
      + 'unsteered sample and report it as a steered one.');
  }
  let obj;
  try { obj = JSON.parse(bytes); }
  catch (e) {
    throw new Error('steering: ' + src + ' did not parse — ' + e.message
      + '\n  Refusing to run: an empty census makes every action score equally and the driver falls '
      + 'back to click order, silently.');
  }
  if (!obj || !Array.isArray(obj.results) || !obj.results.length) {
    throw new Error('steering: ' + src + ' carries no `results` rows. That is not a census, and a '
      + 'run steered by it would be steered by nothing.');
  }

  const digest = sha12(src);
  /* The LIVE digest is recorded even when the run is pinned, so a reader can see whether the pin was
   * already stale when the run was taken. `null` when the live file cannot be digested — UNKNOWN,
   * never a false match. */
  let live = null;
  try { live = sha12(LIVE_CENSUS); }
  catch (e) { console.error('  steering: could not digest the live census (' + e.message
    + ') — matches_live reads UNKNOWN, not false'); }

  return {
    policy: POLICY,
    rule: POLICY_RULE,
    input: 'data/mechanics-census.json',
    input_read_from: pinned ? path.relative(ROOT, src).replace(/\\/g, '/') : 'data/mechanics-census.json',
    input_digest: digest,
    input_rows: obj.results.length,
    input_generated: obj.generated || null,
    input_live_digest: live,
    pinned,
    matches_live: live === null ? null : (live === digest),
    census: obj,
  };
}

/* Two artifacts' steering blocks: may their numbers be compared?
 *
 * FAILS CLOSED ON AN ABSENT BLOCK. Every artifact written before this file existed has no `steering`,
 * and the honest answer for those is NOT that they were comparable — it is that nothing recorded
 * whether they were. Returning "ok" for a missing declaration would launder exactly the four
 * before/after pairs this wire exists to re-examine. */
function comparable(a, b) {
  const bad = [];
  for (const [name, s] of [['before', a], ['after', b]]) {
    if (!s || !s.policy) bad.push(name + ' declares no steering policy at all — it predates '
      + 'engine/steering.js, so nothing recorded what selected its sample. NOT comparable.');
  }
  if (bad.length) return { ok: false, reasons: bad };
  if (a.policy !== b.policy) {
    bad.push('the selection POLICY differs: ' + a.policy + ' vs ' + b.policy
      + ' — the scoring rule itself moved, so identical inputs would still select different samples');
  }
  if (a.input_digest !== b.input_digest) {
    bad.push('the steering INPUT differs: ' + a.input + ' is ' + a.input_digest + ' in the before-arm and '
      + b.input_digest + ' in the after-arm (' + a.input_rows + ' vs ' + b.input_rows + ' rows, generated '
      + a.input_generated + ' vs ' + b.input_generated + '). The two arms played DIFFERENT GAMES for a '
      + 'reason unrelated to the change under test.');
  }
  /* THE SECOND STEERING INPUT, FOUND WHILE FIXING THE FIRST (WIRE 5). `diff_swarm.buildSwarm` reads
   * data/games.bo3.jsonl and data/games.ots.jsonl LIVE, dedupes to distinct teams and picks by a
   * STRIDE over the matching set — so one appended game shifts the stride and changes WHICH TEAMS get
   * played. OPS appends to that store continuously; it moved twice during this wire's own test runs.
   * WIRE 4 controlled it by asserting size and mtime by hand before, between and after both arms. This
   * is the same assertion made by the instrument, on the thing that actually matters: the digest of the
   * team KEYS actually picked, per configuration. `undefined` on either side is a REFUSAL, not a pass. */
  if (a.team_pool_digest === undefined || b.team_pool_digest === undefined) {
    bad.push('one arm does not record `team_pool_digest`, so the two arms cannot be shown to have '
      + 'played the same TEAMS. The swarm reads the live game store, which OPS appends to.');
  } else if (a.team_pool_digest !== b.team_pool_digest) {
    bad.push('the TEAM POOL differs: ' + a.team_pool_digest + ' vs ' + b.team_pool_digest + ' ('
      + a.team_pool_teams + ' vs ' + b.team_pool_teams + ' distinct teams in the corpus, '
      + a.team_pool_picked + ' vs ' + b.team_pool_picked + ' picked). The game store moved between the '
      + 'arms, so they played different teams — the other half of the sample.');
  }
  return { ok: !bad.length, reasons: bad };
}

module.exports = { resolve, comparable, POLICY, POLICY_RULE, LIVE_CENSUS };
