/* wire_ladder.js — THE RELEASE LADDER. What one night of WIRE fixes actually bought, measured once,
 * controlled, over EVERY frozen release rather than adjacent pair by adjacent pair.
 *
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js                 run it, print the table
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js --write         + data/wire-ladder.json
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js --games 2700    the sample size (default 2700)
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js --keep-arms <d> keep every arm's full artifact
 *
 * ================= WHY THIS EXISTS =================================================================
 *
 * Six wires landed on 2026-08-06/07 and each published a before/after pair. WIRE 5 then found that
 * `data/mechanics-census.json` STEERS the differential's sample — `covWant()` prefers the action
 * reaching the least-exercised census row — and sat outside the photograph. Landing a probe changed
 * which games got played, so every pair before WIRE 6 was uncontrolled and its deltas are retracted
 * (CHANGELOG 3.62.1). WIRE 4's controlled re-run moved `-damage field 3` from a published 46/45->31/31
 * to an actual 59/56->38/35: the finding was REAL AND LARGER, the numbers were wrong.
 *
 * A pairwise before/after also cannot answer the question anybody actually has, which is what the
 * NIGHT bought. TEN releases are frozen along the way (nine from 2026-08-06/07 plus WIRE 7's), so the
 * ladder is replayable rather than a re-do: every rung is run under ONE pinned census and ONE team
 * pool, which makes all eleven arms mutually comparable instead of only adjacent.
 *
 * ================= WHAT THIS FILE IS AND IS NOT ===================================================
 *
 * IT ORCHESTRATES; IT DOES NOT MEASURE. Every number below comes out of `engine/game_differential.js`
 * run as a child process, and every comparability verdict comes out of `engine/arms_comparable.js`'s
 * own `compare()`. Nothing here reimplements a rule either of them owns — CLAUDE.md's canonical-path
 * rule, and the reason `status.js` shells out to `provenance.js` instead of copying its staleness
 * logic. A second implementation of "did these two arms sample the same population" is how two files
 * come to disagree about one fact.
 *
 * ONE RUN PER ARM, NOT TWO. The arm is run with `--verbose --write` together, so the per-game
 * divergence depth parsed from stdout and the artifact written to disk describe the SAME run. Running
 * twice and joining the two would be two photographs presented as one.
 *
 * ================= THE THREE THINGS THAT MAKE THE LADDER READABLE =================================
 *
 * 1. THE CENSUS IS PINNED TO A DURABLE FILE, not to the live one. `data/mechanics-census.json` is
 *    regenerated by `tests/test-mechanics.js` and moved twice during the night these releases were
 *    cut; WIRE 6's own published artifact pinned it to a path inside an agent's scratchpad, which is
 *    unauditable the moment that session ends. `data/wire-ladder-census.pin.json` is a copy of the
 *    live census taken at 2026-08-07T08:21Z and is checked in beside the result.
 *
 * 2. THE BASELINE IS RUN TWICE, FIRST AND LAST. Nine arms sit between the two, so a drift anywhere
 *    in the ladder — the team store appending, a stray regeneration — shows up as the two baselines
 *    disagreeing. If they disagree the whole ladder is uninterpretable AND THAT IS THE FINDING; this
 *    file says so rather than averaging them.
 *
 * 3. EVERY ARM IS CHECKED AGAINST THE BASELINE, NOT AGAINST ITS NEIGHBOUR. `arms_comparable.compare`
 *    runs for all of them and a refusal is REPORTED, never worked around.
 *
 * ================= WHICH RELEASES, AND WHY EACH INTERMEDIATE IS IN ================================
 *
 * The seven named wires left seven releases (WIRE 5 changed the INSTRUMENT and cut none). Three more
 * cuts sit between them, and all three carry a REAL ENGINE CHANGE rather than a re-cut — verified by
 * diffing the manifests, which show exactly one file moving anywhere in the ladder
 * (`engine/medicham2-browser.js`; the other 22 frozen files are byte-identical across all ten
 * releases). Excluding them would silently attribute their effect to the named wire that follows,
 * which is the same misattribution WIRE 5 was written to stop.
 */
'use strict';
require('./showdown_path.js');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const D = (...p) => path.join(__dirname, '..', ...p);
const ER = require('./engine_release.js');
const CMP = require('./arms_comparable.js');
const RS = require('./run_stamp.js');

const argv = process.argv.slice(2);
const flag = (n, d) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : d; };
const GAMES = +flag('--games', 2700);
const WRITE = argv.includes('--write');
const CENSUS = flag('--census', 'data/wire-ladder-census.pin.json');
const KEEP = flag('--keep-arms', null);
/* THE STATE LADDER (Will, 2026-08-07). `--state` runs every rung under `engine/board_state.js`'s
 * end-of-turn BOARD comparison as well as the protocol one, so the table can say what each wire bought
 * in the only currency a search spends: HP, status, items, stat stages, field conditions and who is
 * still alive. The protocol columns are unchanged and are printed beside it, because the whole point
 * is to compare the two instruments over the SAME games rather than across two runs.
 *
 * `--out` keeps the two ladders apart on disk. Writing a state ladder over data/wire-ladder.json would
 * silently replace the published protocol result with a differently-shaped one. */
const STATE = argv.includes('--state');
const OUT = flag('--out', STATE ? 'data/state-ladder.json' : 'data/wire-ladder.json');

if (!process.env.SHOWDOWN_PATH) {
  console.error('NOT RUN — the official simulator is absent. Set SHOWDOWN_PATH. This is not a pass.');
  process.exit(2);
}

/* THE RUNGS, IN THE ORDER THEY WERE CUT. `cut` is read from each release's own manifest rather than
 * typed here, so the chronology cannot be got wrong by hand. */
const ARMS = [
  { id: 'a01-baseline-run1', release: 'cf6a68fa412c', label: 'pre-WIRE-1 baseline',
    change: 'the engine as it stood before any of the night\'s wires' },
  { id: 'a02-mega-speed-order', release: '28e66a7c9ab8', label: 'INTERMEDIATE — mega resolution order',
    change: 'two megas in one turn resolve in SPEED order alone; megaEvo actions carry no priority, so '
          + 'a slow body clicking Protect (+4) had been megaing before a fast body clicking an attack',
    included_because: 'a real engine change between the baseline cut and WIRE 1. Folding it into WIRE 1 '
          + 'would credit WIRE 1 with an ordering fix it did not make.' },
  { id: 'a03-knockoff-bp-trunc', release: '0771dc47b5f6', label: 'INTERMEDIATE — Knock Off base power truncated',
    change: 'targetHasItem x1.5 is chainModify and therefore FIXED POINT: 65 x 1.5 is 97, not 97.5',
    included_because: 'a real engine change, and the ladder is the only place its whole-game effect '
          + 'can be seen at all — it is the smallest rung here and that is a result.' },
  { id: 'a04-wire1', release: '41e28311e591', label: 'WIRE 1',
    change: 'Protect is not an immunity: the shield preempts the accuracy roll, and a shielded High '
          + 'Jump Kick still pays its crash through onMoveFail' },
  { id: 'a05-wire2', release: '6b6f898f136f', label: 'WIRE 2',
    change: 'the stall counter resets on failure; a shield moving last fails' },
  { id: 'a06-wire3', release: '128a1ca28d34', label: 'WIRE 3',
    change: 'refused stat drops — scoped refusal, and they were being over-refused' },
  { id: 'a07-wire4-fixedpoint-only', release: '1e29ff6c431b', label: 'INTERMEDIATE — WIRE 4 first half',
    change: 'every damage multiplier in fixed point on 4096ths (md4096 / ch4096), Showdown\'s own '
          + 'round-half-up rather than a float truncation',
    included_because: 'WIRE 4 shipped as one wire and is two independent arithmetic fixes. Split, the '
          + 'ladder says what each half was worth; merged, it says only what the pair was worth.' },
  { id: 'a08-wire4', release: '45485dee6a43', label: 'WIRE 4 (complete)',
    change: '+ recoil is Math.round clamped to >= 1 on the RATIO, and drain is rounded not floored' },
  { id: 'a09-wire6', release: '3fd06d865427', label: 'WIRE 6',
    change: 'two of 27 action kinds announced nothing; four priority brackets wrong' },
  { id: 'a10-wire7', release: '0aa54cb1a9de', label: 'WIRE 7',
    change: 'six absent-or-misordered mechanics in one batch: Hospitality announces nothing onto a '
          + 'full-HP partner and never an -ability; Knock Off strips AFTER the damage and cannot take '
          + 'a mega stone; the pinch and status berries are onUpdate rather than residual; the '
          + 'substitute doll is ceil(maxhp/4) and its -start precedes the -damage; Protean converts '
          + 'before the hit so the move gets its STAB; a move redirect announces nothing and an '
          + 'ability redirect announces an -activate' },
  { id: 'a11-wire8', release: 'dd3da7c69cb0', label: 'WIRE 8',
    change: 'two families. A side condition that is already up is NOT re-set — Showdown\'s '
          + 'addSideCondition returns false and the move fails, where this engine wrote a second '
          + '-sidestart and reset the clock, so a Tailwind or a screen re-clicked each turn was '
          + 'permanent; screens are now three named conditions rather than two counters keyed by '
          + 'damage category, so each expires under its own name. And the two-turn wind-up happens '
          + 'even when the charge is skipped: |-prepare| is written first and unconditionally, and '
          + 'the charge-turn stat boost is taken — a rain Electro Shot was firing with no +1 SpA' },
  { id: 'a12-wire9', release: '86048ca3a422', label: 'WIRE 9',
    change: 'ROADMAP #81 WIRE 9 + ROADMAP #84. A SPREAD move carries no target on Showdown\'s own '
          + 'request, and playerAction\'s damaging branch was gated on having one — so every '
          + 'allAdjacentFoes / allAdjacent click from a driver reading the authority fell through to '
          + 'the status chain and became a no-op turn (33 legal moves, 56,524 corpus uses, dealing '
          + 'ZERO). It now aims off the board; a single-target click with the target withheld is '
          + 'still refused, and counted. The accuracy miss writes one |-miss| PER TARGET, each naming '
          + 'the body it missed, instead of one line with an empty target field. And the move RESULT '
          + 'is now stored and split three ways as Showdown stores it — false (flinch, paralysis, '
          + 'sleep, freeze, Taunt, Throat Chop, a miss, a type immunity), null (recharge, a fully '
          + 'shielded move) and true — so Stomping Tantrum and Temper Flare double after a failure '
          + 'and NOT after a recharge. Two things the family reached only once it started resolving are fixed in the same pass: Wide Guard NAMES each body it shielded (it wrote one line with an empty body field), and a quake resolves against your own partner FIRST, which is getMoveTargets\'s own allies-then-foes order' },
  { id: 'a13-wire10', release: 'dc3c43336539', label: 'WIRE 10',
    change: 'ROADMAP #81 WIRE 10 — THE SHAPE, NOT A MECHANIC. Showdown resolves a move as a STEP LIST '
          + 'over the whole target array: trySpreadMoveHit runs eight steps and each one walks every '
          + 'target before the next begins, and spreadMoveHit numbers six more inside the last. This '
          + 'engine ran ONE loop over the targets with the whole move inside it, so every effectiveness '
          + 'line, damage line, secondary and faint for target A was written before target B was even '
          + 'priced. The loop is now `for (step) for (target)`; the blocks did not move and the ORDER is '
          + 'data. Two consequences beyond the stream: the accuracy roll was step 0 here and is step 4 '
          + 'in the authority, so an immune body was announced as a MISS rather than as -immune whenever '
          + 'the die lost; and a KO scored on the first body of a spread move was handing the attacker '
          + 'its Beast Boost before the second body was priced, which is HP and not a protocol line. '
          + 'Single-target output is unchanged by construction — at one target the two loop orders are '
          + 'the same permutation, and 36/36 staged single-target clicks are byte-identical.' },
  { id: 'a14-baseline-run2', release: 'cf6a68fa412c', label: 'pre-WIRE-1 baseline, REPEATED',
    change: 'the same frozen bytes as a01, run last with ten arms in between — the drift check' },
];
/* WIRE 5 HAS NO RUNG AND THAT IS CORRECT. It changed the INSTRUMENT (engine/steering.js,
 * engine/arms_comparable.js), not the engine, so it cut no release and there is nothing to play. */

/* ---- THE INPUTS, DIGESTED BEFORE AND AFTER --------------------------------------------------------
 * `arms_comparable.js` names three things its own check cannot see. Two of them are files on this
 * machine, so they are digested here rather than left on a list: a ladder taken across ten runs has
 * ten chances for one of them to move. The third — an uncommitted edit inside SHOWDOWN_PATH — is still
 * outside anything this repository can observe, and is stated rather than implied. */
const WATCHED = [
  'data/games.bo3.jsonl', 'data/games.ots.jsonl', 'data/mechanics-census.json', CENSUS,
  'data/protocol-events.json', 'data/tags.json', 'data/engine-data.js',
  'engine/game_differential.js', 'engine/steering.js', 'engine/diff_swarm.js', 'engine/champions_sim.js',
];
const stampInputs = () => {
  const o = {};
  for (const f of WATCHED) {
    try { const s = fs.statSync(D(f)); o[f] = { size: s.size, sha12: ER.sha12(D(f)) }; }
    catch (e) { o[f] = { error: String((e && e.message) || e) }; }
  }
  return o;
};

/* `--resume <dir>` FINISHES A LADDER THAT DIED PART WAY, and it exists because one did. Fourteen arms
 * at ~400s is over an hour of wall clock in one process, and a run that loses arm 10 of 14 has thrown
 * away nine complete, correct, frozen-release measurements that are sitting on disk.
 *
 * AN ARM IS REUSED ONLY IF BOTH ITS FILES ARE THERE — the artifact AND the verbose log — because the
 * two are one run by construction (see runArm) and half of a pair is not a rung. Every reused arm is
 * PRINTED as reused; a resumed ladder that looked like a fresh one would be a silent default about the
 * most important property this file has, which is that all fourteen arms are the same photograph.
 *
 * THE TEAM STORE IS NOT RE-COPIED. The point of the freeze is that every arm reads the SAME bytes, so
 * a resume that took a fresh copy would hand the last arms a store the first ones never saw — exactly
 * the failure the freeze was added for. It is re-digested and printed instead. */
const RESUME = flag('--resume', null);
const ARM_DIR = RESUME ? path.resolve(RESUME)
              : KEEP ? path.resolve(KEEP)
              : fs.mkdtempSync(path.join(require('os').tmpdir(), 'abra-wire-ladder-'));
fs.mkdirSync(ARM_DIR, { recursive: true });

/* ---- THE LADDER TAKES ITS OWN PHOTOGRAPH OF THE TEAM STORE -------------------------------------
 *
 * IT PINNED THE CENSUS AND LEFT THE OTHER HALF OF THE SAMPLE LIVE, and that cost a whole run.
 * `engine/diff_swarm.js` reads `data/games.bo3.jsonl` and `data/games.ots.jsonl` LIVE and picks by a
 * STRIDE over the deduped set, so ONE appended game shifts which teams are played. OPS appends to that
 * file continuously. On 2026-08-07 it appended between arm 3 and arm 4 of a 14-arm state ladder — the
 * corpus went 7,454 -> 7,509 and the pool digest went `bd29c210884e` -> `32b2abcbfeb7`. The first three
 * rungs and the last eleven were sampling different populations. `arms_comparable.compare` would have
 * refused the table at the end, correctly, after two hours.
 *
 * `stampInputs` DIGESTING THE FILE BEFORE AND AFTER WAS NOT ENOUGH, and that is the lesson worth
 * keeping: it can only tell you afterwards that the run was wasted. CLAUDE.md says this in as many
 * words about engine releases — "it is a COPY, not a checksum: verifying digests afterwards only tells
 * you the run was wasted." The store is now COPIED once, before arm 1, and every arm reads the copy.
 *
 * `--no-pin-store` runs the old way, so the method behind data/wire-ladder.json can still be reproduced
 * exactly rather than being retroactively rewritten. */
const PIN_STORE = !argv.includes('--no-pin-store');
const STORE_DIR = path.join(ARM_DIR, 'team-store');
const STORE_FILES = ['games.bo3.jsonl', 'games.ots.jsonl'];
let STORE_STAMP = null;
if (PIN_STORE) {
  fs.mkdirSync(STORE_DIR, { recursive: true });
  STORE_STAMP = {};
  for (const f of STORE_FILES) {
    const src = D('data', f), dst = path.join(STORE_DIR, f);
    try {
      /* ON A RESUME THE EXISTING COPY IS THE PHOTOGRAPH — see the RESUME header. Overwriting it would
       * hand the remaining arms bytes the completed arms never read. */
      if (!(RESUME && fs.existsSync(dst))) fs.copyFileSync(src, dst);
      const s = fs.statSync(dst);
      STORE_STAMP[f] = { size: s.size, sha12: ER.sha12(dst), copied_from: src,
                         reused_from_a_previous_run: !!(RESUME && fs.existsSync(dst)) };
    } catch (e) {
      console.error('the team store could not be frozen (' + f + '): ' + String((e && e.message) || e)
        + '\nREFUSING — an unpinned store is how the last ladder was lost. Pass --no-pin-store to run '
        + 'the old way on purpose.');
      process.exit(4);
    }
  }
  console.log('\n  THE TEAM STORE IS FROZEN for this ladder: ' + STORE_DIR);
  for (const f of STORE_FILES) console.log('    ' + f.padEnd(20) + STORE_STAMP[f].sha12 + '  '
    + STORE_STAMP[f].size.toLocaleString() + ' bytes');
}

/* ---- ONE ARM --------------------------------------------------------------------------------------
 * `--verbose --write` in the SAME invocation: the depth distribution parsed from stdout and the
 * artifact on disk are then the same run. A run that threw is a REFUSAL — a ladder missing a rung is
 * not a ladder, and continuing past it would publish a table with a silent hole in it. */
function runArm(arm) {
  const out = path.join(ARM_DIR, arm.id + '.json');
  const logPath = path.join(ARM_DIR, arm.id + '.log');
  if (RESUME && fs.existsSync(out) && fs.existsSync(logPath)) {
    const j = JSON.parse(fs.readFileSync(out, 'utf8'));
    const depth = parseDepth(fs.readFileSync(logPath, 'utf8'), arm, j);
    return { artifact: j, depth, wall_s: null, path: out, reused: true };
  }
  const args = ['engine/game_differential.js', '--release', arm.release, '--census', CENSUS,
                '--games', String(GAMES), '--verbose', '--write', '--out', out]
                .concat(STATE ? ['--state'] : [])
                .concat(PIN_STORE ? ['--team-store', STORE_DIR] : []);
  const t0 = Date.now();
  let stdout;
  try {
    stdout = execFileSync(process.execPath, args, { cwd: D(), encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
  } catch (e) {
    console.error('ARM ' + arm.id + ' (release ' + arm.release + ') DID NOT COMPLETE — the ladder is '
      + 'incomplete and is not written.\n' + String((e && e.stderr) || (e && e.message) || e).slice(0, 4000));
    process.exit(4);
  }
  fs.writeFileSync(logPath, stdout);
  const j = JSON.parse(fs.readFileSync(out, 'utf8'));
  const depth = parseDepth(stdout, arm, j);
  return { artifact: j, depth, wall_s: +((Date.now() - t0) / 1000).toFixed(1), path: out, reused: false };
}

/* THE PER-GAME DEPTH, READ OFF THE DRIVER'S OWN VERBOSE LINE. `null` is a game that agreed all the
 * way through — kept as null and never as a large number, because "never diverged" and "diverged late"
 * are different events and a sentinel would let them average together.
 *
 * ONE IMPLEMENTATION, because a resumed arm parses a log off disk and a fresh one parses the same text
 * out of the child's stdout — and two copies of "how deep did this game get" would drift, which is the
 * defect CLAUDE.md names as facts-are-global. The count check travels with it for the same reason. */
function parseDepth(stdout, arm, j) {
  const depth = [];
  for (const l of String(stdout).split(/\r?\n/)) {
    const m = /DIVERGES at line (\d+)/.exec(l);
    if (m) { depth.push(+m[1]); continue; }
    if (/agrees, \d+ turns/.test(l)) depth.push(null);
  }
  if (depth.length !== j.games) {
    console.error('ARM ' + arm.id + ': the verbose stream carries ' + depth.length + ' games and the '
      + 'artifact says ' + j.games + '. They are the same run, so they must agree — refusing.');
    process.exit(4);
  }
  return depth;
}

/* ---- SUMMARY STATISTICS, ONE IMPLEMENTATION ------------------------------------------------------ */
const finite = v => v.filter(x => x != null);
const quant = (v, p) => { const s = finite(v).slice().sort((a, b) => a - b);
                          return s.length ? s[Math.min(s.length - 1, Math.floor(s.length * p))] : null; };
const mean = v => { const s = finite(v); return s.length ? +(s.reduce((a, b) => a + b, 0) / s.length).toFixed(2) : null; };
/* PAIRED, over the same games in the same order — the two arms played the identical sample, so this
 * is a paired comparison and not two independent rates. A game that never diverged is ranked deepest;
 * that is an ORDER statement (it parted later than any game that parted) and not an imputed value, so
 * it is used for the counts and excluded from the means above. */
function paired(a, b) {
  let later = 0, earlier = 0, same = 0;
  const deltas = [];
  for (let i = 0; i < a.length; i++) {
    const x = a[i] == null ? Infinity : a[i], y = b[i] == null ? Infinity : b[i];
    if (y > x) later++; else if (y < x) earlier++; else same++;
    if (a[i] != null && b[i] != null) deltas.push(b[i] - a[i]);
  }
  deltas.sort((p, q) => p - q);
  return { n: a.length, parted_later: later, parted_earlier: earlier, parted_at_the_same_line: same,
           net_later: later - earlier,
           median_delta_lines: deltas.length ? deltas[Math.floor(deltas.length / 2)] : null };
}
const classGames = (j, c) => { const x = j.classes.find(y => y.cls === c); return x ? x.games : 0; };
const classCauses = (j, c) => { const x = j.classes.find(y => y.cls === c); return x ? x.causes.length : 0; };
const totalCauses = j => j.classes.reduce((a, c) => a + c.causes.length, 0);

/* ---- RUN ------------------------------------------------------------------------------------------ */
const inputs_before = stampInputs();
console.log('\nTHE RELEASE LADDER — ' + ARMS.length + ' arms, ' + GAMES + ' games requested each, census pinned to '
  + CENSUS + ' (' + (inputs_before[CENSUS] || {}).sha12 + ')\n');

const RUNS = {};
for (const arm of ARMS) {
  const r = runArm(arm);
  RUNS[arm.id] = r;
  console.log('  ' + arm.id.padEnd(28) + arm.release + '   ' + r.artifact.diverged + '/' + r.artifact.games
    + ' diverged   ' + (r.reused ? 'REUSED from ' + ARM_DIR : r.wall_s + 's'));
}
const inputs_after = stampInputs();
const moved = WATCHED.filter(f => JSON.stringify(inputs_before[f]) !== JSON.stringify(inputs_after[f]));

/* ---- COMPARABILITY, EVERY ARM AGAINST THE BASELINE ------------------------------------------------ */
const BASE = ARMS[0];
/* THE TOP RUNG IS DERIVED, NOT TYPED. `what_remains_at_the_top_rung` below read a hard-coded
 * `'a09-wire6'` and was therefore TWO RUNGS STALE the moment WIRE 7 landed — the surviving-cause list
 * published with WIRE 7 was WIRE 6's, and it still named 251 hospitality rows that WIRE 7 had taken
 * to zero. Found by WIRE 8 while reading its own output. The top rung is the last arm that is NOT the
 * repeated baseline, and the arm it came from is written into the artifact so a stale read cannot
 * happen silently again. */
const TOP = [...ARMS].reverse().find(a => a.release !== BASE.release);
if (!TOP) { console.error('no non-baseline arm — refusing'); process.exit(4); }
const comparability = ARMS.slice(1).map(arm => {
  const r = CMP.compare(RUNS[BASE.id].artifact, RUNS[arm.id].artifact);
  return { arm: arm.id, release: arm.release, ok: r.ok, reasons: r.reasons,
           repeat_of_baseline: RUNS[arm.id].artifact.engine_release === RUNS[BASE.id].artifact.engine_release };
});
const refused = comparability.filter(c => !c.ok);

/* ---- THE DRIFT CHECK: the two baselines --------------------------------------------------------- */
const stripVolatile = (o) => {
  const c = JSON.parse(JSON.stringify(o));
  /* Everything removed here is a fact about WHEN the run happened or WHAT it was compared with, never
   * about what it measured. If any measured field differed the comparison below would say so. */
  for (const k of ['generated', 'elapsed_s', 'baseline_comparability', 'engine_release_cut',
                   'engine_release_cuts', 'steering']) delete c[k];
  return JSON.stringify(c);
};
/* THE TWO BASELINE ARMS ARE DERIVED, exactly as TOP is and for the same reason. These four lines
 * named `a01-baseline-run1` and `a12-baseline-run2` as literals, and WIRE 9 inserting a rung ahead of
 * the repeated baseline renamed the second one — so a typed id would have thrown on a missing key at
 * best, and at worst compared the wrong pair. That is the SAME defect WIRE 8 found in
 * `what_remains_at_the_top_rung`'s hard-coded 'a09-wire6', one function over: a name typed into a
 * generator goes stale the moment the thing it names moves. */
const BASE_ARMS = ARMS.filter(a => a.release === BASE.release);
if (BASE_ARMS.length !== 2) {
  console.error('the drift check needs EXACTLY two arms on the baseline release, found ' + BASE_ARMS.length
    + ' — refusing rather than comparing an arbitrary pair');
  process.exit(4);
}
const [BASE_FIRST, BASE_LAST] = BASE_ARMS;
const baselineReproduces = stripVolatile(RUNS[BASE_FIRST.id].artifact)
                        === stripVolatile(RUNS[BASE_LAST.id].artifact);
const baselineDepthIdentical = JSON.stringify(RUNS[BASE_FIRST.id].depth)
                            === JSON.stringify(RUNS[BASE_LAST.id].depth);

/* ---- THE TABLE ------------------------------------------------------------------------------------ */
const rows = ARMS.map((arm, i) => {
  const j = RUNS[arm.id].artifact, d = RUNS[arm.id].depth;
  const prev = i > 0 ? RUNS[ARMS[i - 1].id].depth : null;
  return {
    arm: arm.id, label: arm.label, release: arm.release,
    release_cut: j.engine_release_cut,
    medicham2_sha12: (j.source_digests || {})['engine/medicham2-browser.js'] || null,
    change: arm.change, included_because: arm.included_because || null,
    diverged: j.diverged, games: j.games, agreed_completely: j.games - j.diverged, threw: j.threw,
    classes: j.classes.length, distinct_causes: totalCauses(j),
    damage_field_3_games: classGames(j, '-damage field 3'),
    damage_field_3_causes: classCauses(j, '-damage field 3'),
    event_missing_from_medicham2_games: classGames(j, 'event missing from medicham2'),
    event_missing_from_medicham2_causes: classCauses(j, 'event missing from medicham2'),
    turn_order_games: classGames(j, 'turn order'),
    distinct_moves_connected: j.coverage.distinct_moves_connected,
    census_rows_exercised_by_a_connected_move: j.coverage.exercised_by_a_connected_move,
    median_completed_turns_before_divergence: j.coverage.median_completed_turns_before_divergence,
    /* THE FINER MEASURE, AND THE REASON IT IS HERE. The turn median has read 1 all night, so it cannot
     * distinguish a rung that helped from one that did not. The PROTOCOL LINE index can. */
    first_divergence_line: { median: quant(d, 0.5), mean: mean(d), p75: quant(d, 0.75), p90: quant(d, 0.9),
                             max: Math.max(...finite(d)) },
    /* THE STATE COLUMNS. `null` on a protocol-only ladder, which is a different claim from zero.
     * `state_families` is the actionable half: WHICH part of the board parted, collapsed the way the
     * protocol side collapses causes, so a rung that fixed HP and a rung that fixed a clock do not
     * read as one number. */
    state: !j.state ? null : {
      /* THE HEADLINE COLUMN, FIRST IN THE OBJECT AS IT IS FIRST IN THE REPORT. Will, 2026-08-07:
       * *"I ONLY CARE ABOUT TURN 1 TO START."* Bounded, target 100%, and — unlike the median first
       * divergence turn, which read 1 at all ten rungs — it cannot be blinded by a bimodal
       * distribution. `identical_at_end_of_turn` carries turns 2 and 3 beside it so the decay shows. */
      turn1: j.state.turn1 ? {
        games: j.state.turn1.games,
        identical: j.state.turn1.identical,
        rate_of_all_games: j.state.turn1.rate_of_all_games,
        reached_a_turn1_boundary: j.state.turn1.reached_a_turn1_boundary,
        rate_of_games_that_reached_it: j.state.turn1.rate_of_games_that_reached_it,
        protocol_parted_during_turn1: j.state.turn1.protocol_parted_during_turn1,
        protocol_parted_during_turn1_board_identical_anyway:
          j.state.turn1.protocol_parted_during_turn1_board_identical_anyway,
        by_field: j.state.turn1.by_field,
        by_cause: j.state.turn1.by_cause,
        by_protocol_class: j.state.turn1.by_protocol_class,
      } : null,
      turn1_boards_identical: j.state.turn1_boards_identical,
      turn1_boards_identical_fraction: j.state.turn1_boards_identical_fraction,
      identical_at_end_of_turn: j.state.identical_at_end_of_turn || null,
      /* TURNS 1..12 SEPARATELY, each with its own denominator. `turn_boundary_agreement` below pools
       * them and is kept precisely so the contamination is visible by comparison. */
      agreement_by_turn: j.state.agreement_by_turn || null,
      turn_boundaries_compared: j.state.turn_boundaries_compared,
      turn_boundaries_identical: j.state.turn_boundaries_identical,
      turn_boundary_agreement: j.state.turn_boundary_agreement,
      games_board_never_diverged: j.state.games_board_never_diverged,
      game_agreement: j.state.game_agreement,
      median_turn_of_first_board_divergence: j.state.median_turn_of_first_board_divergence,
      protocol_diverged_games: j.state.protocol_diverged_games,
      protocol_diverged_board_never_did: j.state.protocol_diverged_board_never_did,
      protocol_diverged_board_held_longer: j.state.protocol_diverged_board_held_longer,
      board_parted_before_the_protocol_did: j.state.board_parted_before_the_protocol_did,
      screens_shape_medicham: j.state.screens_shape_medicham,
      reader_failures: j.state.reader_failures,
      planted_state_proof_ok: j.state.planted_state_proof_ok,
      mappings_all_proved: j.state.mappings_all_proved,
      families: j.state.families,
    },
    vs_baseline: i === 0 ? null : paired(RUNS[BASE.id].depth, d),
    vs_previous_rung: prev ? paired(prev, d) : null,
    class_counts: Object.fromEntries(j.classes.map(c => [c.cls, c.games])),
    planted_divergence_proof_ok: j.planted_divergence_proof_ok,
    normaliser_all_rules_proved: j.normalisation.all_rules_proved,
    declared_gaps: j.declared_gaps,
    wall_s: RUNS[arm.id].wall_s,
  };
});

const pad = (s, n) => String(s).padEnd(n);
console.log('\n  arm                          div/total   cls  causes  dmgF3  evMiss  moves  medTurn  medLine  meanLine');
for (const r of rows) console.log('  ' + pad(r.arm, 28) + pad(r.diverged + '/' + r.games, 12)
  + pad(r.classes, 5) + pad(r.distinct_causes, 8) + pad(r.damage_field_3_games, 7)
  + pad(r.event_missing_from_medicham2_games, 8) + pad(r.distinct_moves_connected, 7)
  + pad(r.median_completed_turns_before_divergence, 9) + pad(r.first_divergence_line.median, 9)
  + r.first_divergence_line.mean);

/* THE STATE TABLE, PRINTED BESIDE THE PROTOCOL ONE AND NEVER INSTEAD OF IT. The two answer different
 * questions and the whole reason this ladder was re-run is that only one of them was ever asked. */
if (STATE) {
  const pct = v => (v == null ? '  n/a' : (100 * v).toFixed(1) + '%');
  /* PRINTED FIRST AND ON ITS OWN, because it is the one number this ladder is now for. */
  console.log('\n  ============================================================================');
  console.log('  THE HEADLINE — FRACTION OF GAMES WHOSE BOARD IS IDENTICAL AT THE END OF TURN 1');
  console.log('  ============================================================================');
  console.log('  arm                          turn 1            turn 2            turn 3        protoDiv-in-T1 -> same board');
  for (const r of rows) {
    const s = r.state;
    if (!s || !s.turn1) { console.log('  ' + pad(r.arm, 28) + 'NOT MEASURED'); continue; }
    const d = s.identical_at_end_of_turn || [];
    const cell = e => (e ? pad(e.identical + '/' + e.games + '  ' + pct(e.rate_of_all_games), 18) : pad('n/a', 18));
    console.log('  ' + pad(r.arm, 28) + cell(d[0]) + cell(d[1]) + cell(d[2])
      + s.turn1.protocol_parted_during_turn1_board_identical_anyway + '/' + s.turn1.protocol_parted_during_turn1);
  }
  /* THE FULL DECAY AT THE TWO ENDS OF THE LADDER. Printing all twelve turns for all fourteen arms
   * would be 168 rows; the artifact carries every one of them per arm, and the console shows the two
   * rungs anybody compares. */
  {
    const show = (arm) => {
      const s = (RUNS[arm.id].artifact.state || {}).agreement_by_turn;
      if (!s) return;
      console.log('  ' + arm.id + '  (' + arm.label + ')');
      console.log('    turn      1     2     3     4     5     6     7     8     9    10    11    12');
      console.log('    ident %' + s.map(e => (e.reached ? (100 * e.rate_given_it_reached_this_turn).toFixed(0) + '%' : '  -').padStart(6)).join(''));
      console.log('    reached ' + s.map(e => String(e.reached).padStart(5) + ' ').join('').slice(0, 72));
    };
    console.log('\n  THE DECAY, TURN BY TURN, denominator = games that REACHED that turn:');
    show(BASE); show(TOP);
    console.log('  (every arm carries the full array in the artifact as arms[].state.agreement_by_turn)');
  }
  console.log('\n  THE SAME LADDER, SCORED ON THE BOARD AT THE TURN BOUNDARY:');
  console.log('  arm                          turns identical      games clean        medTurn  protoDiv->sameBoard  proof');
  for (const r of rows) {
    const s = r.state;
    if (!s) { console.log('  ' + pad(r.arm, 28) + 'NOT MEASURED'); continue; }
    console.log('  ' + pad(r.arm, 28)
      + pad(s.turn_boundaries_identical + '/' + s.turn_boundaries_compared + '  ' + pct(s.turn_boundary_agreement), 20)
      + pad(s.games_board_never_diverged + '/' + r.games + '  ' + pct(s.game_agreement), 18)
      + pad(s.median_turn_of_first_board_divergence, 9)
      + pad(s.protocol_diverged_board_never_did + '/' + s.protocol_diverged_games, 21)
      + (s.planted_state_proof_ok && s.mappings_all_proved ? 'ok' : 'FAILED'));
  }
  const bad = rows.filter(r => r.state && !(r.state.planted_state_proof_ok && r.state.mappings_all_proved));
  if (bad.length) console.log('\n  ' + bad.length + ' ARM(S) FAILED THE STATE COMPARATOR\'S OWN PROOF — their state '
    + 'numbers are worthless: ' + bad.map(r => r.arm).join(', '));
  const rf = rows.filter(r => r.state && Object.keys(r.state.reader_failures || {}).length);
  if (rf.length) console.log('  READER FAILURES on ' + rf.length + ' arm(s): '
    + rf.map(r => r.arm + ' ' + JSON.stringify(r.state.reader_failures)).join('; '));
  const shapes = [...new Set(rows.filter(r => r.state).map(r => JSON.stringify(r.state.screens_shape_medicham)))];
  console.log('  side-condition shapes seen across the ladder (both must be readable): ' + shapes.join('  '));
}

console.log('\n  THE BASELINE, RUN TWICE WITH EIGHT ARMS BETWEEN: '
  + (baselineReproduces && baselineDepthIdentical
      ? 'REPRODUCES EXACTLY — every measured field identical, and the per-game divergence depth identical game for game.'
      : 'DOES NOT REPRODUCE. The ladder is uninterpretable and that is the finding.'));
console.log('  COMPARABILITY: ' + (refused.length ? refused.length + ' ARM(S) REFUSED' : 'all '
  + comparability.length + ' arms COMPARABLE with the baseline'));
for (const c of refused) { console.log('    REFUSED ' + c.arm); for (const x of c.reasons) console.log('      - ' + x); }
console.log('  INPUTS UNDER THE LADDER: ' + (moved.length ? 'MOVED — ' + moved.join(', ')
  : 'all ' + WATCHED.length + ' watched files byte-identical before and after'));
{
  const digests = new Set(ARMS.map(a => ((RUNS[a.id].artifact.steering) || {}).team_pool_digest));
  console.log('  THE TEAM POOL: ' + (PIN_STORE ? 'PINNED to a copy taken before arm 1' : 'read LIVE — unpinned')
    + ', and every arm reported '
    + (digests.size === 1 ? 'THE SAME digest ' + [...digests][0]
       : digests.size + ' DIFFERENT digests — THE ARMS DID NOT PLAY THE SAME TEAMS: ' + [...digests].join(', ')));
  if (digests.size !== 1) process.exitCode = 1;
}
console.log('');

if (WRITE) {
  const artifact = {
    generated: new Date().toISOString(), by: 'engine/wire_ladder.js',
    what: 'every frozen release of the 2026-08-06/07 wire night, run through engine/game_differential.js '
        + 'under ONE pinned census and ONE team pool, so all arms are mutually comparable rather than '
        + 'only adjacent. Replaces the retracted pairwise before/afters of CHANGELOG 3.62.1.',
    games_requested: GAMES,
    games_per_arm: rows[0].games,
    /* SAID IN THE ARTIFACT, not only on the console. A resumed ladder is still one photograph — the
     * frozen store and the pinned census are the same bytes for every arm — but a reader must be able
     * to tell that the arms did not all run in one process. */
    resumed_from: RESUME ? ARM_DIR : null,
    arms_reused: ARMS.filter(a => RUNS[a.id].reused).map(a => a.id),
    /* CONTENT, NOT MTIME. `engine/provenance.js` ratchets down the count of artifacts it can only
     * check by mtime, and a new one that rests on mtime BREAKS that ratchet — which it did on this
     * file's first run, correctly.
     *
     * WHAT IS DELIBERATELY NOT IN HERE: `engine/medicham2-browser.js`. The ladder reads NINE FROZEN
     * COPIES of it out of `data/releases/`, and never the live file. Stamping the live one would mark
     * this artifact UNSAFE the moment ENGINE touches a file it did not read, which is a false alarm of
     * exactly the kind that gets a checker ignored. Each arm carries the frozen digest it actually
     * played, in `arms[].medicham2_sha12`. */
    source_digests: RS.sourceDigests(WATCHED),
    /* THE STARVED CONFIGURATIONS ARE NAMED BY THE ARTIFACT, NOT BY THIS FILE. The first version typed
     * them into the sentence, and `engine/conformance.js` S12b flagged it — correctly, even though it
     * had matched a diff_swarm CONFIG ID rather than a move: a name typed here goes stale the moment
     * the swarm's configuration list changes, which is the whole defect S12 exists to catch. Read off
     * the baseline arm's own `swarm` block, so the sentence describes the run that was played. */
    sample_size_reason: 'the largest sample the swarm sustains before the starved configurations ('
        + (RUNS[BASE.id].artifact.swarm || []).slice().sort((a, b) => a.available - b.available)
            .slice(0, 2).map(s => s.config + ': ' + s.available + ' teams available').join(', ')
        + ') stop contributing marginal games, and '
        + 'small enough that all ten arms finish inside one photograph window. Identical for every arm '
        + 'by construction: only engine/medicham2-browser.js differs across the nine releases, so '
        + 'buildPair reaches the same teams in every arm.',
    /* THE STEERING BLOCK. Read from the baseline arm's own artifact rather than restated, so it cannot
     * disagree with what the runs actually used. */
    steering: RUNS[BASE.id].artifact.steering,
    steering_note: 'PINNED to a durable file checked in beside this artifact. WIRE 6\'s published run '
        + 'pinned the census to a path inside an agent scratchpad, which stops being checkable the '
        + 'moment that session ends.',
    instrument: {
      note: 'engine/arms_comparable.js names three inputs its own check cannot see. Two are files here '
          + 'and are digested before and after every arm; the third is stated and remains outside.',
      showdown_commit: RUNS[BASE.id].artifact.showdown_commit || null,
      still_outside: 'an uncommitted edit inside SHOWDOWN_PATH is invisible to `showdown_commit`.',
      inputs_before, inputs_after, inputs_that_moved: moved,
      nothing_in_frame_moved: moved.length === 0,
      /* THE TEAM STORE IS COPIED, NOT WATCHED. A digest before and after can only report afterwards
       * that the run was wasted — see the STORE_DIR block above for the ladder this cost. When it is
       * pinned, `inputs_that_moved` naming games.bo3.jsonl is NOT a fault: the ladder read the copy. */
      team_store_pinned: PIN_STORE, team_store_dir: PIN_STORE ? STORE_DIR : null,
      team_store: STORE_STAMP,
      team_pool_digest_per_arm: Object.fromEntries(ARMS.map(a =>
        [a.id, ((RUNS[a.id].artifact.steering) || {}).team_pool_digest || null])),
      every_arm_played_the_same_team_pool:
        new Set(ARMS.map(a => ((RUNS[a.id].artifact.steering) || {}).team_pool_digest)).size === 1,
    },
    determinism: {
      what: 'the pre-WIRE-1 baseline was run FIRST and LAST with eight arms in between',
      reproduces: baselineReproduces,
      per_game_depth_identical: baselineDepthIdentical,
      verdict: baselineReproduces && baselineDepthIdentical
        ? 'the instrument is deterministic across the whole ladder, so every difference in the table '
          + 'below is the engine change and not the run'
        : 'THE TWO BASELINES DISAGREE. Do not read the table below as a ladder.',
    },
    comparability: { all_ok: !refused.length, per_arm: comparability },
    arms: rows,
    /* WHAT REMAINS, so the ladder ends in something actionable rather than in a score. */
    top_rung: { arm: TOP.id, label: TOP.label, release: TOP.release },
    what_remains_at_the_top_rung: (() => {
      const j = RUNS[TOP.id].artifact;
      return [...j.classes].sort((a, b) => b.games - a.games).slice(0, 6).map(c => ({
        cls: c.cls, games: c.games, distinct_causes: c.causes.length,
        top_causes: [...c.causes].sort((a, b) => b.n - a.n).slice(0, 5).map(x => ({
          n: x.n, cause: x.cause, cannot_occur_in_format: x.cannot_occur_in_format, max_uses: x.max_uses })),
      }));
    })(),
    arm_artifacts: KEEP ? ARM_DIR : 'not kept — re-run this file to regenerate them',
    /* THE NEXT WIRE QUEUE, AND IT IS THE FIRST ONE THIS PROJECT HAS CHOSEN BY WHAT CHANGES A BOARD.
     * `what_remains_at_the_top_rung` above ranks by protocol CLASS, which is a ranking of narration.
     * This ranks the fields the end-of-turn-1 BOARD actually parted on at the same rung, with the
     * magnitude buckets kept apart — an HP off by one and an HP off by forty are different work. */
    turn1_queue_at_the_top_rung: !STATE ? null : (() => {
      const s = (RUNS[TOP.id].artifact.state || {}).turn1;
      if (!s) return null;
      return { arm: TOP.id, release: TOP.release, by_field: s.by_field, by_cause: s.by_cause.slice(0, 25),
               by_protocol_class: s.by_protocol_class,
               /* THE PLAIN-ENGLISH TURNS. Will: *"OR YOU CAN TELL ME."* Each one names the four bodies,
                * the four clicks, what the authority says, what this engine says, and the field diff.
                * Kept in the artifact so the report and the file cannot drift apart. */
               cases: s.cases };
    })(),
  };
  artifact.mode = STATE ? 'protocol + end-of-turn BOARD state' : 'protocol only';
  artifact.state_instrument = STATE ? {
    what: 'engine/board_state.js — HP, status (with the toxic stage and turns slept), item, all seven '
        + 'stat stages, fainted and species per active body; every party member\'s HP and aliveness; '
        + 'weather / terrain / Trick Room / Tailwind / each screen with its counter; hazard layer '
        + 'counts; and the persistent volatiles (Substitute with its HP, Taunt, Encore, Disable, Leech '
        + 'Seed, confusion, Perish, move-trapping with its counter).',
    boundary: 'AFTER the entire residual phase and before the next set of choices — the board the next '
            + 'decision is actually made from. Taken any earlier and Leftovers, chip, the toxic stage, '
            + 'Leech Seed, Perish and every ticking clock are invisible.',
    read_from: 'the live bodies of both engines. NEITHER ENGINE\'S LOG IS OPENED — deriving a board '
             + 'from the protocol would reproduce the bug this instrument exists to escape.',
    not_compared: (RUNS[BASE.id].artifact.state || {}).not_compared || null,
    mappings: (RUNS[BASE.id].artifact.state || {}).mappings || null,
    planted_state_proof: (RUNS[BASE.id].artifact.state || {}).planted_state_proof || null,
  } : null;
  fs.writeFileSync(D(...OUT.split('/')), JSON.stringify(artifact, null, 2) + '\n');
  console.log('  -> ' + OUT);
}

process.exitCode = (refused.length || !baselineReproduces) ? 1 : 0;
