/* wire_ladder.js — THE RELEASE LADDER. What one night of WIRE fixes actually bought, measured once,
 * controlled, over EVERY frozen release rather than adjacent pair by adjacent pair.
 *
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js                 run it, print the table
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js --write         + data/wire-ladder.json
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js --games 2700    the sample size (default 2700)
 *   SHOWDOWN_PATH=... node engine/wire_ladder.js --keep-arms <d> keep every arm's full artifact
 *
 * ================= WHY THIS EXISTS =================================================================
 *
 * Six wires landed on 2026-08-06/07 and each published a before/after pair. WIRE 5 then found that
 * `data/mechanics-census.json` STEERS the differential's sample — `covWant()` prefers the action
 * reaching the least-exercised census row — and sat outside the photograph. Landing a probe changed
 * which games got played, so every pair before WIRE 6 was uncontrolled and its deltas are retracted
 * (CHANGELOG 3.62.1). WIRE 4's controlled re-run moved `-damage field 3` from a published 46/45->31/31
 * to an actual 59/56->38/35: the finding was REAL AND LARGER, the numbers were wrong.
 *
 * A pairwise before/after also cannot answer the question anybody actually has, which is what the
 * NIGHT bought. TEN releases are frozen along the way (nine from 2026-08-06/07 plus WIRE 7's), so the
 * ladder is replayable rather than a re-do: every rung is run under ONE pinned census and ONE team
 * pool, which makes all eleven arms mutually comparable instead of only adjacent.
 *
 * ================= WHAT THIS FILE IS AND IS NOT ===================================================
 *
 * IT ORCHESTRATES; IT DOES NOT MEASURE. Every number below comes out of `engine/game_differential.js`
 * run as a child process, and every comparability verdict comes out of `engine/arms_comparable.js`'s
 * own `compare()`. Nothing here reimplements a rule either of them owns — CLAUDE.md's canonical-path
 * rule, and the reason `status.js` shells out to `provenance.js` instead of copying its staleness
 * logic. A second implementation of "did these two arms sample the same population" is how two files
 * come to disagree about one fact.
 *
 * ONE RUN PER ARM, NOT TWO. The arm is run with `--verbose --write` together, so the per-game
 * divergence depth parsed from stdout and the artifact written to disk describe the SAME run. Running
 * twice and joining the two would be two photographs presented as one.
 *
 * ================= THE THREE THINGS THAT MAKE THE LADDER READABLE =================================
 *
 * 1. THE CENSUS IS PINNED TO A DURABLE FILE, not to the live one. `data/mechanics-census.json` is
 *    regenerated by `tests/test-mechanics.js` and moved twice during the night these releases were
 *    cut; WIRE 6's own published artifact pinned it to a path inside an agent's scratchpad, which is
 *    unauditable the moment that session ends. `data/wire-ladder-census.pin.json` is a copy of the
 *    live census taken at 2026-08-07T08:21Z and is checked in beside the result.
 *
 * 2. THE BASELINE IS RUN TWICE, FIRST AND LAST. Nine arms sit between the two, so a drift anywhere
 *    in the ladder — the team store appending, a stray regeneration — shows up as the two baselines
 *    disagreeing. If they disagree the whole ladder is uninterpretable AND THAT IS THE FINDING; this
 *    file says so rather than averaging them.
 *
 * 3. EVERY ARM IS CHECKED AGAINST THE BASELINE, NOT AGAINST ITS NEIGHBOUR. `arms_comparable.compare`
 *    runs for all of them and a refusal is REPORTED, never worked around.
 *
 * ================= WHICH RELEASES, AND WHY EACH INTERMEDIATE IS IN ================================
 *
 * The seven named wires left seven releases (WIRE 5 changed the INSTRUMENT and cut none). Three more
 * cuts sit between them, and all three carry a REAL ENGINE CHANGE rather than a re-cut — verified by
 * diffing the manifests, which show exactly one file moving anywhere in the ladder
 * (`engine/medicham2-browser.js`; the other 22 frozen files are byte-identical across all ten
 * releases). Excluding them would silently attribute their effect to the named wire that follows,
 * which is the same misattribution WIRE 5 was written to stop.
 */
'use strict';
require('./showdown_path.js');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const D = (...p) => path.join(__dirname, '..', ...p);
const ER = require('./engine_release.js');
const CMP = require('./arms_comparable.js');
const RS = require('./run_stamp.js');

const argv = process.argv.slice(2);
const flag = (n, d) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : d; };
const GAMES = +flag('--games', 2700);
const WRITE = argv.includes('--write');
const CENSUS = flag('--census', 'data/wire-ladder-census.pin.json');
const KEEP = flag('--keep-arms', null);

if (!process.env.SHOWDOWN_PATH) {
  console.error('NOT RUN — the official simulator is absent. Set SHOWDOWN_PATH. This is not a pass.');
  process.exit(2);
}

/* THE RUNGS, IN THE ORDER THEY WERE CUT. `cut` is read from each release's own manifest rather than
 * typed here, so the chronology cannot be got wrong by hand. */
const ARMS = [
  { id: 'a01-baseline-run1', release: 'cf6a68fa412c', label: 'pre-WIRE-1 baseline',
    change: 'the engine as it stood before any of the night\'s wires' },
  { id: 'a02-mega-speed-order', release: '28e66a7c9ab8', label: 'INTERMEDIATE — mega resolution order',
    change: 'two megas in one turn resolve in SPEED order alone; megaEvo actions carry no priority, so '
          + 'a slow body clicking Protect (+4) had been megaing before a fast body clicking an attack',
    included_because: 'a real engine change between the baseline cut and WIRE 1. Folding it into WIRE 1 '
          + 'would credit WIRE 1 with an ordering fix it did not make.' },
  { id: 'a03-knockoff-bp-trunc', release: '0771dc47b5f6', label: 'INTERMEDIATE — Knock Off base power truncated',
    change: 'targetHasItem x1.5 is chainModify and therefore FIXED POINT: 65 x 1.5 is 97, not 97.5',
    included_because: 'a real engine change, and the ladder is the only place its whole-game effect '
          + 'can be seen at all — it is the smallest rung here and that is a result.' },
  { id: 'a04-wire1', release: '41e28311e591', label: 'WIRE 1',
    change: 'Protect is not an immunity: the shield preempts the accuracy roll, and a shielded High '
          + 'Jump Kick still pays its crash through onMoveFail' },
  { id: 'a05-wire2', release: '6b6f898f136f', label: 'WIRE 2',
    change: 'the stall counter resets on failure; a shield moving last fails' },
  { id: 'a06-wire3', release: '128a1ca28d34', label: 'WIRE 3',
    change: 'refused stat drops — scoped refusal, and they were being over-refused' },
  { id: 'a07-wire4-fixedpoint-only', release: '1e29ff6c431b', label: 'INTERMEDIATE — WIRE 4 first half',
    change: 'every damage multiplier in fixed point on 4096ths (md4096 / ch4096), Showdown\'s own '
          + 'round-half-up rather than a float truncation',
    included_because: 'WIRE 4 shipped as one wire and is two independent arithmetic fixes. Split, the '
          + 'ladder says what each half was worth; merged, it says only what the pair was worth.' },
  { id: 'a08-wire4', release: '45485dee6a43', label: 'WIRE 4 (complete)',
    change: '+ recoil is Math.round clamped to >= 1 on the RATIO, and drain is rounded not floored' },
  { id: 'a09-wire6', release: '3fd06d865427', label: 'WIRE 6',
    change: 'two of 27 action kinds announced nothing; four priority brackets wrong' },
  { id: 'a10-wire7', release: '0aa54cb1a9de', label: 'WIRE 7',
    change: 'six absent-or-misordered mechanics in one batch: Hospitality announces nothing onto a '
          + 'full-HP partner and never an -ability; Knock Off strips AFTER the damage and cannot take '
          + 'a mega stone; the pinch and status berries are onUpdate rather than residual; the '
          + 'substitute doll is ceil(maxhp/4) and its -start precedes the -damage; Protean converts '
          + 'before the hit so the move gets its STAB; a move redirect announces nothing and an '
          + 'ability redirect announces an -activate' },
  { id: 'a11-wire8', release: 'dd3da7c69cb0', label: 'WIRE 8',
    change: 'two families. A side condition that is already up is NOT re-set — Showdown\'s '
          + 'addSideCondition returns false and the move fails, where this engine wrote a second '
          + '-sidestart and reset the clock, so a Tailwind or a screen re-clicked each turn was '
          + 'permanent; screens are now three named conditions rather than two counters keyed by '
          + 'damage category, so each expires under its own name. And the two-turn wind-up happens '
          + 'even when the charge is skipped: |-prepare| is written first and unconditionally, and '
          + 'the charge-turn stat boost is taken — a rain Electro Shot was firing with no +1 SpA' },
  { id: 'a12-wire9', release: '86048ca3a422', label: 'WIRE 9',
    change: 'ROADMAP #81 WIRE 9 + ROADMAP #84. A SPREAD move carries no target on Showdown\'s own '
          + 'request, and playerAction\'s damaging branch was gated on having one — so every '
          + 'allAdjacentFoes / allAdjacent click from a driver reading the authority fell through to '
          + 'the status chain and became a no-op turn (33 legal moves, 56,524 corpus uses, dealing '
          + 'ZERO). It now aims off the board; a single-target click with the target withheld is '
          + 'still refused, and counted. The accuracy miss writes one |-miss| PER TARGET, each naming '
          + 'the body it missed, instead of one line with an empty target field. And the move RESULT '
          + 'is now stored and split three ways as Showdown stores it — false (flinch, paralysis, '
          + 'sleep, freeze, Taunt, Throat Chop, a miss, a type immunity), null (recharge, a fully '
          + 'shielded move) and true — so Stomping Tantrum and Temper Flare double after a failure '
          + 'and NOT after a recharge. Two things the family reached only once it started resolving are fixed in the same pass: Wide Guard NAMES each body it shielded (it wrote one line with an empty body field), and a quake resolves against your own partner FIRST, which is getMoveTargets\'s own allies-then-foes order' },
  { id: 'a13-wire10', release: 'dc3c43336539', label: 'WIRE 10',
    change: 'ROADMAP #81 WIRE 10 — THE SHAPE, NOT A MECHANIC. Showdown resolves a move as a STEP LIST '
          + 'over the whole target array: trySpreadMoveHit runs eight steps and each one walks every '
          + 'target before the next begins, and spreadMoveHit numbers six more inside the last. This '
          + 'engine ran ONE loop over the targets with the whole move inside it, so every effectiveness '
          + 'line, damage line, secondary and faint for target A was written before target B was even '
          + 'priced. The loop is now `for (step) for (target)`; the blocks did not move and the ORDER is '
          + 'data. Two consequences beyond the stream: the accuracy roll was step 0 here and is step 4 '
          + 'in the authority, so an immune body was announced as a MISS rather than as -immune whenever '
          + 'the die lost; and a KO scored on the first body of a spread move was handing the attacker '
          + 'its Beast Boost before the second body was priced, which is HP and not a protocol line. '
          + 'Single-target output is unchanged by construction — at one target the two loop orders are '
          + 'the same permutation, and 36/36 staged single-target clicks are byte-identical.' },
  { id: 'a14-baseline-run2', release: 'cf6a68fa412c', label: 'pre-WIRE-1 baseline, REPEATED',
    change: 'the same frozen bytes as a01, run last with ten arms in between — the drift check' },
];
/* WIRE 5 HAS NO RUNG AND THAT IS CORRECT. It changed the INSTRUMENT (engine/steering.js,
 * engine/arms_comparable.js), not the engine, so it cut no release and there is nothing to play. */

/* ---- THE INPUTS, DIGESTED BEFORE AND AFTER --------------------------------------------------------
 * `arms_comparable.js` names three things its own check cannot see. Two of them are files on this
 * machine, so they are digested here rather than left on a list: a ladder taken across ten runs has
 * ten chances for one of them to move. The third — an uncommitted edit inside SHOWDOWN_PATH — is still
 * outside anything this repository can observe, and is stated rather than implied. */
const WATCHED = [
  'data/games.bo3.jsonl', 'data/games.ots.jsonl', 'data/mechanics-census.json', CENSUS,
  'data/protocol-events.json', 'data/tags.json', 'data/engine-data.js',
  'engine/game_differential.js', 'engine/steering.js', 'engine/diff_swarm.js', 'engine/champions_sim.js',
];
const stampInputs = () => {
  const o = {};
  for (const f of WATCHED) {
    try { const s = fs.statSync(D(f)); o[f] = { size: s.size, sha12: ER.sha12(D(f)) }; }
    catch (e) { o[f] = { error: String((e && e.message) || e) }; }
  }
  return o;
};

const ARM_DIR = KEEP ? path.resolve(KEEP) : fs.mkdtempSync(path.join(require('os').tmpdir(), 'abra-wire-ladder-'));
fs.mkdirSync(ARM_DIR, { recursive: true });

/* ---- ONE ARM --------------------------------------------------------------------------------------
 * `--verbose --write` in the SAME invocation: the depth distribution parsed from stdout and the
 * artifact on disk are then the same run. A run that threw is a REFUSAL — a ladder missing a rung is
 * not a ladder, and continuing past it would publish a table with a silent hole in it. */
function runArm(arm) {
  const out = path.join(ARM_DIR, arm.id + '.json');
  const args = ['engine/game_differential.js', '--release', arm.release, '--census', CENSUS,
                '--games', String(GAMES), '--verbose', '--write', '--out', out];
  const t0 = Date.now();
  let stdout;
  try {
    stdout = execFileSync(process.execPath, args, { cwd: D(), encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
  } catch (e) {
    console.error('ARM ' + arm.id + ' (release ' + arm.release + ') DID NOT COMPLETE — the ladder is '
      + 'incomplete and is not written.\n' + String((e && e.stderr) || (e && e.message) || e).slice(0, 4000));
    process.exit(4);
  }
  fs.writeFileSync(path.join(ARM_DIR, arm.id + '.log'), stdout);
  /* THE PER-GAME DEPTH, READ OFF THE DRIVER'S OWN VERBOSE LINE. `null` is a game that agreed all the
   * way through — kept as null and never as a large number, because "never diverged" and "diverged
   * late" are different events and a sentinel would let them average together. */
  const depth = [];
  for (const l of stdout.split(/\r?\n/)) {
    const m = /DIVERGES at line (\d+)/.exec(l);
    if (m) { depth.push(+m[1]); continue; }
    if (/agrees, \d+ turns/.test(l)) depth.push(null);
  }
  const j = JSON.parse(fs.readFileSync(out, 'utf8'));
  if (depth.length !== j.games) {
    console.error('ARM ' + arm.id + ': the verbose stream carries ' + depth.length + ' games and the '
      + 'artifact says ' + j.games + '. They are the same run, so they must agree — refusing.');
    process.exit(4);
  }
  return { artifact: j, depth, wall_s: +((Date.now() - t0) / 1000).toFixed(1), path: out };
}

/* ---- SUMMARY STATISTICS, ONE IMPLEMENTATION ------------------------------------------------------ */
const finite = v => v.filter(x => x != null);
const quant = (v, p) => { const s = finite(v).slice().sort((a, b) => a - b);
                          return s.length ? s[Math.min(s.length - 1, Math.floor(s.length * p))] : null; };
const mean = v => { const s = finite(v); return s.length ? +(s.reduce((a, b) => a + b, 0) / s.length).toFixed(2) : null; };
/* PAIRED, over the same games in the same order — the two arms played the identical sample, so this
 * is a paired comparison and not two independent rates. A game that never diverged is ranked deepest;
 * that is an ORDER statement (it parted later than any game that parted) and not an imputed value, so
 * it is used for the counts and excluded from the means above. */
function paired(a, b) {
  let later = 0, earlier = 0, same = 0;
  const deltas = [];
  for (let i = 0; i < a.length; i++) {
    const x = a[i] == null ? Infinity : a[i], y = b[i] == null ? Infinity : b[i];
    if (y > x) later++; else if (y < x) earlier++; else same++;
    if (a[i] != null && b[i] != null) deltas.push(b[i] - a[i]);
  }
  deltas.sort((p, q) => p - q);
  return { n: a.length, parted_later: later, parted_earlier: earlier, parted_at_the_same_line: same,
           net_later: later - earlier,
           median_delta_lines: deltas.length ? deltas[Math.floor(deltas.length / 2)] : null };
}
const classGames = (j, c) => { const x = j.classes.find(y => y.cls === c); return x ? x.games : 0; };
const classCauses = (j, c) => { const x = j.classes.find(y => y.cls === c); return x ? x.causes.length : 0; };
const totalCauses = j => j.classes.reduce((a, c) => a + c.causes.length, 0);

/* ---- RUN ------------------------------------------------------------------------------------------ */
const inputs_before = stampInputs();
console.log('\nTHE RELEASE LADDER — ' + ARMS.length + ' arms, ' + GAMES + ' games requested each, census pinned to '
  + CENSUS + ' (' + (inputs_before[CENSUS] || {}).sha12 + ')\n');

const RUNS = {};
for (const arm of ARMS) {
  const r = runArm(arm);
  RUNS[arm.id] = r;
  console.log('  ' + arm.id.padEnd(28) + arm.release + '   ' + r.artifact.diverged + '/' + r.artifact.games
    + ' diverged   ' + r.wall_s + 's');
}
const inputs_after = stampInputs();
const moved = WATCHED.filter(f => JSON.stringify(inputs_before[f]) !== JSON.stringify(inputs_after[f]));

/* ---- COMPARABILITY, EVERY ARM AGAINST THE BASELINE ------------------------------------------------ */
const BASE = ARMS[0];
/* THE TOP RUNG IS DERIVED, NOT TYPED. `what_remains_at_the_top_rung` below read a hard-coded
 * `'a09-wire6'` and was therefore TWO RUNGS STALE the moment WIRE 7 landed — the surviving-cause list
 * published with WIRE 7 was WIRE 6's, and it still named 251 hospitality rows that WIRE 7 had taken
 * to zero. Found by WIRE 8 while reading its own output. The top rung is the last arm that is NOT the
 * repeated baseline, and the arm it came from is written into the artifact so a stale read cannot
 * happen silently again. */
const TOP = [...ARMS].reverse().find(a => a.release !== BASE.release);
if (!TOP) { console.error('no non-baseline arm — refusing'); process.exit(4); }
const comparability = ARMS.slice(1).map(arm => {
  const r = CMP.compare(RUNS[BASE.id].artifact, RUNS[arm.id].artifact);
  return { arm: arm.id, release: arm.release, ok: r.ok, reasons: r.reasons,
           repeat_of_baseline: RUNS[arm.id].artifact.engine_release === RUNS[BASE.id].artifact.engine_release };
});
const refused = comparability.filter(c => !c.ok);

/* ---- THE DRIFT CHECK: the two baselines --------------------------------------------------------- */
const stripVolatile = (o) => {
  const c = JSON.parse(JSON.stringify(o));
  /* Everything removed here is a fact about WHEN the run happened or WHAT it was compared with, never
   * about what it measured. If any measured field differed the comparison below would say so. */
  for (const k of ['generated', 'elapsed_s', 'baseline_comparability', 'engine_release_cut',
                   'engine_release_cuts', 'steering']) delete c[k];
  return JSON.stringify(c);
};
/* THE TWO BASELINE ARMS ARE DERIVED, exactly as TOP is and for the same reason. These four lines
 * named `a01-baseline-run1` and `a12-baseline-run2` as literals, and WIRE 9 inserting a rung ahead of
 * the repeated baseline renamed the second one — so a typed id would have thrown on a missing key at
 * best, and at worst compared the wrong pair. That is the SAME defect WIRE 8 found in
 * `what_remains_at_the_top_rung`'s hard-coded 'a09-wire6', one function over: a name typed into a
 * generator goes stale the moment the thing it names moves. */
const BASE_ARMS = ARMS.filter(a => a.release === BASE.release);
if (BASE_ARMS.length !== 2) {
  console.error('the drift check needs EXACTLY two arms on the baseline release, found ' + BASE_ARMS.length
    + ' — refusing rather than comparing an arbitrary pair');
  process.exit(4);
}
const [BASE_FIRST, BASE_LAST] = BASE_ARMS;
const baselineReproduces = stripVolatile(RUNS[BASE_FIRST.id].artifact)
                        === stripVolatile(RUNS[BASE_LAST.id].artifact);
const baselineDepthIdentical = JSON.stringify(RUNS[BASE_FIRST.id].depth)
                            === JSON.stringify(RUNS[BASE_LAST.id].depth);

/* ---- THE TABLE ------------------------------------------------------------------------------------ */
const rows = ARMS.map((arm, i) => {
  const j = RUNS[arm.id].artifact, d = RUNS[arm.id].depth;
  const prev = i > 0 ? RUNS[ARMS[i - 1].id].depth : null;
  return {
    arm: arm.id, label: arm.label, release: arm.release,
    release_cut: j.engine_release_cut,
    medicham2_sha12: (j.source_digests || {})['engine/medicham2-browser.js'] || null,
    change: arm.change, included_because: arm.included_because || null,
    diverged: j.diverged, games: j.games, agreed_completely: j.games - j.diverged, threw: j.threw,
    classes: j.classes.length, distinct_causes: totalCauses(j),
    damage_field_3_games: classGames(j, '-damage field 3'),
    damage_field_3_causes: classCauses(j, '-damage field 3'),
    event_missing_from_medicham2_games: classGames(j, 'event missing from medicham2'),
    event_missing_from_medicham2_causes: classCauses(j, 'event missing from medicham2'),
    turn_order_games: classGames(j, 'turn order'),
    distinct_moves_connected: j.coverage.distinct_moves_connected,
    census_rows_exercised_by_a_connected_move: j.coverage.exercised_by_a_connected_move,
    median_completed_turns_before_divergence: j.coverage.median_completed_turns_before_divergence,
    /* THE FINER MEASURE, AND THE REASON IT IS HERE. The turn median has read 1 all night, so it cannot
     * distinguish a rung that helped from one that did not. The PROTOCOL LINE index can. */
    first_divergence_line: { median: quant(d, 0.5), mean: mean(d), p75: quant(d, 0.75), p90: quant(d, 0.9),
                             max: Math.max(...finite(d)) },
    vs_baseline: i === 0 ? null : paired(RUNS[BASE.id].depth, d),
    vs_previous_rung: prev ? paired(prev, d) : null,
    class_counts: Object.fromEntries(j.classes.map(c => [c.cls, c.games])),
    planted_divergence_proof_ok: j.planted_divergence_proof_ok,
    normaliser_all_rules_proved: j.normalisation.all_rules_proved,
    declared_gaps: j.declared_gaps,
    wall_s: RUNS[arm.id].wall_s,
  };
});

const pad = (s, n) => String(s).padEnd(n);
console.log('\n  arm                          div/total   cls  causes  dmgF3  evMiss  moves  medTurn  medLine  meanLine');
for (const r of rows) console.log('  ' + pad(r.arm, 28) + pad(r.diverged + '/' + r.games, 12)
  + pad(r.classes, 5) + pad(r.distinct_causes, 8) + pad(r.damage_field_3_games, 7)
  + pad(r.event_missing_from_medicham2_games, 8) + pad(r.distinct_moves_connected, 7)
  + pad(r.median_completed_turns_before_divergence, 9) + pad(r.first_divergence_line.median, 9)
  + r.first_divergence_line.mean);

console.log('\n  THE BASELINE, RUN TWICE WITH EIGHT ARMS BETWEEN: '
  + (baselineReproduces && baselineDepthIdentical
      ? 'REPRODUCES EXACTLY — every measured field identical, and the per-game divergence depth identical game for game.'
      : 'DOES NOT REPRODUCE. The ladder is uninterpretable and that is the finding.'));
console.log('  COMPARABILITY: ' + (refused.length ? refused.length + ' ARM(S) REFUSED' : 'all '
  + comparability.length + ' arms COMPARABLE with the baseline'));
for (const c of refused) { console.log('    REFUSED ' + c.arm); for (const x of c.reasons) console.log('      - ' + x); }
console.log('  INPUTS UNDER THE LADDER: ' + (moved.length ? 'MOVED — ' + moved.join(', ')
  : 'all ' + WATCHED.length + ' watched files byte-identical before and after'));
console.log('');

if (WRITE) {
  const artifact = {
    generated: new Date().toISOString(), by: 'engine/wire_ladder.js',
    what: 'every frozen release of the 2026-08-06/07 wire night, run through engine/game_differential.js '
        + 'under ONE pinned census and ONE team pool, so all arms are mutually comparable rather than '
        + 'only adjacent. Replaces the retracted pairwise before/afters of CHANGELOG 3.62.1.',
    games_requested: GAMES,
    games_per_arm: rows[0].games,
    /* CONTENT, NOT MTIME. `engine/provenance.js` ratchets down the count of artifacts it can only
     * check by mtime, and a new one that rests on mtime BREAKS that ratchet — which it did on this
     * file's first run, correctly.
     *
     * WHAT IS DELIBERATELY NOT IN HERE: `engine/medicham2-browser.js`. The ladder reads NINE FROZEN
     * COPIES of it out of `data/releases/`, and never the live file. Stamping the live one would mark
     * this artifact UNSAFE the moment ENGINE touches a file it did not read, which is a false alarm of
     * exactly the kind that gets a checker ignored. Each arm carries the frozen digest it actually
     * played, in `arms[].medicham2_sha12`. */
    source_digests: RS.sourceDigests(WATCHED),
    /* THE STARVED CONFIGURATIONS ARE NAMED BY THE ARTIFACT, NOT BY THIS FILE. The first version typed
     * them into the sentence, and `engine/conformance.js` S12b flagged it — correctly, even though it
     * had matched a diff_swarm CONFIG ID rather than a move: a name typed here goes stale the moment
     * the swarm's configuration list changes, which is the whole defect S12 exists to catch. Read off
     * the baseline arm's own `swarm` block, so the sentence describes the run that was played. */
    sample_size_reason: 'the largest sample the swarm sustains before the starved configurations ('
        + (RUNS[BASE.id].artifact.swarm || []).slice().sort((a, b) => a.available - b.available)
            .slice(0, 2).map(s => s.config + ': ' + s.available + ' teams available').join(', ')
        + ') stop contributing marginal games, and '
        + 'small enough that all ten arms finish inside one photograph window. Identical for every arm '
        + 'by construction: only engine/medicham2-browser.js differs across the nine releases, so '
        + 'buildPair reaches the same teams in every arm.',
    /* THE STEERING BLOCK. Read from the baseline arm's own artifact rather than restated, so it cannot
     * disagree with what the runs actually used. */
    steering: RUNS[BASE.id].artifact.steering,
    steering_note: 'PINNED to a durable file checked in beside this artifact. WIRE 6\'s published run '
        + 'pinned the census to a path inside an agent scratchpad, which stops being checkable the '
        + 'moment that session ends.',
    instrument: {
      note: 'engine/arms_comparable.js names three inputs its own check cannot see. Two are files here '
          + 'and are digested before and after every arm; the third is stated and remains outside.',
      showdown_commit: RUNS[BASE.id].artifact.showdown_commit || null,
      still_outside: 'an uncommitted edit inside SHOWDOWN_PATH is invisible to `showdown_commit`.',
      inputs_before, inputs_after, inputs_that_moved: moved,
      nothing_in_frame_moved: moved.length === 0,
    },
    determinism: {
      what: 'the pre-WIRE-1 baseline was run FIRST and LAST with eight arms in between',
      reproduces: baselineReproduces,
      per_game_depth_identical: baselineDepthIdentical,
      verdict: baselineReproduces && baselineDepthIdentical
        ? 'the instrument is deterministic across the whole ladder, so every difference in the table '
          + 'below is the engine change and not the run'
        : 'THE TWO BASELINES DISAGREE. Do not read the table below as a ladder.',
    },
    comparability: { all_ok: !refused.length, per_arm: comparability },
    arms: rows,
    /* WHAT REMAINS, so the ladder ends in something actionable rather than in a score. */
    top_rung: { arm: TOP.id, label: TOP.label, release: TOP.release },
    what_remains_at_the_top_rung: (() => {
      const j = RUNS[TOP.id].artifact;
      return [...j.classes].sort((a, b) => b.games - a.games).slice(0, 6).map(c => ({
        cls: c.cls, games: c.games, distinct_causes: c.causes.length,
        top_causes: [...c.causes].sort((a, b) => b.n - a.n).slice(0, 5).map(x => ({
          n: x.n, cause: x.cause, cannot_occur_in_format: x.cannot_occur_in_format, max_uses: x.max_uses })),
      }));
    })(),
    arm_artifacts: KEEP ? ARM_DIR : 'not kept — re-run this file to regenerate them',
  };
  fs.writeFileSync(D('data', 'wire-ladder.json'), JSON.stringify(artifact, null, 2) + '\n');
  console.log('  -> data/wire-ladder.json');
}

process.exitCode = (refused.length || !baselineReproduces) ? 1 : 0;
