#!/usr/bin/env node
/* tests/probe_lownode_argv.js — ROADMAP #348.
 * ==================================================================================================
 * DOES tools/lownode.cmd DELIVER A SPACED ARGUMENT AND A DRIVE-LETTER PATH TO NODE BYTE FOR BYTE?
 *
 * The wrapper's exit code is proven by tests/test-lownode.js. Its ARGUMENTS are not: the row records a
 * quoted `--why` reason truncated on an engine-release cut, and `start` mis-parsing a spaced argument.
 *
 * THIS FILE IS ITS OWN CHILD. Run with `--child-echo`, it writes the argv it received after that flag
 * to the file named by ABRA_ARGV_OUT and exits 0. So the script path handed to the wrapper is always
 * the repo-relative `tests\probe_lownode_argv.js` — no drive path in the CONTROL — and each arm varies
 * one argument.
 *
 *   ROUTE A  node -> cmd.exe /c tools\lownode.cmd ...   (how tests/test-lownode.js and run-all call it)
 *   ROUTE B  Git Bash -> cmd //c "tools\\lownode.cmd ..." (how an agent types it from the Bash tool)
 *   ARMS     plain (the CONTROL), a spaced `--why` value, a drive path with backslashes, and one with
 *            forward slashes.
 * A route whose CONTROL arm fails is reported CANNOT-ANSWER for that route, not RED — nothing about
 * quoting can be read off a route that cannot pass a plain word.
 *
 * Kills nothing: every child is spawned synchronously with a timeout on the process this file started.
 * EXIT: 0 green / 1 red / 2 cannot answer. Plays no game.
 * ================================================================================================ */
'use strict';
/* A THROW IS NOT A VERDICT: node exits 1 on an uncaught exception, which the register reads as RED. */
process.on('uncaughtException', (e) => { console.log('CANNOT ANSWER — the probe threw: ' + String(e && e.stack || e).split('\n').slice(0, 4).join(' | ')); console.log('ABRA-EXIT 2 CANNOT-ANSWER'); process.exit(2); });
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ci = process.argv.indexOf('--child-echo');
if (ci >= 0) { fs.writeFileSync(process.env.ABRA_ARGV_OUT, JSON.stringify(process.argv.slice(ci + 1))); process.exit(0); }

const ROOT = path.join(__dirname, '..');
const cannot = (why) => { console.log('CANNOT ANSWER — ' + why); console.log('ABRA-EXIT 2 CANNOT-ANSWER'); process.exit(2); };
if (process.platform !== 'win32') cannot('tools/lownode.cmd is a Windows batch file and this is ' + process.platform);
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'abra-348-'));
const CHILD = 'tests\\probe_lownode_argv.js';
const ARMS = [
  { id: 'plain (CONTROL)', args: ['alpha'] },
  { id: 'spaced --why', args: ['--why', 'a vs b'] },
  { id: 'drive path, backslashes', args: ['C:\\Users\\willj\\x.json'] },
  { id: 'drive path, forward slashes', args: ['C:/Users/willj/x.json'] },
];
let seq = 0;
function viaCmd(args) {
  const out = path.join(TMP, 'a' + (seq++) + '.json');
  const r = spawnSync('cmd.exe', ['/c', 'tools\\lownode.cmd', CHILD, '--child-echo', ...args],
    { cwd: ROOT, env: { ...process.env, ABRA_ARGV_OUT: out }, encoding: 'utf8', timeout: 60000 });
  return { got: fs.existsSync(out) ? JSON.parse(fs.readFileSync(out, 'utf8')) : null, status: r.status, err: (r.stderr || '').trim().slice(0, 160) };
}
/* THE BASH ROUTES ARE TYPED THE WAY AN AGENT TYPES THEM, one spelling per arm, and never generated by
 * an escaping function — the first form of this probe ran every argument through a quoting helper,
 * so its CONTROL arrived as `"alpha"` with the quotes attached and the route read CANNOT-ANSWER on
 * the instrument's own quoting. Each arm below is the literal Bash text (JS-escaped once).
 *   ROUTE B  the whole command inside one double-quoted string:  cmd //c "tools\\lownode.cmd ... <arg>"
 *   ROUTE C  the arguments as separate Bash words:               cmd //c tools\\lownode.cmd ... <arg>  */
const TYPED = {
  B: ['alpha', '--why \\"a vs b\\"', 'C:\\\\Users\\\\willj\\\\x.json', 'C:/Users/willj/x.json'],
  C: ['alpha', '--why "a vs b"', "'C:\\Users\\willj\\x.json'", 'C:/Users/willj/x.json'],
};
function viaBashWith(route) {
  let i = 0;
  return (args) => {
    const typed = TYPED[route][ARMS.findIndex(a => a.args === args)];
    const out = path.join(TMP, route + (seq++) + '.json');
    const line = route === 'B'
      ? 'cmd //c "tools\\\\lownode.cmd tests\\\\probe_lownode_argv.js --child-echo ' + typed + '"'
      : 'cmd //c "tools\\\\lownode.cmd" "tests\\\\probe_lownode_argv.js" --child-echo ' + typed;
    void i;
    const r = spawnSync('bash', ['-c', line], { cwd: ROOT, env: { ...process.env, ABRA_ARGV_OUT: out }, encoding: 'utf8', timeout: 60000 });
    if (r.error) return { unavailable: String(r.error.message || r.error) };
    return { got: fs.existsSync(out) ? JSON.parse(fs.readFileSync(out, 'utf8')) : null, status: r.status, line, err: (r.stderr || '').trim().slice(0, 160) };
  };
}

console.log('\ntests/probe_lownode_argv.js — ROADMAP #348');
let bad = 0, answered = 0;
const ok = (cond, what, detail) => {
  console.log('  ' + (cond ? 'ok  ' : 'FAIL') + '  ' + what);
  if (detail) console.log('          ' + String(detail).split('\n').join('\n          '));
  if (!cond) bad++;
};
for (const [route, fn] of [['ROUTE A  node -> cmd.exe /c', viaCmd],
                           ['ROUTE B  Git Bash -> cmd //c "one string"', viaBashWith('B')],
                           ['ROUTE C  Git Bash -> cmd //c separate words', viaBashWith('C')]]) {
  console.log('\n  ' + route);
  const ctl = fn(ARMS[0].args);
  if (ctl.unavailable) { console.log('      not run: ' + ctl.unavailable); continue; }
  const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
  if (!same(ctl.got, ARMS[0].args)) {
    console.log('      CANNOT ANSWER for this route — the control did not arrive: got ' + JSON.stringify(ctl.got)
      + ' exit ' + ctl.status + (ctl.err ? ' stderr ' + ctl.err : ''));
    continue;
  }
  answered++;
  ok(true, ARMS[0].id + ' -> ' + JSON.stringify(ctl.got));
  for (const a of ARMS.slice(1)) {
    const r = fn(a.args);
    ok(same(r.got, a.args), a.id + ' arrives byte for byte',
       same(r.got, a.args) ? null : 'cell: ' + route.split('  ')[0] + ' / ' + a.id + ': sent ' + JSON.stringify(a.args)
         + ', node received ' + (r.got ? JSON.stringify(r.got) : 'NOTHING (the child never ran)') + ', exit ' + r.status
         + (r.line ? '\n  typed: ' + r.line : '') + (r.err ? '\n  stderr: ' + r.err : ''));
  }
}
try { fs.rmSync(TMP, { recursive: true, force: true }); } catch (e) { console.log('  (temp dir left at ' + TMP + ')'); }
if (!answered) cannot('no route passed its control arm');
console.log('\n' + (bad ? 'RED' : 'GREEN'));
console.log('ABRA-EXIT ' + (bad ? '1 VERDICT-RED' : '0 VERDICT-GREEN'));
process.exit(bad ? 1 : 0);
