/* solver/meta/report.js — renders docs/_reports/2026-09-23-regmc-meta.md from solver/out/meta/*.json.
 * Every figure in the report is read out of those artifacts on this run; none is typed.
 *   node solver/meta/report.js */
'use strict';
const fs = require('fs');
const path = require('path');
const L = require('./lib.js');

const J = f => JSON.parse(fs.readFileSync(path.join(L.OUT, f), 'utf8'));
const man = J('manifest.json'), U = J('usage.json'), S = J('sets.json'), A = J('archetypes.json'), BL = J('bringlead.json'), B3 = J('bo3.json');
const OUTF = path.join(L.ROOT, 'docs', '_reports', '2026-09-23-regmc-meta.md');

const pc = (x, d = 1) => (x == null ? '—' : (100 * x).toFixed(d) + '%');
const ci = c => (c && c[0] != null ? `${pc(c[0])}–${pc(c[1])}` : '—');
const pp = x => (x == null ? '—' : (x >= 0 ? '+' : '') + (100 * x).toFixed(1) + ' pp');
const n = x => (x == null ? '—' : Number(x).toLocaleString('en-US'));
const q = x => (x == null ? '—' : x < 0.001 ? '<0.001' : x.toFixed(3));
const table = (head, rows) => ['| ' + head.join(' | ') + ' |', '|' + head.map(() => '---').join('|') + '|', ...rows.map(r => '| ' + r.join(' | ') + ' |')].join('\n');
const out = [];
const P = s => out.push(s);

const sp = U.categories.species;
const flagged = cat => U.categories[cat].rows.filter(r => r.trend.flag);
const kRow = A.grid.find(g => g.k === A.k_chosen);
const ruleMet = A.grid.some(g => g.ari_median >= 0.8);
const decWL = B3.summary.by_previous_result;
const arSig = A.archetypes.filter(a => a.win.elo_residual.q != null && a.win.elo_residual.q < 0.05);
const exFirst = man.exclusions.charged_first;
const exTot = Object.values(exFirst).reduce((a, v) => a + v.bo1 + v.bo3, 0);

P('# Reg M-C meta analysis — usage, sets, archetypes, bring/lead, Bo3 adaptation');
P('');
P(`Date: 2026-09-23. Historical findings record under \`docs/_reports/\`; not a living document and not current state.`);
P(`**Generated by \`node solver/meta/report.js\`** from \`solver/out/meta/*.json\`; every figure is read from those artifacts.`);
P(`Store read at ${man.generated} (manifest \`solver/out/meta/manifest.json\`). Open team sheets only. No win predictor from sheets.`);
P('');
P('## 0. Verdict');
P('');
P(`1. **Population:** ${n(man.kept.total)} clean open-sheet games (${n(man.kept.bo3)} bo3, ${n(man.kept.bo1)} bo1), ${n(U.totals.players)} players, ${man.kept.first_date} → ${man.kept.last_date} UTC. ${n(exTot)} of ${n(man.games.distinct_ids)} store games excluded, ${n(exFirst.closed_sheet.bo1)} of them closed-sheet bo1. Legality was read from the M-C checkout (\`${path.basename(man.checkout.dir)}\` @ \`${(man.checkout.head || '').slice(0, 10)}\`, ${man.checkout_matches_pin ? 'equal to' : 'NOT equal to'} the pin); every kept game passes it.`);
P(`2. **Usage moves fast and the intervals are wide.** Games cluster heavily by player (design effect on species shares ~${Math.round(median(sp.rows.slice(0, 30).map(r => r.design_effect)))}×), so a Wilson interval on game counts understates the uncertainty by ~${Math.sqrt(median(sp.rows.slice(0, 30).map(r => r.design_effect))).toFixed(1)}×. Even so, first week vs last week flags ${sp.risers} species risers and ${sp.fallers} fallers at BH q<0.05.`);
P(`3. **Archetypes: ${ruleMet ? 'k=' + A.k_chosen + ' met the pre-set stability bar' : 'no k met the pre-set stability bar'}** (median bootstrap ARI ≥ 0.80). ${ruleMet ? '' : `The fallback took the most stable k, **k=${A.k_chosen}** (median ARI ${kRow.ari_median}); ${kRow.clusters_jaccard_ge_075} of ${A.k_chosen} clusters are individually stable (Jaccard ≥ 0.75). `}Archetype win rates sit within a few points of 50%; after the Elo correction and BH, ${arSig.length} of ${A.archetypes.length} archetypes differ from their pilots' expectation.`);
P(`4. **Bo3 adaptation is large and result-driven:** the same four is brought again ${pc(decWL.won.same_four.rate)} of the time after a win and ${pc(decWL.lost.same_four.rate)} after a loss (win minus loss ${pp(-decWL.same_four.lost_minus_won)}, cluster 95% ${pp(-decWL.same_four.ci[1])} to ${pp(-decWL.same_four.ci[0])}). Sheets never change within a series (${n(B3.series.sheet_changed_within_series)} of ${n(B3.series.player_series_with_2plus_games)}).`);
P(`5. **Stat Points are not in the store** (evs null on every slot), so the set library has no spreads.`);
P('');
P('Paths: code `solver/meta/`, test `solver/tests/test-meta-lib.js`, artifacts `solver/out/meta/` (`manifest.json`, `games.clean.jsonl.gz`, `usage.json`, `sets.json`, `archetypes.json`, `bringlead.json`, `bo3.json`).');
P('');

/* ---- 1 ---- */
P('## 1. Population, provenance and legality');
P('');
P('### 1.1 What was read');
P('');
P(`The two stores are appended hourly. Each was digested **before** it was read and re-stat'ed after; files that moved during the read: ${man.stores_moved_during_read.length ? man.stores_moved_during_read.join(', ') : 'none'}.`);
P('The `.gz` copy (tracked, newer) was read first and the plain `.jsonl` second; first occurrence of an id wins, which is the store\'s own reconcile rule (`engine/next_regulation_ingest.js`).');
P('');
P(table(['file', 'bytes', 'mtime (UTC)', 'sha256', 'rows', 'new ids'], man.inputs.filter(i => i.role.startsWith('store:')).map(i => {
  const r = man.store_reads.find(x => x.path === i.path) || {};
  return ['`' + i.path + '`', n(i.bytes), i.mtime.slice(0, 16), '`' + i.sha256.slice(0, 16) + '`', n(r.rows), n(r.added)];
})));
P('');
const raws = man.inputs.filter(i => i.role.startsWith('raw:'));
P(`Raw logs: ${n(raws.length)} files (${n(raws.reduce((a, i) => a + i.bytes, 0))} bytes; each file's sha256 is in the manifest), ${n(man.raw.rows)} rows, ${n(man.raw.distinct_ids)} distinct ids. They supply what the parsed store drops: the custom-rule infobox, the \`|rated|\` flag, and the Bo3 series link and game number.`);
P('');
P('### 1.2 Legality — the M-C format, asked of Showdown');
P('');
P(`Checkout \`${man.checkout.dir.replace(/\\/g, '/')}\`, HEAD \`${man.checkout.head}\` (read from \`.git/HEAD\`, no git command), pin in \`data/regulations.json\`: \`${man.checkout.pinned}\`. Formats \`${man.checkout.bo1}\` and \`${man.checkout.bo3}\`.`);
P(`Legal in the format (exists, not isNonstandard, not tier Illegal, not banned by the format's rule table): ${Object.entries(man.legal_counts_in_format).map(([k, v]) => `${n(v)} ${k}`).join(', ')}.`);
P('');
P(table(['kind', 'observed on open sheets', 'illegal', 'illegal entities (slot uses)'], ['species', 'item', 'ability', 'move', 'nature'].map(k => [k, n(man.legality[k].observed), n(man.legality[k].illegal.length), man.legality[k].illegal.map(x => `${x.name} (${x.slot_uses})`).join(', ') || '—'])));
P('');
P(`Mega formes seen in events: ${n(man.legality.mega_forme.observed)}; illegal: ${man.legality.mega_forme.illegal.map(x => x.id + ' (' + x.uses + ')').join(', ') || 'none'} (a closed-sheet game; never in the kept set).`);
P(`TeamValidator on ${n(man.legality.sheets_validated_distinct)} distinct sheets: ${n(man.legality.reconstruction_artifact_sheets)} rejected ONLY on the zero-Stat-Point clause — a reconstruction artifact, because the store keeps no SP — and the real rejections were:`);
P('');
P(table(['validator reason', 'sheets'], man.legality.validator_real_reasons.map(r => [r.reason.replace(/\|/g, '/'), n(r.sheets)])));
P('');
const lateIll = exFirst.illegal_entity.bo1 + exFirst.illegal_entity.bo3 + exFirst.validator_reject.bo1 + exFirst.validator_reject.bo3;
P(`Every game carrying any of these is excluded. ${lateIll === 0 ? 'Every one of them was already charged to an earlier rule (custom room or bot), so legality removed nothing on its own — the corpus-contamination signature, not a gap in the legality read.' : n(lateIll) + ' games were removed by legality alone.'}`);
P('');
P('### 1.3 Exclusions');
P('');
P('Charged in this order; a game is counted once, under its first reason. The overlap column counts every game each rule would catch on its own.');
P('');
P(table(['rule', 'bo1 (first)', 'bo3 (first)', 'bo1 (any)', 'bo3 (any)'], man.exclusions.order.map(r => [r, n(exFirst[r].bo1), n(exFirst[r].bo3), n(man.exclusions.any_overlap[r].bo1), n(man.exclusions.any_overlap[r].bo3)])));
P('');
P(`- **Own accounts** listed: ${man.own_accounts_listed.map(x => '`' + x + '`').join(', ')} (exact id match). Seen: ${Object.entries(man.own_accounts_seen).map(([k, v]) => `${k} ×${v}`).join(', ') || 'none'} — all in closed-sheet games, so they were already out of scope.`);
P(`- **Behavioural bots** (≥${man.behavioural_bots.rule.min_games} games in these stores with exactly one distinct six, the rule in \`data/quality-filter.json\`): ${Object.keys(man.behavioural_bots.accounts).length} accounts. As that file says, the survivors are "no bot detected", not "verified human".`);
P(`- **Custom rules**: ${n(man.custom_rule_strings.reduce((a, r) => a + r.rows, 0))} raw logs carry the infobox (regex \`rules?\`, READ from \`engine/scan_custom_rulesets.js:59\`). Most common strings:`);
P('');
P(table(['rule string', 'raw logs'], man.custom_rule_strings.slice(0, 12).map(r => [r.rules.length > 110 ? r.rules.slice(0, 110) + '…' : r.rules, n(r.rows)])));
P('');
const infoOnly = man.custom_rule_strings.filter(r => /^(\s*(force open team sheets|best of = 3|!?open ?team ?sheets)\s*,?)+$/i.test(r.rules)).reduce((a, r) => a + r.rows, 0);
P(`  ${n(infoOnly)} of these only set Open Team Sheets and/or Best of 3 — the same information regime as the kept games — and were excluded anyway, following the repo's rule that every custom room is out. **Sensitivity:** this is almost all of the bo1 open-sheet population (bo1 kept = ${n(man.kept.bo1)}), and irrelevant to bo3 (${n(exFirst.custom_ruleset.bo3)} games).`);
P(`- **Untestable for custom rules** (no raw log): bo1 ${n(man.kept_but_untestable_for_custom_rules.bo1)}, bo3 ${n(man.kept_but_untestable_for_custom_rules.bo3)} — every kept game was tested.`);
P(`- **Unrated but kept** (no \`|rated|\` line, no infobox — standard-rules challenges): bo1 ${n(man.kept_unrated.bo1)}, bo3 ${n(man.kept_unrated.bo3)}. They are the "unrated" rating band below.`);
P(`- **Not excluded:** the Eject Button conjunction the frozen engine pool applies (\`data/team-pool-frozen-regmc/FROZEN.md\`). It protects SIMULATION against a Showdown rule change; a team choice made under the old rule is still a real team choice.`);
P('');

/* ---- 2 ---- */
P('## 2. Usage over time');
P('');
P(`**Unit:** share of side-games (one player's sheet in one game) whose sheet contains the entity; ${n(U.totals.sides)} side-games. Moves, items and abilities are "share of teams carrying it", not per-slot. **Player share** = share of the ${n(U.totals.players)} players who showed it at least once.`);
P(`**Intervals:** Wilson on side-game counts (as asked), and beside it a cluster-robust interval by player (linearised ratio estimator). The cluster interval is the honest one; the design effect column is the variance ratio between them.`);
P(`**Weeks:** ${U.weeks.map(w => `W${w.week} = ${w.first}…${w.last} (${n(w.sides)} sides)`).join('; ')}. The last week is partial.`);
P(`**Rating bands:** tertiles of rated side-games — low < ${U.rating_bands.cut_points[0]} ≤ mid < ${U.rating_bands.cut_points[1]} ≤ high; unrated separate; top decile ≥ ${U.rating_bands.top_decile_from}. Sides: ${Object.entries(U.rating_bands.sides).map(([k, v]) => `${k} ${n(v)}`).join(', ')}, top decile ${n(U.rating_bands.top_decile_sides)}. The bo3 and bo1 ladders are separate Elo pools; bo1 is ${pc(man.kept.bo1 / man.kept.total)} of games.`);
P(`**Risers/fallers:** period A = ${U.trend_periods.A.join('…')}, period B = ${U.trend_periods.B.join('…')}; ${U.trend_periods.test}.`);
P('');
P('### 2.1 Species (top 30 of ' + sp.entities + ')');
P('');
const usageRow = r => [r.name, pc(r.share), ci(r.wilson), ci(r.cluster_ci), (r.design_effect || 0).toFixed(1), pc(r.player_share), r.by_week.map(w => pc(w.share, 0)).join(' / '), ['low', 'mid', 'high', 'unrated'].map(b => pc(r.by_band[b].share, 0)).join(' / '), pc(r.top_decile.share, 0), pp(r.trend.diff), q(r.trend.q), r.trend.flag || ''];
const UH = ['entity', 'share', 'Wilson 95%', 'cluster 95%', 'deff', 'player share', 'by week', 'low/mid/high/unrated', 'top 10%', 'B−A', 'q', 'flag'];
P(table(UH, sp.rows.slice(0, 30).map(usageRow)));
P('');
P(`Effective number of species (Hill number, exp-entropy of the side-game shares) by week: ${sp.effective_number_by_week.join(' / ')}.`);
P('');
for (const cat of ['item', 'ability', 'move', 'mega_used', 'megastone_carried']) {
  const c = U.categories[cat];
  const top = cat === 'move' ? 25 : 20;
  P(`### 2.${['item', 'ability', 'move', 'mega_used', 'megastone_carried'].indexOf(cat) + 2} ${cat === 'mega_used' ? 'Mega evolution used in the game (`none` = no mega that game)' : cat === 'megastone_carried' ? 'Mega stone carried on the sheet' : cat[0].toUpperCase() + cat.slice(1) + 's'} (top ${top} of ${c.entities})`);
  P('');
  P(table(UH, c.rows.slice(0, top).map(usageRow)));
  P('');
  P(`Effective number by week: ${c.effective_number_by_week.join(' / ')}.`);
  P('');
}
P('### 2.7 Significant risers and fallers (q < 0.05), every category');
P('');
for (const cat of Object.keys(U.categories)) {
  const f = flagged(cat).sort((a, b) => b.trend.diff - a.trend.diff);
  P(`**${cat}** — ${U.categories[cat].tested_for_trend} tested, ${f.filter(r => r.trend.flag === 'RISER').length} risers, ${f.filter(r => r.trend.flag === 'FALLER').length} fallers.`);
  P('');
  if (f.length) P(table(['entity', 'A', 'B', 'B−A', 'cluster SE', 'q', 'player share A→B'], f.map(r => [r.name, pc(r.trend.pA), pc(r.trend.pB), pp(r.trend.diff), pp(r.trend.se), q(r.trend.q), pc(r.trend.player_share_A) + ' → ' + pc(r.trend.player_share_B)])));
  P('');
}

/* ---- 3 ---- */
P('## 3. Set library');
P('');
P(`Unit: one Pokémon slot on one side-game sheet. ${S.set_key}. \`players\` = distinct players who showed that exact set, which is the count to trust — a Bo3 series repeats one sheet up to three times. ${S.spreads}. The full library (every species, marginals and up to 25 sets each) is \`solver/out/meta/sets.json\`; below, the 20 most-used species.`);
P('');
for (const s of S.species.slice(0, 20)) {
  P(`**${s.name}** — ${n(s.slots)} slots, ${n(s.players)} players, ${n(s.distinct_sets)} distinct sets (${n(s.distinct_cores)} ignoring nature). Items: ${s.item.slice(0, 4).map(x => `${x.name} ${pc(x.share, 0)}`).join(', ')}. Abilities: ${s.ability.slice(0, 3).map(x => `${x.name} ${pc(x.share, 0)}`).join(', ')}. Moves: ${s.move.slice(0, 8).map(x => `${x.name} ${pc(x.share, 0)}`).join(', ')}.`);
  P('');
  P(table(['item', 'ability', 'nature', 'moves', 'slots', 'share', 'players'], s.top_sets.slice(0, 3).map(t => [t.item || '—', t.ability || '—', t.nature || '—', t.moves.join(', '), n(t.k), pc(t.share), n(t.players)])));
  P('');
}

/* ---- 4 ---- */
P('## 4. Archetypes');
P('');
P(`**Method.** ${A.method}. ${n(A.points)} points over ${A.vocab} species. Every side-game is then assigned to the nearest centroid of the reference fit.`);
P(`**Choosing k.** ${A.k_rule}. ${A.stability_bands}.`);
P('');
P(table(['k', 'median ARI', 'p10 ARI', 'min ARI', 'clusters Jaccard ≥ 0.75', 'clusters < 0.6'], A.grid.map(g => [g.k === A.k_chosen ? `**${g.k}**` : g.k, g.ari_median, g.ari_p10, g.ari_min, `${g.clusters_jaccard_ge_075}/${g.k}`, g.clusters_jaccard_lt_06])));
P('');
P(ruleMet ? `k* = ${A.k_chosen}.` : `**No k reached median ARI 0.80, so the pre-set rule was not met.** The fallback — the k with the highest median ARI — is **k = ${A.k_chosen}** (${kRow.ari_median}). That is a real peak (it beats both neighbours on median and on stable-cluster count), but it is "moderately stable", not "stable": ${kRow.clusters_jaccard_ge_075} of ${A.k_chosen} clusters clear Jaccard 0.75 and the rest are doubtful. Team space is a continuum with dense cores, and k-means cuts the continuum differently on every resample.`);
P('');
P('**Labels are derived**: the species present on ≥ 50% of the cluster\'s side-games, most frequent first (up to three). Win rate uses decided games (winner known, an action taken, ≥ 3 turns) and excludes mirrors. The Elo residual is observed win minus the Elo expectation from both players\' ladder ratings — it asks whether the archetype wins more than its pilots\' ratings predict. It is a confound correction, not a predictor. q = BH over archetypes.');
P('');
P(table(['#', 'label', 'stability', 'share', 'Wilson', 'by week', 'low/mid/high/unrated', 'players', 'mean rating', 'decided', 'win rate', 'Wilson', 'cluster 95%', 'Elo residual', '95%', 'q'],
  A.archetypes.map(a => [a.id, a.label, `${a.stable} (${a.jaccard_stability.toFixed(2)})`, pc(a.share), ci(a.wilson), a.by_week.map(w => pc(w.share, 0)).join(' / '), Object.values(a.by_band).map(b => pc(b.share, 0)).join(' / '), n(a.players), a.mean_rating, n(a.win.decided_non_mirror), pc(a.win.rate), ci(a.win.wilson), ci(a.win.cluster_ci), pp(a.win.elo_residual.mean), (a.win.elo_residual.ci ? pp(a.win.elo_residual.ci[0]) + ' to ' + pp(a.win.elo_residual.ci[1]) : '—'), q(a.win.elo_residual.q)])));
P('');
P('Cores and mega choice per archetype:');
P('');
for (const a of A.archetypes) P(`- **#${a.id} ${a.label}** — ${a.core.slice(0, 8).map(c => `${c.name} ${pc(c.in_cluster, 0)} (overall ${pc(c.overall, 0)})`).join(', ')}. Mega used: ${a.mega_used.map(m => `${m.name} ${pc(m.share, 0)}`).join(', ')}.`);
P('');
P(`**Reading the win rates — the null first.** ${A.archetypes.length - arSig.length} of ${A.archetypes.length} archetypes are indistinguishable from their pilots' Elo expectation after BH.${arSig.length ? ' The exception' + (arSig.length > 1 ? 's are ' : ' is ') + arSig.map(a => `#${a.id} ${a.label} (${pp(a.win.elo_residual.mean)}, q ${q(a.win.elo_residual.q)})`).join('; ') + '.' : ''} No archetype-vs-archetype matchup matrix is published: the research note's power arithmetic (~784 games per cell for 55% vs 50%) is not met by most of the ${A.k_chosen * A.k_chosen} cells, and the brief excludes a win predictor.`);
P('');

/* ---- 5 ---- */
P('## 5. Bring and lead behaviour');
P('');
P(`**Censoring.** Only revealed Pokémon are known to have been brought. ${n(BL.censoring.full_bring_sides)} of ${n(BL.censoring.sides)} sides revealed all four ("full bring"); leads are known on ${n(BL.censoring.lead_known_sides)}. The bring rate is computed on full-bring sides and the revealed-only lower bound over all sides is printed beside it. ${BL.censoring.note}.`);
P('');
P('### 5.1 Per species (top 30 by sheets; ≥ 30 sheets for the extremes)');
P('');
P(table(['species', 'on sheet', 'bring (full)', 'Wilson', 'bring lower bound', 'lead', 'Wilson', 'lead | brought', 'bring, game 1 only', 'lead, game 1 only'],
  BL.species.slice(0, 30).map(s => [s.name, n(s.on_sheet), pc(s.bring_full.rate), ci(s.bring_full.wilson), pc(s.bring_revealed_lower_bound), pc(s.lead.rate), ci(s.lead.wilson), pc(s.lead_given_brought.rate), pc(s.game1_only.bring), pc(s.game1_only.lead)])));
P('');
const big = BL.species.filter(s => s.on_sheet >= 300);
const byB = big.slice().sort((a, b) => b.bring_full.rate - a.bring_full.rate), byL = big.slice().sort((a, b) => b.lead.rate - a.lead.rate);
P(`Among species on ≥ 300 sheets: most often brought ${byB.slice(0, 5).map(s => `${s.name} ${pc(s.bring_full.rate, 0)}`).join(', ')}; least ${byB.slice(-5).map(s => `${s.name} ${pc(s.bring_full.rate, 0)}`).join(', ')}. Most often led ${byL.slice(0, 5).map(s => `${s.name} ${pc(s.lead.rate, 0)}`).join(', ')}; least ${byL.slice(-5).map(s => `${s.name} ${pc(s.lead.rate, 0)}`).join(', ')}.`);
P('');
P('### 5.2 Per archetype matchup');
P('');
P(`Cell = species S on an archetype-A sheet facing an archetype-B sheet, ≥ ${BL.rule.min_cell} sides; tested only when ≥ ${BL.rule.min_players_to_test} distinct players make up the cell. Test: ${BL.rule.matchup_test}. ${n(BL.matchup_cells)} cells; bring tested ${n(BL.matchup_tests.bring)} (q<0.05: ${n(BL.matchup_tests.bring_q_lt_05)}), lead tested ${n(BL.matchup_tests.lead)} (q<0.05: ${n(BL.matchup_tests.lead_q_lt_05)}). The largest significant deviations (full table in \`bringlead.json\` → \`matchup_all\`):`);
P('');
const archName = id => { const a = A.archetypes.find(x => x.id === id); return `#${id} ${a ? a.label : ''}`; };
const sig = BL.matchup_significant.slice().sort((x, y) => Math.max(Math.abs((y.bring && y.bring.q < 0.05 && y.bring.vs_rest) || 0), Math.abs((y.lead && y.lead.q < 0.05 && y.lead.vs_rest) || 0)) - Math.max(Math.abs((x.bring && x.bring.q < 0.05 && x.bring.vs_rest) || 0), Math.abs((x.lead && x.lead.q < 0.05 && x.lead.vs_rest) || 0)));
P(table(['S on A', 'vs B', 'players', 'bring n', 'bring', 'vs rest', 'q', 'lead n', 'lead', 'vs rest', 'q'], sig.slice(0, 30).map(c => [`${c.name} on ${archName(c.arch)}`, archName(c.vs), n(c.players), n(c.bring && c.bring.n), pc(c.bring && c.bring.rate), pp(c.bring && c.bring.vs_rest), q(c.bring && c.bring.q), n(c.lead && c.lead.n), pc(c.lead && c.lead.rate), pp(c.lead && c.lead.vs_rest), q(c.lead && c.lead.q)])));
P('');

/* ---- 6 ---- */
P('## 6. Bo3 adaptation');
P('');
P(`**Series linkage** comes from the raw log (\`${B3.series.series_key}\`), not from guessing. ${n(B3.series.linked)} series; games of each present in the clean store: ${Object.entries(B3.series.by_length).map(([k, v]) => `${k} game${k === '1' ? '' : 's'}: ${n(v)}`).join(', ')}. ${n(B3.series.player_series_with_2plus_games)} player-series have ≥ 2 games; the six changed within a series in **${n(B3.series.sheet_changed_within_series)}** of them. ${n(B3.transitions)} game-to-game transitions (player's view). Intervals are cluster-robust by player.`);
P('');
const T = B3.summary;
const rr = (lab, x) => [lab, n(x.n), pc(x.rate), ci(x.wilson), ci(x.cluster_ci)];
P(table(['transition', 'n', 'rate', 'Wilson', 'cluster 95%'], [
  rr('same four, any', T.all.same_four), rr('same four, after a WIN', T.by_previous_result.won.same_four), rr('same four, after a LOSS', T.by_previous_result.lost.same_four),
  rr('same lead pair, any', T.all.same_lead_pair), rr('same lead pair, after a WIN', T.by_previous_result.won.same_lead_pair), rr('same lead pair, after a LOSS', T.by_previous_result.lost.same_lead_pair),
  rr('same four, game 1 → 2', T.by_transition.g1_g2.same_four), rr('same four, game 2 → 3', T.by_transition.g2_g3.same_four),
  rr('same lead, game 1 → 2', T.by_transition.g1_g2.same_lead_pair), rr('same lead, game 2 → 3', T.by_transition.g2_g3.same_lead_pair),
  rr('BASELINE same four: game 1 of next series, same six', T.baseline_next_series_game1.same_four), rr('BASELINE same lead: game 1 of next series, same six', T.baseline_next_series_game1.same_lead_pair)]));
P('');
P(`Loss minus win: same four ${pp(T.by_previous_result.same_four.lost_minus_won)} (cluster 95% ${pp(T.by_previous_result.same_four.ci[0])} to ${pp(T.by_previous_result.same_four.ci[1])}); same lead pair ${pp(T.by_previous_result.same_lead_pair.lost_minus_won)} (${pp(T.by_previous_result.same_lead_pair.ci[0])} to ${pp(T.by_previous_result.same_lead_pair.ci[1])}). Of the four brought, the number kept into the next game: after a win ${JSON.stringify(T.by_previous_result.won.kept_of_four.dist)} (mean ${T.by_previous_result.won.kept_of_four.mean_kept}); after a loss ${JSON.stringify(T.by_previous_result.lost.kept_of_four.dist)} (mean ${T.by_previous_result.lost.kept_of_four.mean_kept}). At least two of the four are always kept — that is forced (six on the sheet, four brought), not a behaviour.`);
P('');
P(`**The baseline is the important row.** Against a NEW opponent the same player with the same six repeats the same four only ${pc(T.baseline_next_series_game1.same_four.rate)} of the time. So the bring is opponent-conditioned before any adaptation happens, and within a series — same opponent — even the losers repeat more than the cross-opponent habit (${pc(T.by_previous_result.lost.same_four.rate)} vs ${pc(T.baseline_next_series_game1.same_four.rate)}). "Win-stay, lose-shift" is the shape; the size is the win/loss gap, not the gap to the baseline.`);
P('');
P('### 6.1 Per species: brought in the earlier game vs the later game of the same player-series');
P('');
const spS = B3.species.filter(s => s.q < 0.05);
P(`${n(B3.species.length)} species with ≥ 100 full-bring transitions; ${spS.length} change significantly (BH q<0.05). Top 20 by q:`);
P('');
P(table(['species', 'transitions', 'bring earlier', 'bring later', 'change', 'cluster 95%', 'q', 'in / out', 'after a loss: earlier → later', 'lead earlier → later'], B3.species.slice(0, 20).map(s => [s.name, n(s.transitions), pc(s.bring_earlier), pc(s.bring_later), pp(s.change), s.ci ? `${pp(s.ci[0])} to ${pp(s.ci[1])}` : '—', q(s.q), `${s.swapped_in} / ${s.swapped_out}`, `${pc(s.after_loss.bring_earlier)} → ${pc(s.after_loss.bring_later)} (n ${n(s.after_loss.n)})`, `${pc(s.lead_earlier)} → ${pc(s.lead_later)}`])));
P('');
P('Species-level adaptation is small: players swap one or two slots, and the swaps are spread across many species, so no single species moves much in aggregate. Whether a swap ANSWERS the opponent\'s previous bring needs a counter model and was not attempted.');
P('');

/* ---- 7 ---- */
P('## 7. Limits — what this does not say');
P('');
P('- **Two weeks of data.** "Riser" means period B differs from period A; it is not a trend estimate. The state-space smoother the research note suggests needs more periods than two full weeks.');
P('- **Cluster-robust ≠ fully independent.** Players are clusters; a bo3 series is nested inside a player. Two players in one game share a game-level shock that the player clustering does not absorb for two-sided quantities.');
P('- **Win rate by archetype is observational.** The Elo residual corrects for pilot rating only.');
P('- **Bring rates are censored** (§5). A Pokémon that sat in the back all game is invisible in the lower bound and its side is dropped from the full-bring rate.');
P('- **Archetypes are moderately stable, not stable.** Treat the doubtful clusters as neighbourhoods, not types. Species usage and sets do not depend on the clustering.');
P('- **bo1 is almost absent** after the custom-room exclusion; every table is effectively the bo3 ladder.');
P('- **No spreads.** Not in the store.');
P('');
P('## 8. Reproduce');
P('');
P('```');
P('cmd.exe /c tools\\lownode.cmd solver/meta/extract.js     # reads data/ + the M-C checkout, writes solver/out/meta/manifest.json + games.clean.jsonl.gz');
P('cmd.exe /c tools\\lownode.cmd solver/meta/analyze.js     # verifies the extract digest, writes the five analysis JSONs');
P('node solver/meta/report.js                              # writes this file');
P('node solver/tests/test-meta-lib.js                       # statistics, parsing, legality helpers');
P('```');
P('');
P('A re-run an hour later reads a larger store and is a different sample; compare manifests, not memory. Nothing under `engine/`, `tests/`, `web/` or `data/` was written, and no git command was run against this repository.');

fs.writeFileSync(OUTF, out.join('\n') + '\n');
console.log('wrote ' + L.rel(OUTF) + ' (' + out.length + ' lines)');

function median(a) { const b = a.filter(x => x != null).sort((x, y) => x - y); return b.length ? b[Math.floor(b.length / 2)] : 0; }
