/* web/quarantine-data.js — GENERATED by web/build-quarantine.js. Do not hand-edit.
 *
 * Sets window.ABRA_QUARANTINE. Loaded by web/index.html, web/replay.html, web/scoreboard.html and
 * web/models.html; the identical block is stamped INTO web/stadium.html, which must stay
 * self-contained because a claude.ai artifact blocks a sibling <script src> exactly like a remote
 * one.
 *
 * `held` is every artifact downstream of engine/medicham2-browser.js. `R` is the figures that have been
 * RELEASED — a key is absent while its artifact is withheld, so a page cannot read a stale value
 * out of this file. Nothing in here was computed, rounded or averaged by the WEB division:
 * membership comes from engine/quarantine.js and the values come from web/quarantine-release.json,
 * which was harvested out of the pages by script.
 *
 * Regenerate:  node web/build-quarantine.js
 */
(function (root) {
  var Q = {
    "generated": "2026-08-09T19:49:25.319Z",
    "by": "web/build-quarantine.js",
    "simulator": "engine/medicham2-browser.js",
    "open": false,
    "clauses": [
      {"name":"game differential","ok":false,"why":"1 of 150 comparisons disagree with Showdown — worst: chesnaught woodhammer -> mimikyu (showdown 0-0, medicham 120-130) [read from data/engine-diff.json]"},
      {"name":"deliberate roster / items","ok":false,"why":"0 FIRED-AND-BOARDS-DIFFER, 6 DID-NOT-FIRE [read from data/roster.items.json]"},
      {"name":"deliberate roster / abilities","ok":true,"why":"clean: 82 fired and matched [read from data/roster.abilities.json]"},
      {"name":"deliberate roster / moves","ok":false,"why":"50 FIRED-AND-BOARDS-DIFFER, 27 DID-NOT-FIRE [read from data/roster.moves.json]"}
    ],
    "failing": [
      "game differential",
      "deliberate roster / items",
      "deliberate roster / moves"
    ],
    "n_quarantined": 40,
    "n_artifacts": 160,
    "rule": "CLAUDE.md — EVERYTHING DOWNSTREAM OF MEDICHAM IS WITHHELD UNTIL MEDICHAM IS CORRECT. Will, 2026-08-08: \"all engines that take medicham's output should be regarded as out of date and we should stop referencing them until medicham is up to date and we can rerun them.\"",
    "derivation": "node engine/quarantine.js --graph",
    "held": {
      "data/ab-batch-effect.json": {
        "file": "data/ab-batch-effect.json",
        "because": "its generator engine/mew.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/mew.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/brood.json": {
        "file": "data/brood.json",
        "because": "its generator engine/brood.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/brood.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/censoring-value.json": {
        "file": "data/censoring-value.json",
        "because": "its generator engine/censoring_value.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/censoring_value.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/click-censoring-census.json": {
        "file": "data/click-censoring-census.json",
        "because": "its generator engine/click_census.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/click_census.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/collinearity-audit.json": {
        "file": "data/collinearity-audit.json",
        "because": "its generator engine/collinearity_audit.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/collinearity_audit.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/collinearity-fix.json": {
        "file": "data/collinearity-fix.json",
        "because": "its generator engine/collinearity_fix.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/collinearity_fix.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/collinearity-joint.json": {
        "file": "data/collinearity-joint.json",
        "because": "its generator engine/collinearity_joint.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/collinearity_joint.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/exploit-step-probe-reparam.json": {
        "file": "data/exploit-step-probe-reparam.json",
        "because": "its generator engine/exploit_step_probe.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/exploit_step_probe.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/exploit-step-probe.json": {
        "file": "data/exploit-step-probe.json",
        "because": "its generator engine/exploit_step_probe.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/exploit_step_probe.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/exploitability-machamp.json": {
        "file": "data/exploitability-machamp.json",
        "because": "its generator engine/exploit.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/exploit.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/exploitability-mag.json": {
        "file": "data/exploitability-mag.json",
        "because": "its generator engine/exploit.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/exploit.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/exploitability.json": {
        "file": "data/exploitability.json",
        "because": "its generator engine/exploit.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/exploit.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/feature-audit.json": {
        "file": "data/feature-audit.json",
        "because": "its generator engine/feature_audit.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/feature_audit.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/feature-engine-contrast.json": {
        "file": "data/feature-engine-contrast.json",
        "because": "its generator engine/feature_engine_contrast.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/feature_engine_contrast.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/ladder.json": {
        "file": "data/ladder.json",
        "because": "its generator engine/ladder.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/ladder.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/leaf-engine-contrast.json": {
        "file": "data/leaf-engine-contrast.json",
        "because": "its generator engine/leaf_engine_contrast.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/leaf_engine_contrast.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/leaf-position-contrast.json": {
        "file": "data/leaf-position-contrast.json",
        "because": "its generator engine/leaf_position_contrast.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/leaf_position_contrast.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/lookahead-cost.json": {
        "file": "data/lookahead-cost.json",
        "because": "its generator engine/lookahead_cost.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/lookahead_cost.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/mag.js": {
        "file": "data/mag.js",
        "because": "it reads policy-weights.json, which is quarantined",
        "rerun": "node build/build_mag_data.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/mew.js": {
        "file": "data/mew.js",
        "because": "build/build_mew_bundle.js reads games.selfplay.jsonl — a dump of games MEDICHAM played",
        "rerun": "node build/build_mew_bundle.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/opponent-calibration.json": {
        "file": "data/opponent-calibration.json",
        "because": "its generator engine/opponent_calibration.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/opponent_calibration.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/opponent-recall.json": {
        "file": "data/opponent-recall.json",
        "because": "its generator engine/opponent_recall.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/opponent_recall.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/partial-label-em.json": {
        "file": "data/partial-label-em.json",
        "because": "its generator engine/em_validation.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/em_validation.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/policy-weights-joint-presheet.json": {
        "file": "data/policy-weights-joint-presheet.json",
        "because": "its generator engine/fit_joint.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/fit_joint.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/policy-weights-joint.json": {
        "file": "data/policy-weights-joint.json",
        "because": "its generator engine/fit_joint.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/fit_joint.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/policy-weights.json": {
        "file": "data/policy-weights.json",
        "because": "its generator engine/fit_policy.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/fit_policy.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/quarantine-stamp.json": {
        "file": "data/quarantine-stamp.json",
        "because": "its generator engine/quarantine.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/quarantine.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/recall-at-k.json": {
        "file": "data/recall-at-k.json",
        "because": "its generator engine/recall_at_k.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/recall_at_k.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/redirect-audit.json": {
        "file": "data/redirect-audit.json",
        "because": "its generator engine/redirect_audit.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/redirect_audit.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/rollout-cost.json": {
        "file": "data/rollout-cost.json",
        "because": "its generator engine/rollout_r2.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/rollout_r2.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/rollout-r1-explore-sweep.json": {
        "file": "data/rollout-r1-explore-sweep.json",
        "because": "engine/rollout_explore_sweep.js reads rollout-r1-explore1-rows.jsonl, rollout-r1-rows.jsonl — a dump of games MEDICHAM played",
        "rerun": "node engine/rollout_explore_sweep.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/rollout-r1-explore1.json": {
        "file": "data/rollout-r1-explore1.json",
        "because": "engine/rollout_r1_artifact.js reads rollout-r1-rows.jsonl — a dump of games MEDICHAM played",
        "rerun": "node engine/rollout_r1_artifact.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/rollout-r1.json": {
        "file": "data/rollout-r1.json",
        "because": "engine/rollout_r1_artifact.js reads rollout-r1-rows.jsonl — a dump of games MEDICHAM played",
        "rerun": "node engine/rollout_r1_artifact.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/rollout-r3.json": {
        "file": "data/rollout-r3.json",
        "because": "its generator engine/rollout_r3.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/rollout_r3.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/rollout-r4.json": {
        "file": "data/rollout-r4.json",
        "because": "engine/rollout_r4.js reads games.r4-decided.jsonl — a dump of games MEDICHAM played",
        "rerun": "node engine/rollout_r4.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/scoreboard.js": {
        "file": "data/scoreboard.js",
        "because": "its generator build/build_scoreboard.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node build/build_scoreboard.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/scoreboard.json": {
        "file": "data/scoreboard.json",
        "because": "its generator build/build_scoreboard.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node build/build_scoreboard.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/sheet-channel-value.json": {
        "file": "data/sheet-channel-value.json",
        "because": "its generator engine/sheet_channel_value.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/sheet_channel_value.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/weight-multiplicity.json": {
        "file": "data/weight-multiplicity.json",
        "because": "it reads policy-weights.json, which is quarantined",
        "rerun": "node engine/weight_multiplicity.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      },
      "data/winrate-backtest.json": {
        "file": "data/winrate-backtest.json",
        "because": "its generator engine/backtest_winrate.js is in the play layer (it reaches engine/medicham2-browser.js through require)",
        "rerun": "node engine/backtest_winrate.js",
        "clause": "3 of 4 gate clauses fail (game differential; deliberate roster / items; deliberate roster / moves)"
      }
    },
    "sources": {
      "stadium.ctrl.medicham": "data/winrate-backtest.json",
      "stadium.ctrl.mag": "data/policy-weights.json",
      "stadium.ctrl.miltank": "data/rollout-r4.json",
      "stadium.ctrl.miltank#rollout-r3": "data/rollout-r3.json",
      "stadium.ctrl.doduo": "data/policy-weights-joint.json",
      "stadium.ctrl.wobbuffet": "data/exploitability.json",
      "stadium.ctrl.wobbuffet#policy-weights": "data/policy-weights.json",
      "stadium.ctrl.machamp": "data/ladder.json",
      "stadium.ctrl.machamp#policy-weights": "data/policy-weights.json",
      "stadium.ctrl.ditto": "data/winrate-backtest.json",
      "stadium.text.medicham.honest": "data/winrate-backtest.json",
      "stadium.text.mag.job": "data/policy-weights.json",
      "stadium.stat.mag.Features": "data/policy-weights.json",
      "stadium.stat.mag.Decisions fitted": "data/policy-weights.json",
      "stadium.stat.miltank.Beats MAG greedy": "data/rollout-r4.json",
      "stadium.stat.miltank.Corpus": "data/rollout-r4.json",
      "stadium.stat.miltank.Splits discarded": "data/rollout-r4.json",
      "stadium.stat.miltank.Divergence from MAG": "data/rollout-r3.json",
      "stadium.text.miltank.honest": "data/rollout-r4.json",
      "stadium.stat.doduo.Coordination features": "data/policy-weights-joint.json",
      "stadium.stat.doduo.Predicting the human PAIR": "data/policy-weights-joint.json",
      "stadium.text.doduo.honest": "data/policy-weights-joint.json",
      "stadium.stat.wobbuffet.Beat MAG, current build": "data/exploitability.json",
      "stadium.stat.wobbuffet.Vector then / now": "data/exploitability.json",
      "stadium.stat.wobbuffet.Rounds run": "data/exploitability.json",
      "stadium.text.wobbuffet.honest": "data/exploitability.json",
      "stadium.stat.machamp.Generations run": "data/ladder.json",
      "stadium.stat.machamp.Vector then / now": "data/policy-weights.json",
      "stadium.stat.mew.Mirror symmetry": "data/exploitability.json",
      "models.machamp.gens": "data/ladder.json",
      "models.machamp.vector": "data/policy-weights.json",
      "models.miltank.leaf": "data/winrate-backtest.json",
      "index.jolteon.winrate": "data/winrate-backtest.json"
    },
    "withheld_keys": [
      "index.jolteon.winrate",
      "models.machamp.gens",
      "models.machamp.vector",
      "models.miltank.leaf",
      "stadium.ctrl.ditto",
      "stadium.ctrl.doduo",
      "stadium.ctrl.machamp",
      "stadium.ctrl.machamp#policy-weights",
      "stadium.ctrl.mag",
      "stadium.ctrl.medicham",
      "stadium.ctrl.miltank",
      "stadium.ctrl.miltank#rollout-r3",
      "stadium.ctrl.wobbuffet",
      "stadium.ctrl.wobbuffet#policy-weights",
      "stadium.stat.doduo.Coordination features",
      "stadium.stat.doduo.Predicting the human PAIR",
      "stadium.stat.machamp.Generations run",
      "stadium.stat.machamp.Vector then / now",
      "stadium.stat.mag.Decisions fitted",
      "stadium.stat.mag.Features",
      "stadium.stat.mew.Mirror symmetry",
      "stadium.stat.miltank.Beats MAG greedy",
      "stadium.stat.miltank.Corpus",
      "stadium.stat.miltank.Divergence from MAG",
      "stadium.stat.miltank.Splits discarded",
      "stadium.stat.wobbuffet.Beat MAG, current build",
      "stadium.stat.wobbuffet.Rounds run",
      "stadium.stat.wobbuffet.Vector then / now",
      "stadium.text.doduo.honest",
      "stadium.text.mag.job",
      "stadium.text.medicham.honest",
      "stadium.text.miltank.honest",
      "stadium.text.wobbuffet.honest"
    ],
    "R": {}
  };

  /* ---- the one question every page asks ------------------------------------------------------
     Returns null when the figure may be shown, and the reason record when it may not. It answers
     "no" whenever the gate is OPEN, so a page needs no second branch for the healthy case. */
  Q.heldFor = function (p) {
    if (Q.open !== false) return null;
    var k = String(p).replace(/^\.\.\//, '');
    if (k.indexOf('data/') !== 0) k = 'data/' + k;
    return Q.held[k] || null;
  };
  /* A RELEASED figure. Absent while its artifact is withheld — the key is not in the payload at all,
     so a page cannot accidentally read a stale value out of it. */
  Q.rel = function (k) { return (Q.R && Q.R[k]) || null; };

  Q.esc = function (s) { return String(s).replace(/[&<>]/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]; }); };

  /* ---- THE PLATE. Full visual weight, never a footnote. --------------------------------------
     docs/WEB.md: a missing measurement is rendered at the same weight as a real one, and
     engine/quarantine.js: "a caption is not a quarantine". This is the caption's replacement — the
     number is gone and its whole space is given to why it is gone and what brings it back. */
  Q.plate = function (p, o) {
    var h = Q.heldFor(p); if (!h) return '';
    o = o || {};
    var dark = o.theme === 'dark';
    var bg = dark ? '#2a0f0c' : '#fff5f3', fg = dark ? '#ffe2dc' : '#5b2a20',
        line = dark ? '#ff6b57' : '#ff6b57', hd = dark ? '#ff9c8f' : '#c0432f';
    return '<div class="qplate" data-q="' + Q.esc(h.file) + '" role="note" style="background:' + bg +
      ';border:2px solid ' + line + ';border-left:7px solid ' + line + ';border-radius:12px;padding:14px 16px;margin:12px 0;color:' + fg + '">' +
      '<div style="font-size:11px;letter-spacing:.14em;font-weight:800;color:' + hd + '">QUARANTINED — THE FIGURE IS WITHHELD, NOT ANNOTATED</div>' +
      (o.subject ? '<div style="font-size:15px;font-weight:800;margin-top:6px">' + Q.esc(o.subject) + '</div>' : '') +
      '<p style="margin:8px 0 0;font-size:12.5px;line-height:1.6;max-width:70ch"><b>' + Q.esc(h.file) + '</b> is downstream of ' +
        Q.esc(Q.simulator) + ' — ' + Q.esc(h.because) + '.</p>' +
      '<p style="margin:6px 0 0;font-size:12.5px;line-height:1.6;max-width:70ch">' + Q.esc(h.clause) + '. ' +
        'A quarantined number does not become true when MEDICHAM becomes correct; it becomes re-runnable.</p>' +
      (h.rerun ? '<p style="margin:6px 0 0;font-size:12.5px">Re-run it: <code style="background:' + (dark ? '#120504' : '#20344a') +
        ';color:#e6ecf8;padding:2px 7px;border-radius:5px">' + Q.esc(h.rerun) + '</code></p>' : '') +
      '<p style="margin:8px 0 0;font-size:11.5px;opacity:.8;max-width:70ch">Derivation: <code>' + Q.esc(Q.derivation) +
        '</code>. Nothing here is a list somebody maintains — the withheld set falls out of one root.</p>' +
      '</div>';
  };

  /* ---- THE CHIP. What a withheld figure looks like INSIDE a sentence. ------------------------- */
  Q.chip = function (p) {
    var h = Q.heldFor(p); if (!h) return '';
    return '<span class="qchip" data-q="' + Q.esc(h.file) + '" title="' + Q.esc(h.file + ' — ' + h.because + '. ' + h.clause) +
      '" style="display:inline-block;background:#ff6b57;color:#fff;font-weight:800;font-size:11px;letter-spacing:.08em;' +
      'padding:1px 7px;border-radius:5px;white-space:nowrap">QUARANTINED</span>';
  };

  root.ABRA_QUARANTINE = Q;
})(typeof window !== 'undefined' ? window : this);
