/* web/quarantine-data.js — GENERATED by web/build-quarantine.js. Do not hand-edit.
 *
 * Sets window.ABRA_QUARANTINE. Loaded by web/index.html, web/replay.html, web/scoreboard.html and
 * web/models.html; the identical block is stamped INTO web/stadium.html, which must stay
 * self-contained because a claude.ai artifact blocks a sibling <script src> exactly like a remote
 * one.
 *
 * `held` is every artifact downstream of engine/medicham2-browser.js. `R` is the figures that have been
 * RELEASED — a key is absent while its artifact is withheld, so a page cannot read a stale value
 * out of this file. Nothing in here was computed, rounded or averaged by the WEB division:
 * membership comes from engine/quarantine.js and the values come from web/quarantine-release.json,
 * which was harvested out of the pages by script.
 *
 * Regenerate:  node web/build-quarantine.js
 */
(function (root) {
  var Q = {
    "generated": "2026-08-11T03:38:41.865Z",
    "by": "web/build-quarantine.js",
    "simulator": "engine/medicham2-browser.js",
    "open": true,
    "clauses": [
      {"name":"game differential","ok":true,"why":"clean: 0 of 20000 comparisons disagree with Showdown (seed 20260804) [read from data/engine-diff.json]"},
      {"name":"deliberate roster / items","ok":true,"why":"clean: 139 TESTED of 148 IN SCOPE, of 148 total (0 have NO LEGAL CARRIER in this format — a fact about the regulation) (1 deferred by the owner, still staged and printed) [read from data/roster.items.json]"},
      {"name":"deliberate roster / abilities","ok":true,"why":"clean: 94 TESTED of 202 IN SCOPE, of 316 total (114 have NO LEGAL CARRIER in this format — a fact about the regulation) (2 deferred by the owner, still staged and printed). 15 row(s) count in NEITHER column — the control arm is itself a live ability: aftermath, angerpoint, aromaveil, damp, flowerveil, fluffy, justified, keeneye, moxie, opportunist, rivalry, shellarmor, slushrush, stalwart, stickyhold [read from data/roster.abilities.json]"},
      {"name":"deliberate roster / moves","ok":true,"why":"clean: 427 TESTED of 500 IN SCOPE, of 500 total (0 have NO LEGAL CARRIER in this format — a fact about the regulation) (9 deferred by the owner, still staged and printed) [read from data/roster.moves.json]"},
      {"name":"coverage / every used mechanic is measured by something","ok":true,"why":"clean: all 412 moves above 25 clicks are measured by the roster or the census [read from engine/quarantine.js]"},
      {"name":"no open, known engine defect","ok":true,"why":"clean: the roadmap registers no open row describing a live engine defect [read from engine/quarantine.js]"}
    ],
    "failing": [],
    "n_quarantined": 47,
    "n_artifacts": 179,
    "rule": "CLAUDE.md — EVERYTHING DOWNSTREAM OF MEDICHAM IS WITHHELD UNTIL MEDICHAM IS CORRECT. Will, 2026-08-08: \"all engines that take medicham's output should be regarded as out of date and we should stop referencing them until medicham is up to date and we can rerun them.\"",
    "derivation": "node engine/quarantine.js --graph",
    "root": null,
    "play": [
      "build/build_scoreboard.js",
      "engine/all_mechanics_fire.js",
      "engine/backtest_winrate.js",
      "engine/board.js",
      "engine/board_drift.js",
      "engine/branch_recall.js",
      "engine/brood.js",
      "engine/build_lab.js",
      "engine/censoring_value.js",
      "engine/click_census.js",
      "engine/click_class.js",
      "engine/click_match.js",
      "engine/collinearity_audit.js",
      "engine/collinearity_fix.js",
      "engine/collinearity_joint.js",
      "engine/corpus_shift.js",
      "engine/derive_protocol_events.js",
      "engine/ditto.js",
      "engine/em_validation.js",
      "engine/explain_divergence.js",
      "engine/exploit.js",
      "engine/exploit_step_probe.js",
      "engine/exposure.js",
      "engine/feature_audit.js",
      "engine/feature_coverage.js",
      "engine/feature_engine_contrast.js",
      "engine/feature_fixture.js",
      "engine/fit_joint.js",
      "engine/fit_policy.js",
      "engine/game_differential.js",
      "engine/joint_rows.js",
      "engine/ko_calibration.js",
      "engine/ladder.js",
      "engine/leaf_engine_contrast.js",
      "engine/leaf_position_contrast.js",
      "engine/leaf_scoring.js",
      "engine/lookahead_cost.js",
      "engine/lookahead_divergence.js",
      "engine/mag_bot.js",
      "engine/magnemite.js",
      "engine/mechanics_coverage.js",
      "engine/medicham2-browser.js",
      "engine/medicham_coverage.js",
      "engine/mew.js",
      "engine/mew_farm.js",
      "engine/miltank.js",
      "engine/opponent_calibration.js",
      "engine/opponent_recall.js",
      "engine/play.js",
      "engine/player_digest.js",
      "engine/position_features.js",
      "engine/pp_board_probe.js",
      "engine/preflight.js",
      "engine/protect_calibration.js",
      "engine/quarantine.js",
      "engine/recall_at_k.js",
      "engine/redirect_audit.js",
      "engine/replay_differential.js",
      "engine/rollout_leaf.js",
      "engine/rollout_r1.js",
      "engine/rollout_r2.js",
      "engine/rollout_r3.js",
      "engine/rollout_switch_probe.js",
      "engine/selftest.js",
      "engine/sheet_channel_value.js",
      "engine/showdown_bot.js",
      "engine/status.js",
      "engine/surprise.js",
      "engine/tag_dex.js",
      "engine/tag_exposure.js",
      "engine/train_policy.js",
      "engine/truncation_curve.js",
      "engine/variance.js"
    ],
    "classified": [
      "data/ab-batch-effect.json",
      "data/ability-blocks.json",
      "data/abra-meta.js",
      "data/abra-tags.js",
      "data/all-mechanics-fire.json",
      "data/archetypes.json",
      "data/board-browser-baseline.json",
      "data/board-data.js",
      "data/bring-bias.json",
      "data/bring-priors.json",
      "data/brood.json",
      "data/calibration.json",
      "data/censoring-value.json",
      "data/chomp-ev.json",
      "data/click-censoring-census.json",
      "data/click-counts.json",
      "data/collinearity-audit.json",
      "data/collinearity-fix.json",
      "data/collinearity-joint.json",
      "data/conformance-baseline.json",
      "data/conformance.json",
      "data/core-matchups.json",
      "data/counterplay.json",
      "data/counters.json",
      "data/damage-validation.json",
      "data/degradation-budgets.json",
      "data/diff-swarm.json",
      "data/diff-team-pool.json",
      "data/docs-currency-baseline.json",
      "data/double-protect.json",
      "data/dusk-size-gate.json",
      "data/dynamics.json",
      "data/effective-identity-baseline.json",
      "data/engine-data.js",
      "data/engine-diff.json",
      "data/eval-report.json",
      "data/exploit-step-probe-reparam.json",
      "data/exploit-step-probe.json",
      "data/exploitability-machamp.json",
      "data/exploitability-mag.json",
      "data/exploitability.json",
      "data/feature-audit.json",
      "data/feature-engine-contrast.json",
      "data/format-audit.json",
      "data/game-diff.json",
      "data/game-differential.json",
      "data/guru-matchups.json",
      "data/guru.js",
      "data/illusion.json",
      "data/interaction-matrix.json",
      "data/jolteon-weights.json",
      "data/json-nan-guard-baseline.json",
      "data/kad-replays.js",
      "data/ladder.json",
      "data/leaf-engine-contrast.json",
      "data/leaf-position-contrast.json",
      "data/live.js",
      "data/lookahead-bound.json",
      "data/lookahead-clock-control.json",
      "data/lookahead-cost.json",
      "data/mag.js",
      "data/mc-key-baseline.json",
      "data/mechanics-census.json",
      "data/mechanics-rank.json",
      "data/mechanics-surface.json",
      "data/medicham-bench.json",
      "data/medicham-coverage.json",
      "data/mega-decision.json",
      "data/mega-dex-official.json",
      "data/mega-dex.json",
      "data/mega-formes.js",
      "data/mega-usage.json",
      "data/meta-usage.json",
      "data/mew.js",
      "data/million-targets.json",
      "data/move-effects.js",
      "data/move-priors.json",
      "data/mutation-coverage.json",
      "data/nature-arms.json",
      "data/nmf-rank-selection.json",
      "data/nmf-roles.json",
      "data/nmf.js",
      "data/opponent-calibration.json",
      "data/opponent-recall.json",
      "data/partial-label-em.json",
      "data/playstyle-matchups.json",
      "data/pokemon-roles.json",
      "data/policy-eval.json",
      "data/policy-weights-joint-presheet.json",
      "data/policy-weights-joint.json",
      "data/policy-weights.json",
      "data/pory-eval.json",
      "data/pory-nn.json",
      "data/pory.js",
      "data/porygon2-curve.json",
      "data/porygon2-open.json",
      "data/porygon2-separation-gate.json",
      "data/porygon2-species.json",
      "data/porygon2.json",
      "data/porygon2c-dist.json",
      "data/porygon2c.json",
      "data/pp-board-probe.json",
      "data/protocol-events.json",
      "data/provenance-stamp.json",
      "data/quarantine-stamp.json",
      "data/recall-at-k.json",
      "data/redirect-audit.json",
      "data/regulation-usage.json",
      "data/release-census.json",
      "data/replay-differential-bo3.json",
      "data/replay-differential-freezes.json",
      "data/replay-differential-sheets.json",
      "data/replay-differential.json",
      "data/rerun-list.json",
      "data/role-matchups.json",
      "data/roles-eval.json",
      "data/roles.js",
      "data/rollout-cost.json",
      "data/rollout-cost.meta.json",
      "data/rollout-r1-explore-sweep.json",
      "data/rollout-r1-explore1-rows-3932186b59ef.meta.json",
      "data/rollout-r1-explore1-rows-6e43710396db.meta.json",
      "data/rollout-r1-explore1-rows.meta.json",
      "data/rollout-r1-explore1.json",
      "data/rollout-r1-greedy-rows-3932186b59ef.meta.json",
      "data/rollout-r1-withdrawn-join.json",
      "data/rollout-r1.json",
      "data/rollout-r3.json",
      "data/rollout-r3.meta.json",
      "data/rollout-r4.json",
      "data/rollout-switch-census.json",
      "data/rollout-switch-probe.json",
      "data/roster.abilities.json",
      "data/roster.abilities.pre-shape-rules.json",
      "data/roster.abilities.prev.json",
      "data/roster.all.json",
      "data/roster.items.json",
      "data/roster.items.prev.json",
      "data/roster.json",
      "data/roster.moves.json",
      "data/roster.moves.prev.json",
      "data/roster.moves.staging-trial.json",
      "data/rulebook-collision.json",
      "data/scenario-catalogue.json",
      "data/scoreboard.js",
      "data/scoreboard.json",
      "data/sheet-channel-value.json",
      "data/sheet-usage.json",
      "data/silent-catch-baseline.json",
      "data/site-data-orphans.json",
      "data/slowking-eval.json",
      "data/slowking-playstyle-eval.json",
      "data/slowking-playstyle.js",
      "data/slowking.js",
      "data/smogon-priors-bo3.json",
      "data/smogon-priors.json",
      "data/species-abilities.json",
      "data/species-sets.json",
      "data/state-ladder.json",
      "data/status.js",
      "data/store-validation.json",
      "data/strong-player-baseline.json",
      "data/tag-consumption.json",
      "data/tag-walk.json",
      "data/tags.json",
      "data/trajectories.sample.json",
      "data/unmodelled-clicks.json",
      "data/value-net.json",
      "data/vocab-usage.json",
      "data/war.json",
      "data/weight-multiplicity.json",
      "data/winrate-backtest.json",
      "data/wire-ladder-census.pin.json",
      "data/wire-ladder.json",
      "data/xatu-belief.json",
      "data/xatu-context-sets.json",
      "data/xatu-context.json",
      "data/xatu.js",
      "data/xatu.json"
    ],
    "held": {},
    "sources": {
      "stadium.ctrl.medicham": "data/winrate-backtest.json",
      "stadium.ctrl.mag": "data/policy-weights.json",
      "stadium.ctrl.miltank": "data/rollout-r4.json",
      "stadium.ctrl.miltank#rollout-r3": "data/rollout-r3.json",
      "stadium.ctrl.doduo": "data/policy-weights-joint.json",
      "stadium.ctrl.wobbuffet": "data/exploitability.json",
      "stadium.ctrl.wobbuffet#policy-weights": "data/policy-weights.json",
      "stadium.ctrl.machamp": "data/ladder.json",
      "stadium.ctrl.machamp#policy-weights": "data/policy-weights.json",
      "stadium.ctrl.ditto": "data/winrate-backtest.json",
      "stadium.text.medicham.honest": "data/winrate-backtest.json",
      "stadium.text.mag.job": "data/policy-weights.json",
      "stadium.stat.mag.Features": "data/policy-weights.json",
      "stadium.stat.mag.Decisions fitted": "data/policy-weights.json",
      "stadium.stat.miltank.Beats MAG greedy": "data/rollout-r4.json",
      "stadium.stat.miltank.Corpus": "data/rollout-r4.json",
      "stadium.stat.miltank.Splits discarded": "data/rollout-r4.json",
      "stadium.stat.miltank.Divergence from MAG": "data/rollout-r3.json",
      "stadium.text.miltank.honest": "data/rollout-r4.json",
      "stadium.stat.doduo.Coordination features": "data/policy-weights-joint.json",
      "stadium.stat.doduo.Predicting the human PAIR": "data/policy-weights-joint.json",
      "stadium.text.doduo.honest": "data/policy-weights-joint.json",
      "stadium.stat.wobbuffet.Beat MAG, current build": "data/exploitability.json",
      "stadium.stat.wobbuffet.Vector then / now": "data/exploitability.json",
      "stadium.stat.wobbuffet.Rounds run": "data/exploitability.json",
      "stadium.text.wobbuffet.honest": "data/exploitability.json",
      "stadium.stat.machamp.Generations run": "data/ladder.json",
      "stadium.stat.machamp.Vector then / now": "data/policy-weights.json",
      "stadium.stat.mew.Mirror symmetry": "data/exploitability.json",
      "models.machamp.gens": "data/ladder.json",
      "models.machamp.vector": "data/policy-weights.json",
      "models.miltank.leaf": "data/winrate-backtest.json",
      "index.jolteon.winrate": "data/winrate-backtest.json"
    },
    "withheld_keys": [],
    "R": {
      "stadium.ctrl.medicham": {
        "buckets": [
          [
            "0-10%",
            "52",
            "53.85%",
            0.0619,
            0.5385
          ],
          [
            "10-20%",
            "93",
            "55.91%",
            0.1555,
            0.5591
          ],
          [
            "20-30%",
            "160",
            "51.25%",
            0.2513,
            0.5125
          ],
          [
            "30-40%",
            "177",
            "52.54%",
            0.3504,
            0.5254
          ],
          [
            "40-50%",
            "201",
            "46.27%",
            0.4447,
            0.4627
          ],
          [
            "50-60%",
            "206",
            "50.97%",
            0.5505,
            0.5097
          ],
          [
            "60-70%",
            "189",
            "51.32%",
            0.6454,
            0.5132
          ],
          [
            "70-80%",
            "145",
            "57.24%",
            0.7468,
            0.5724
          ],
          [
            "80-90%",
            "99",
            "54.55%",
            0.8461,
            0.5455
          ],
          [
            "90-100%",
            "56",
            "53.57%",
            0.9366,
            0.5357
          ]
        ],
        "ece": "0.1811",
        "acc": "51.0%",
        "accn": "1,314",
        "accci": "[48.3, 53.7]",
        "brier": "+0.0502",
        "brierci": "[0.0371, 0.0628]",
        "uses": "56"
      },
      "stadium.ctrl.mag": {
        "top1": [
          "20.0%",
          "23.1%",
          "32.3%"
        ],
        "gain": "+9.2 points",
        "feats": "58",
        "games": "8,414",
        "dec": "220,613",
        "held": "44,033",
        "greedy": "79.7%"
      },
      "stadium.ctrl.miltank": {
        "arm1": "297",
        "split": "777",
        "arm2": "238",
        "pairs": "1,312",
        "games": "2,624",
        "dec": "535",
        "win": "55.5%",
        "ci": "[51.3, 59.7]",
        "floor": "31.4%"
      },
      "stadium.ctrl.miltank#rollout-r3": {
        "div": "80.2%",
        "divn": "121"
      },
      "stadium.ctrl.doduo": {
        "pairFeats": "18",
        "apart": "10.1%",
        "zeroed": "9.4%",
        "joint": "12.2%",
        "turns": "81,515",
        "held": "14,995",
        "games": "7,454"
      },
      "stadium.ctrl.wobbuffet": {
        "was": [
          "63.2%",
          "49.7%"
        ],
        "ci": [
          "[56.6, 69.3]",
          "[46.2, 53.2]"
        ],
        "rounds": "24",
        "per": "220",
        "weights": "17"
      },
      "stadium.ctrl.wobbuffet#policy-weights": {
        "now": "58"
      },
      "stadium.ctrl.machamp": {
        "gens": "2 of 6"
      },
      "stadium.ctrl.machamp#policy-weights": {
        "vecNow": "58"
      },
      "stadium.ctrl.ditto": {
        "leaf": "51.0%",
        "leafn": "1,314",
        "leafci": "[48.3, 53.7]",
        "ece": "0.1811"
      },
      "stadium.text.medicham.honest": "Its win% does not beat a coin. On the held-out fifth the live in-game leaf is <em>worse</em> than a coin on Brier — paired +0.0502, 95% CI [0.0371, 0.0628], where lower is better — and it names the winner on 51.0% of 1,314 decisive calls, 95% CI [48.3, 53.7], an interval that contains chance, with ECE 0.1811 (<code>data/winrate-backtest.json</code>). This cabinet previously read <s class='wd' title='Withdrawn 2026-08-04 — the 2026-07-23 reading, superseded by data/winrate-backtest.json measured 2026-08-04, which puts accuracy at 51.0% with a CI containing 50%.'>log-loss 1.2 against 0.69 and ~44% of decisive calls, which is below chance and therefore systematically inverted</s>; the current artifact does not support the inversion, so it is struck out here rather than quietly deleted. The damage math is validated. The win probability is a matchup heuristic wearing a probability's clothes.",
      "stadium.text.mag.job": "The live policy — the thing that actually clicks. 58 features off a reconstructed board, fitted to real human choices by conditional logit over 8,414 clean open-sheet games and 220,613 decisions, as recorded by <code>data/policy-weights.json</code>.",
      "stadium.stat.mag.Features": {
        "v": "58",
        "n": "Up from 12 at v3.21.0. <code>data/policy-weights.json</code>."
      },
      "stadium.stat.mag.Decisions fitted": {
        "v": "220,613",
        "n": "176,580 train / 44,033 held out. <code>data/policy-weights.json</code>."
      },
      "stadium.stat.miltank.Beats MAG greedy": {
        "v": "55.5%",
        "n": "Of 535 decisive pairs, CI [51.3, 59.7]. <code>data/rollout-r4.json</code>."
      },
      "stadium.stat.miltank.Corpus": {
        "v": "2,624 games",
        "n": "1,312 seed pairs. <code>data/rollout-r4.json</code>."
      },
      "stadium.stat.miltank.Splits discarded": {
        "v": "777",
        "n": "1-1 pairs the SPRT cannot score. <code>data/rollout-r4.json</code>."
      },
      "stadium.stat.miltank.Divergence from MAG": {
        "v": "80.2%",
        "n": "Over 121 decisions. <code>data/rollout-r3.json</code>."
      },
      "stadium.text.miltank.honest": "The run stopped at an SPRT boundary, so 55.5% is <em>biased high</em> by the stopping rule — the verdict carries the error rate, the point estimate does not. There is no A/A noise floor for this comparison; three split-half cuts (0.2, 3.9, 1.3 points against an effect of 5.5) stand in for one and are labelled a substitute, and all four figures are carried by <code>data/rollout-r4.json</code> itself. And the engine moved after the games were played, so transfer to the current build is an assumption the artifact states rather than tests.",
      "stadium.stat.doduo.Coordination features": {
        "v": "18",
        "n": "On top of the single-action ones. <code>docs/MODELS.md</code>."
      },
      "stadium.stat.doduo.Predicting the human PAIR": {
        "v": "12.2%",
        "n": "Top-1, against 10.1% scoring the slots apart and 9.4% with the pair terms zeroed, over 14,995 held-out joint turns. <code>docs/MODELS.md</code>."
      },
      "stadium.text.doduo.honest": "This was retired once and the retirement was wrong. It rested on the double-target rate — 24.6% against humans' 23.2%, recorded in <code>docs/MODELS.md</code> — and that statistic touches 2 of the 18 features. Judging a team-coordination model by a targeting number is judging a ninth of it. The <em>second</em> retirement was also wrong, and for a sharper reason: <code>engine/fit_joint.js</code> required a candidate's target to match the human's, and a spread move is built with no target at all, so 1,393 of 1,397 spread clicks were discarded and the fit ran on 24,997 of 82,483 joint turns. Refitted on 63,305, the feature the old cabinet used as its illustration flips sign — <code>spreadFreeBesideAlly</code> <s class='wd' title='Withdrawn 2026-08-01 per docs/MODELS.md — −5.054 was produced by the spread-matcher defect described in this paragraph, not by a human preference. The refit on 63,305 turns gives +0.863, and data/policy-weights-joint.json carries +0.799 today.'>−5.054</s> becomes <em>+0.863</em>, and <code>data/policy-weights-joint.json</code> carries +0.799 today.",
      "stadium.stat.wobbuffet.Beat MAG, current build": {
        "v": null,
        "n": "<b>There is no number.</b> The old one read <s class='wd' title='Retracted 2026-08-04 — a 17-feature run against the 58 we ship, on an engine 25 wire-fixes old, computed before the quality filter existed.'>63.2%, CI [56.6, 69.3]</s> and is retracted: 17 features against the <b>58</b> we ship, an engine 25 wire-fixes old, computed before the quality filter existed. The 2026-08-04 re-run (5,500 games + a 1,600-game replay) is <b>VOID</b> — MAG itself was refitted mid-search, so the two legs defended with different weight vectors. <code>data/exploitability.json</code> now declares <code>void: true</code> and <code>provenance.js</code> reads it UNSAFE. Blocked on a frozen engine release, and on a step rule that survives 58 dimensions: the hill-climb accepted <b>1 of 24</b> steps against 10 of 18 at 17 features, so even on a still tree it would have returned an uninformative null."
      },
      "stadium.stat.wobbuffet.Vector then / now": {
        "v": "17 / 58",
        "n": "Then <code>data/exploitability.json</code>, now <code>data/policy-weights.json</code>."
      },
      "stadium.stat.wobbuffet.Rounds run": {
        "v": "18",
        "n": "220 games per evaluation, seed 90210. <code>data/exploitability.json</code>."
      },
      "stadium.text.wobbuffet.honest": "This is the most important number in the repo and we currently cannot quote it. <code>engine/provenance.js --strict</code> marks <code>data/exploitability.json</code> UNSAFE on two counts — it predates the quality filter, so it was computed under different rules about which games count, and it predates <code>data/policy-weights.json</code>, the weights it is supposed to be attacking. It searched <b>17</b> weights; we ship <b>58</b>. Nothing about the method is wrong and nothing here says the leak was closed; the run simply describes a player we no longer are, and shipping greedy-over-sampling since then made that player <em>more</em> deterministic rather than less. Read the rest with that in front of it: exploitability grades <em>can a prepared opponent read us</em>, an adversary who studies you over many games, and a tournament opponent has never seen you play. It was also a LOWER bound by construction — the search moved only MAG's own weights, so a wider policy class would find at least as much.",
      "stadium.stat.machamp.Generations run": {
        "v": "2 of 6",
        "n": "Recorded no verdict. <code>docs/MODELS.md</code>."
      },
      "stadium.stat.machamp.Vector then / now": {
        "v": "17 / 58",
        "n": "Then <code>docs/MODELS.md</code>, now <code>data/policy-weights.json</code>."
      },
      "stadium.stat.mew.Mirror symmetry": {
        "v": "49.7%",
        "n": "95% CI [46.2, 53.2] on 782 battles — <code>data/exploitability-holdout.json</code>, field <code>mirror</code>. That artifact declares <code>void: true</code>, and its own <code>void_reason</code> names this one figure as the exception that survives, because both of its legs fall inside a single stable window. It retires a live worry: the 47.0% round-0 mirror at n=217 in <code>data/exploitability.json</code> was noise, not a seat or pairing asymmetry biasing every other row. A second round-0 mirror of <s class='wd' title='Struck 2026-08-05 — NOT MEASURED. No artifact under data/ carries a 47.5% mirror control; exploitability.json reads 47.0% at n=217. The figure was typed here and has no source.'>47.5%</s> used to be quoted beside it and is NOT MEASURED."
      },
      "models.machamp.gens": "<text x=\"34\" y=\"1236\" class=\"st\" fill=\"#8a5a1a\">HALF-RUN AND NO VERDICT: the run on disk stopped after 2 of the 8</text>\n<text x=\"34\" y=\"1248\" class=\"st\" fill=\"#8a5a1a\">generations it asked for, on a 48-feature vector<tspan x=\"34\" dy=\"10\" class=\"src\">generations / gensRequested / features in data/ladder.json</tspan></text>",
      "models.machamp.vector": "<text x=\"34\" y=\"1276\" class=\"st\" fill=\"#9a2b2b\">its champion vector was DELETED — 48 features against MAG's 58<tspan x=\"34\" dy=\"10\" class=\"src\">features in data/policy-weights.json · docs/MODELS.md calls it the largest untested lever here</tspan></text>",
      "models.miltank.leaf": "<text x=\"34\" y=\"1456\" class=\"st\" fill=\"#9a2b2b\">its in-game judge names the winner on</text>\n<text x=\"34\" y=\"1470\" class=\"st\" fill=\"#9a2b2b\">51.0% of decisive calls, CI 48.3–53.7 <tspan x=\"34\" dy=\"11\" class=\"src\">from data/winrate-backtest.json</tspan></text>\n<text x=\"34\" y=\"1497\" class=\"st\" fill=\"#9a2b2b\">— the interval contains a coin</text>",
      "index.jolteon.winrate": "MEDICHAM's in-game win meter is measured <b>worse than a coin</b> on Brier and names the winner on 51.0% of decisive calls (95% CI 48.3–53.7, <code>data/winrate-backtest.json</code>)"
    }
  };

  /* ---- the one question every page asks ------------------------------------------------------
     Returns null when the figure may be shown, and the reason record when it may not. It answers
     "no" whenever the gate is OPEN, so a page needs no second branch for the healthy case. */
  Q.heldFor = function (p) {
    if (Q.open !== false) return null;
    var k = String(p).replace(/^(?:\.\.?\/)+/, '');
    /* THE ROOT ANSWERS THROUGH THE SAME QUESTION. A page can skip every artifact and load the
       SIMULATOR — web/tower.html does, and plays a live battle out of it — in which case there is no
       artifact to withhold and the figures on screen were computed by the engine under repair on this
       visit. `play` is engine/quarantine.js's own play layer, so a room that loads a different file
       that reaches the simulator is answered too, without a list anybody maintains. */
    if (Q.root && (k === Q.root.file || (Q.play || []).indexOf(k) >= 0)) {
      if (k === Q.root.file) return Q.root;
      return { file: k, root: true, rerun: Q.root.rerun, clause: Q.root.clause,
               because: 'it reaches ' + Q.root.file + ' through require, and ' + Q.root.because };
    }
    if (k.indexOf('data/') !== 0) k = 'data/' + k;
    return Q.held[k] || null;
  };
  /* A RELEASED figure. Absent while its artifact is withheld — the key is not in the payload at all,
     so a page cannot accidentally read a stale value out of it. */
  Q.rel = function (k) { return (Q.R && Q.R[k]) || null; };

  /* ---- THE THIRD ANSWER: UNCLASSIFIED. ------------------------------------------------------
     engine/quarantine.js prints ~20 artifacts that have NO ROW in the dependency graph and refuses
     to default them either way — "the set holds instruments AND consumers, so it cannot be defaulted".
     A page needs the same three-valued answer, because a bundle can be CLEARED itself and still
     re-encode a figure out of a file nothing can classify: data/status.js is a clear row whose DODUO
     line is a 194,514-game head-to-head played by this simulator. Defaulting that to "publish" is how
     a leak walks past a graph that never claimed it was safe. */
  Q.gateFor = function (p) {
    var k = String(p).replace(/^(?:\.\.?\/)+/, '');
    if (k.indexOf('data/') !== 0 && k.indexOf('engine/') !== 0 && k.indexOf('build/') !== 0) k = 'data/' + k;
    if (Q.heldFor(k)) return 'held';
    if (Q.open !== false) return 'clear';   /* gate open: nothing is withheld and nothing is pending */
    return (Q.classified || []).indexOf(k) >= 0 ? 'clear' : 'unclassified';
  };

  Q.esc = function (s) { return String(s).replace(/[&<>]/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]; }); };

  /* ---- THE PLATE. Full visual weight, never a footnote. --------------------------------------
     docs/WEB.md: a missing measurement is rendered at the same weight as a real one, and
     engine/quarantine.js: "a caption is not a quarantine". This is the caption's replacement — the
     number is gone and its whole space is given to why it is gone and what brings it back. */
  Q.plate = function (p, o) {
    var h = Q.heldFor(p); if (!h) return '';
    o = o || {};
    var dark = o.theme === 'dark';
    var bg = dark ? '#2a0f0c' : '#fff5f3', fg = dark ? '#ffe2dc' : '#5b2a20',
        line = dark ? '#ff6b57' : '#ff6b57', hd = dark ? '#ff9c8f' : '#c0432f';
    return '<div class="qplate" data-q="' + Q.esc(h.file) + '" role="note" style="background:' + bg +
      ';border:2px solid ' + line + ';border-left:7px solid ' + line + ';border-radius:12px;padding:14px 16px;margin:12px 0;color:' + fg + '">' +
      '<div style="font-size:11px;letter-spacing:.14em;font-weight:800;color:' + hd + '">QUARANTINED — THE FIGURE IS WITHHELD, NOT ANNOTATED</div>' +
      (o.subject ? '<div style="font-size:15px;font-weight:800;margin-top:6px">' + Q.esc(o.subject) + '</div>' : '') +
      /* THE ROOT NEEDS ITS OWN SENTENCE. "engine/medicham2-browser.js is downstream of
         engine/medicham2-browser.js" is not a reason, and "re-run it" is the wrong instruction for a
         room that stored nothing — it recomputed on this visit, so what it is waiting for is the gate. */
      (h.root
        ? '<p style="margin:8px 0 0;font-size:12.5px;line-height:1.6;max-width:70ch"><b>' + Q.esc(h.file) + '</b> is the SOURCE of the quarantine' +
            (h.file === Q.root.file ? '' : ' — ' + Q.esc(h.because)) +
            '. Nothing this room shows was read out of an artifact: it is computed live by the engine that is under repair, so there is no stored figure to withhold and the room is withheld instead.</p>' +
          '<p style="margin:6px 0 0;font-size:12.5px;line-height:1.6;max-width:70ch">' + Q.esc(h.clause) + '. ' +
            'Nothing here has to be re-run when the gate opens — nothing was stored. The room comes back the moment it does.</p>'
        : '<p style="margin:8px 0 0;font-size:12.5px;line-height:1.6;max-width:70ch"><b>' + Q.esc(h.file) + '</b> is downstream of ' +
            Q.esc(Q.simulator) + ' — ' + Q.esc(h.because) + '.</p>' +
          '<p style="margin:6px 0 0;font-size:12.5px;line-height:1.6;max-width:70ch">' + Q.esc(h.clause) + '. ' +
            'A quarantined number does not become true when MEDICHAM becomes correct; it becomes re-runnable.</p>') +
      (h.rerun ? '<p style="margin:6px 0 0;font-size:12.5px">' + (h.root ? 'Read the gate' : 'Re-run it') +
        ': <code style="background:' + (dark ? '#120504' : '#20344a') +
        ';color:#e6ecf8;padding:2px 7px;border-radius:5px">' + Q.esc(h.rerun) + '</code></p>' : '') +
      '<p style="margin:8px 0 0;font-size:11.5px;opacity:.8;max-width:70ch">Derivation: <code>' + Q.esc(Q.derivation) +
        '</code>. Nothing here is a list somebody maintains — the withheld set falls out of one root.</p>' +
      '</div>';
  };

  /* ---- THE CHIP. What a withheld figure looks like INSIDE a sentence. ------------------------- */
  Q.chip = function (p) {
    var h = Q.heldFor(p); if (!h) return '';
    return '<span class="qchip" data-q="' + Q.esc(h.file) + '" title="' + Q.esc(h.file + ' — ' + h.because + '. ' + h.clause) +
      '" style="display:inline-block;background:#ff6b57;color:#fff;font-weight:800;font-size:11px;letter-spacing:.08em;' +
      'padding:1px 7px;border-radius:5px;white-space:nowrap">QUARANTINED</span>';
  };

  root.ABRA_QUARANTINE = Q;
})(typeof window !== 'undefined' ? window : this);
